### ISSUE TITLE
Sass challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#1]
@AkiraLaine is in charge of coordinating the creation of our Sass challenges. 

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

Here are the challenges we have currently planned:
- [ ] CSS with Superpowers 
- [ ] Storing Data with Sass Variables
- [ ] Nesting your CSS
- [ ] Mixing the Cake
- [ ] Using if and else
- [ ] Continuing with for
- [ ] Expanding with each
- [ ] Wrapping up with while
- [ ] Using Sass Partials
- [ ] Extend your CSS styles

**Comment by AkiraLaine** [comment]
@QuincyLarson For the test suite, how are we gonna test Sass? Also, I have most of the seed code, but we will be using multi-tabs for this, right?

**Comment by QuincyLarson** [comment]
@AkiraLaine I suspect we'll have to test it partially using regex, unless we can come up with a better way using Mocha Chai. And yes, @BerkeleyTrue is still working on the multitab editor support. Our goal is to get as much information as possible into these issues, then port that to the seed files once the multitab editor is available, as part of the new challenge integration process.

**Comment by AkiraLaine** [comment]
#### CSS with Superpowers

##### Description
Q: How can we write better CSS?
A: Use a preprocessor.

What are CSS preprocessors?
CSS preprocessors take code written in the preprocessed language and then convert that code into CSS. Pretty basic, right?

So what's the point of using one?
CSS preprocessors such as <code>Sass</code> or <code>Less</code> allow you to do nifty things that regular CSS can't do. They enable you to create <code>variables</code>, write more compact code with <code>nesting</code>, <code>import</code> other CSS files and much more.

In this series of Challenges, we will be teaching you the basics of <code>Sass</code>

##### Tests
None

##### Seed
None

##### Solution
None

**Comment by AkiraLaine** [comment]
#### Storing Data with Sass Variables

##### Description
Just like in Javascript, you can declare variables to store data in.
In JavaScript, you would use the <code>var</code> keyword to define a variable. When declaring variables in <code>Sass</code>, you start by using a <code>$</code> followed by a string.
Here is an example: <code>$color: green;</code>
Making variables becomes exteremly useful when we want similar elements to have the same color, for example. If you wanted to change the color to a slightly different shade, all we would have to do is change the variable's value.
<h4>Instructions</h4>
Create a variable <code>$text-color</code> and set it equal to <code>red</code>
Then change the value of all <code>color</code> properties by using <code>color: $text-color</code>.
Finally, change the value of <code>$text-color</code> to another color and see how all respective elements change color!

##### Tests
None yet

##### Seed
```
<style>
  /*Only change code below this line.*/
  
  /*Only change code above this line.*/
  .header{
    text-align: center;
  }
  .blog-post h3{
  /*Only change code below this line.*/
    color: red;
  /*Only change code above this line.*/
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h3>Some random title</h3>
  <p>This is a paragraph with some very random text in it.</p>
</div>
<div class="blog-post">
  <h3>Header #2</h3>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h3>Here is another header</h3>
  <p>Even more random text within a paragraph.</p>
</div>
```
##### Solution
```
<style>
  /*Only change code below this line.*/
  $text-color: red;
  /*Only change code above this line.*/
  .header{
    text-align: center;
  }
  .blog-post h3{
  /*Only change code below this line.*/
    color: $text-color;
  /*Only change code above this line.*/
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h3>Some random title</h3>
  <p>This is a paragraph with some very random text in it.</p>
</div>
<div class="blog-post">
  <h3>Header #2</h3>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h3>Here is another header</h3>
  <p>Even more random text within a paragraph.</p>
</div>
```

**Comment by AkiraLaine** [comment]
#### Nesting your CSS

##### Description
<code>Nesting</code> is a really useful way of organising your CSS.
Normally, you would target each element on a different line to style it, like so:
<blockquote>nav{<br>&nbsp;&nbsp;background-color: red;<br>}<br><br>nav ul{<br>&nbsp;&nbsp;list-style: none;<br>}<br><br>li{<br>&nbsp;&nbsp;display: inline-block;<br>}</blockquote>
As you can imagine, in larger projects, your CSS file will get pretty messy. Here is where <code>nesting</code> comes in - it allows you to organise your different styles by nesting them within their respective parent elements:
<blockquote>nav{<br>&nbsp;&nbsp;background-color: red;<br><br>&nbsp;&nbsp;ul{<br>&nbsp;&nbsp;&nbsp;&nbsp;list-style: none;<br><br>&nbsp;&nbsp;&nbsp;&nbsp;li{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;display: inline-block;<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;}<br>}<br></blockquote>

Instructions
Use the <code>nesting</code> technique shown above to style both children of <code>.blog-post</code>. The <code>h1</code> **tag** should be **centred** and be blue. The <code>p</code> **tag** should have a font size of 20px.

##### Tests
None yet

##### Seed
```
<style>
/*Only change code below this line.*/
  
/*Only change code above this line.*/
</style>

<div class="blog-post">
  <h1>Blog Title</h1>
  <p>This is a paragraph</p>
</div>
```

##### Solution
```
<style>
/*Only change code below this line.*/
.blog-post {
  h1 {
   color: blue;
   text-align: center;
  }

  p {
    font-size: 20px
  }
}
/*Only change code above this line.*/
</style>

<div class="blog-post">
  <h1>Blog Title</h1>
  <p>This is a paragraph</p>
</div>
```

**Comment by SamAI-Software** [comment]
@AkiraLaine, nice start! :+1: 

[Storing Data with Sass Variables](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/1#issuecomment-230676514)
Small bug.

Instructions
> Finally, change the value of $text-color to another color and see how all respective elements change color!

Solution
```diff
<style>
  /*Only change code below this line.*/
- $text-color: red;
+ $text-color: blue;
  /*Only change code above this line.*/
```

[**Nesting your CSS**](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/1#issuecomment-230676974)
How about making it a bit more obvious for the first time?

Solution
```diff
 <style>
+ .blog-post {
 /*Only change code below this line.*/

 /*Only change code above this line.*/
+ }
 </style>
```

**Comment by QuincyLarson** [comment]
@AkiraLaine and @alayek are collaborating on creating regex-based tests for these challenges.

**Comment by alayek** [comment]
Would it be possible to use some JS library to parse SCSS to CSS? There is only so much RegEx we can write, and as we add more challenges, we would end up adding logic that exists in parsers.

Can we use some parsing library, without adding too much overload to our front-end assets
- [As a service - remote API call](http://docs.shipwrecked.apiary.io/#reference/0/using-the-client-side-compiler)
- [An in-browser JS library](https://github.com/medialize/sass.js/)
- [`npm` module, with `browserify`](https://github.com/tonyganch/gonzales-pe)

**Comment by abhisekp** [comment]
> I suspect we'll have to test it partially using regex

If possible, a text diff library maybe used for easy matching and compare.

**https://github.com/kpdecker/jsdiff**
Demo: **https://kpdecker.github.io/jsdiff/**

----
**Pane 1**
```scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li {
   display: inline-block; 
  }
}
```

----
**Pane 2**
```scss
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li{display: inline-block;}
}
```

----
@QuincyLarson @AkiraLaine

**Comment by QuincyLarson** [comment]
@abhisekp This diff tool looks awesome, but I don't think it would be particularly helpful in this case. The reason is with our tests, we want to minimize the likelihood of a false negative, and having more flexible regex tests is a proven way to do this.

**Comment by atjonathan** [comment]
@AkiraLaine are these challenges done? If so, you could mark them off in the issue description :+1:

**Comment by QuincyLarson** [comment]
@BerkeleyTrue will Sass work on beta now? 
@AkiraLaine so am I correct that these challenges are good to go as soon as we can add them to beta's seed files?

**Comment by AkiraLaine** [comment]
@QuincyLarson Hey! Sorry, I've really busy. So, i don't know what the status of the tests are there is still one challenge to make. But otherwise yes.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! We've loaded these challenges into the seed files and plan to deploy them to beta as soon as possible. 

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
