### ISSUE TITLE
Learn Information Security by Building a Contact Form

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#102]

**Comment by beaucarnes** [comment]
I assume this project is supposed to cover the content in the "Introduction to Information Security with HelmetJS Challenges" section from the current curriculum.

I do not think the project should be building a credit card form. Isn't it common knowledge that you should never create your own payment processing? There are so many potential security problems that it is best to use a third party to take care of everything.

Maybe instead this project can be about creating a user sign up form with a password and security questions.

"Learn Information Security by Building a User Sign-Up Form with HelmetJS".

What do you think, @scissorsneedfoodtoo @QuincyLarson ?

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, your analysis is spot on. I agree that we should change the project from building a credit card form to something else to avoid teaching bad practices. I like the idea of a sign up form, though it might be a bit similar to the signup page in https://github.com/freeCodeCamp/CurriculumExpansion/issues/99. Perhaps it could be another type of page to gather user information where security is important, something like a mailing list form, or a brief survey where the user also enters in their email address?

**Comment by QuincyLarson** [comment]
Hi @beaucarnes That's a good point. I don't know if a password and security question form would be much better though since it's a fool's errand to "roll your own authentication". (One of the reasons we use Auth0 for this). Can either of you think of another form-type project idea that could involve some of the helmet.js and/or OWASP features?

**Comment by beaucarnes** [comment]
I'm thinking "Learn Information Security by securing a Contact page".

The actual content of the page does not really matter as helmet.js can be used in any express web server. Since there are a few other projects where students build express servers from scratch, my idea is that the express server portion of the code for this project will already be written. The student will just have to add more security using helmet.js.

How does this sound @QuincyLarson ?

**Comment by scissorsneedfoodtoo** [comment]
You're right that the content of the page doesn't really matter here. A contact page sounds good because it might give us the opportunity to introduce some other concepts like validation and sanitization.

**Comment by QuincyLarson** [comment]
Agreed. A contact page is more realistic since you wouldn't generally want to roll your own credit card form either.

**Comment by GlynL** [comment]
Anyone working on this? I'd be happy to build something.

Imagining this is a simple frontend form submitting to a backend secured with Helmet.js?

**Comment by scissorsneedfoodtoo** [comment]
Hi @GlynL, this project is all yours.

Yes, that's right. Just a simple contact form with very limited or even no styling is fine, along with a simple backend like you mentioned. Please take a look at the [Contributor's Guide](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/CONTRIBUTING.md) before you start working on a prototype. And feel free to reach out if you have any questions or there's anything we can help out with.

**Comment by GlynL** [comment]
Here's a basic version. Let me know if this is what you were thinking. 

https://codesandbox.io/s/learn-information-security-by-building-a-contact-form-lmvm9?fontsize=14

**Comment by scissorsneedfoodtoo** [comment]
This is off to a great start. One suggestion I have is to consider adding more Helmet.js features. This project will be replacing the current lessons on information security, and should cover as many of those concepts as possible. Check out this Glitch project for more details about what's currently being taught: https://glitch.com/edit/#!/woozy-bill?path=myApp.js:10:0

**Comment by GlynL** [comment]
@scissorsneedfoodtoo I was thinking about this when I made it and included everything that was mentioned in the curriculum. If you check https://helmetjs.github.io/ most of the security methods are included by a simple `app.use(helmet())`. You can configure these or enable extras by passing a config object into the function.

Do we want to have people enabling them for the sake of teaching or do we want people to use it the normal way and then teach them to configure/add a couple of extra security features?

**Comment by scissorsneedfoodtoo** [comment]
@GlynL, I see. Didn't realize that most were enabled by default. In that case, it might be best to follow the current lesson structure as learners build the page. Explain a vulnerability and introduce a piece of middleware that solves it, then go back and refactor to use `app.use(helmet())` and a more normal configuration. Otherwise it seems like there won't be a good way to show all the different problems that Helmet.js solves. What do you think?

**Comment by GlynL** [comment]
@scissorsneedfoodtoo Yepp, I was wondering about that and it's probably best. I've updated my demo https://codesandbox.io/s/learn-information-security-by-building-a-contact-form-lmvm9?fontsize=14

The process I have in mind is:
* Enable each of the packages which are included by default separately.
* Let them know these are included by default using `helmet.use()` and get them to refactor.
* Then we can teach that it takes a configuration object which can enable additional features and change the settings or disable default packages.
* Get them to enable a couple which aren't default. Currently we teach `contentSecurityPolicy` and `noCache`.
* Possibly get them to tweak something. This might be necessary anyway depending on the environment. On Codesandbox you have to tweak `Frameguard` as they insert the browser into the page with an iframe.

**Comment by scissorsneedfoodtoo** [comment]
@GlynL, that all sounds great! Your demo also LGTM :+1: :+1: 

This should be ready to be broken down into steps. Your project is quite similar to the [Express Stock Trading](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/express-stock-trading-platform) one, so feel free to take a look at that and the [Contributor's Guide](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/CONTRIBUTING.md) before you start. Eventually we want this to work offline in the browser, so you can just include your HTML and JS files in your PR.

Also, if you have some time to hop on a call, please sent me an email at kris@freecodecamp.org. I'd be happy to talk more about your project and answer any questions you have.

**Comment by scissorsneedfoodtoo** [comment]
Hi @GlynL, did you have a chance to start breaking your project down?

**Comment by GlynL** [comment]
@scissorsneedfoodtoo Hi, I haven't had a chance yet. Just started a new job last week but I will have a look this week.

**Comment by scissorsneedfoodtoo** [comment]
@GlynL, no problem, thanks for the update. Take a look when you can and I look forward to seeing your lessons soon.

**Comment by GlynL** [comment]
@scissorsneedfoodtoo I've added created a project stepping through the helmet parts. Wasn't too sure whether to add steps for building out the express server and front-end or whether we will provide that as it's covered in other sections? Should I also create a pull request into the fcc repo yet?

https://github.com/GlynL/CurriculumExpansion/tree/Learn-Information-Security-by-Building-a-Contact-Form/Learn-Information-Security-by-Building-a-Contact-Form

**Comment by scissorsneedfoodtoo** [comment]
@GlynL, great, looks like it's headed in the right direction. We want learners to write as much of the code as possible for these projects, so please break down the form section of the HTML and the Express server as well. You're right that HTML and Express have been covered by other projects up to this point in the curriculum, but we imagine that the repetition of certain concepts would be good for retention.

I'm thinking this project can start of with some of the HTML already in place, and learners can write the form line by line since it's relevant to the project. Then they can write out the Express server before diving into all the Helmet stuff.

Please feel free to submit a PR any time and I'll do a more thorough review.

**Comment by scissorsneedfoodtoo** [comment]
Hi @GlynL, were you able to continue breaking this project down?

**Comment by scissorsneedfoodtoo** [comment]
Hi @GlynL, were you able to start working on your next draft? I left some review comments in https://github.com/freeCodeCamp/CurriculumExpansion/pull/212.

**Comment by GlynL** [comment]
@scissorsneedfoodtoo Hey, sorry I've been busy with some other things and hadn't noticed your comments. I'll have a look into it soon

**Comment by scissorsneedfoodtoo** [comment]
@GlynL, no problem. Take a look when you can and let me know if there's anything I can do to help.
