### ISSUE TITLE
Learn RESTful APIs by Building a Grocery List App

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#104]

**Comment by picolloo** [comment]
I'm interessed to participate in this one

**Comment by QuincyLarson** [comment]
@picolloo OK - cool. You have expressed interest in several of these. I recommend tackling these one at a time. Which project do you want to build first?

**Comment by picolloo** [comment]
So I'll finisih those I'm involved with and help with this one later if it's necessary

**Comment by ritute** [comment]
Is the type of service set in stone for this, or can we suggest a different one (such as a recipe book) that would be simpler and translate better to a typical application, since weather is something usually read from another service (openweathermap) and would be more unusual to implement (it also consists largely of numeric data that would make the API more cumbersome in testing and potentially detract from the goal of this learning project).

**Comment by QuincyLarson** [comment]
@ritute the service isn't set in stone. And we won't be using a real API - we'll just use dummy data for reliability, and so that the curriculum can still be completed without internet access (we are gradually working toward making freeCodeCamp an offline-first application.)

**Comment by scissorsneedfoodtoo** [comment]
@ritute, just wanted to check in and see if you've made any progress on this. Please let me know if there's anything I can help with.

**Comment by shimphillip** [comment]
@scissorsneedfoodtoo 

I am also interested in taking this one. Can I take two projects at a time?

**Comment by scissorsneedfoodtoo** [comment]
@shimphillip, sorry, but it's best if you just take one at a time. Which project would you like to work on first? This one, or the shopping cart?

**Comment by beaucarnes** [comment]
@shimphillip Are you going to work on this one? If not, I can give it a try.

**Comment by shimphillip** [comment]
@beaucarnes Sure you can take it.

**Comment by beaucarnes** [comment]
I've been working on this a bit and have been thinking about the best way to show aspects of a RESTful API. I think @ritute was right with the comment about how a weather API is not the best project for this. Weather APIs mainly only accept GET requests. But to really learn about RESTful APIs people should see all the basic CRUD routes. 

In my opinion, the MongoDB project (issue #103 ) is already the exact thing that this project should be. That project is a RESTful API. I think we should consider removing this project from the curriculum.

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, yes, I agree. While I could see this as a high level overview of RESTful APIs, teaching all the core concepts would lead to a lot of overlap with the MongoDB Movie Review DB project. It would probably be better to remove this project and rename the MongoDB project to something like "Learn RESTful APIs and Express by Building a Movie Review Database", or even just "Learn RESTful APIs by Building a Movie Review Database".

What do you think, @QuincyLarson?

**Comment by QuincyLarson** [comment]
@beaucarnes Even if the project accomplishes much the same goals as the MongoDB project, we should build in a bit more redundancy into the curriculum so learners get more opportunities to practice. 

Rather than removing this from the curriculum, I recommend we come up with a similar project, so that learners can practice the the CRUD operations in the context of just an API before they start mixing in the additional complexity (real or perceived) of MongoDB.

I agree with your reasoning that this should not be a weather app. Can you think of a similar type of project we could use for to teach CRUD?

**Comment by beaucarnes** [comment]
"Learn RESTful APIs by Building a Grocery List App"

I created a simple Node / Express server API to keep track of a grocery list. I tested it locally and it works as expected. Instead of storing data using a database, it just stores data in memory using an array.

If @QuincyLarson / @scissorsneedfoodtoo likes this idea, I will start creating instructions.

Here is the code: https://gist.github.com/beaucarnes/6cca9d24744c8cbcdabf84d212c83515

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, this is a great idea. Using an array for temporary storage is a good way to shift the focus away from databases while still teaching CRUD operations.

**Comment by QuincyLarson** [comment]
@beaucarnes Great idea. I've updated the title of this project.

**Comment by beaucarnes** [comment]
I just made a PR with the code and tests for this project.
