### ISSUE TITLE
Learn Express.js by Building an Stock Trading Platform

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#105]

**Comment by lmilliken** [comment]
I would be interested in helping out with this.  Since this is to learn Express.js, this module would teach how to create API endpoints to buy or sell stocks?

**Comment by QuincyLarson** [comment]
@lmilliken Yes - it would teach people how to create API endpoints for buying and selling stocks, and checking their value. We would welcome your help with this. Note that we won't actually be running the API in express - we will have dummy endpoints that get stock prices for fictitious stocks. So you can design this however you want, and we can add additional paths as necessary (for example, /stock-app/buy/grape-computer-company and things like that 👍

**Comment by lmilliken** [comment]
Ok, I can help with this.  Here is a draft in Glitch: https://glitch.com/edit/#!/lxm-trade
Let me know if you have any initial feedback/direction.

**Comment by scissorsneedfoodtoo** [comment]
Just tested this and it looks great! I know this is still a draft, but I have a couple of suggestions. First, consider renaming `dummyPrices` to something like `prices` so users feel like they're building a real app as they're working through your lessons. Second, try to make sure your code has consistent spacing and semicolons:

```js
app.get('/sell/:ticker/:shares', checkTickerAndShares, (req, res) => {
  const ticker = req.params.ticker.toUpperCase();
  const shares = parseInt(req.params.shares);
  const total = shares * dummyPrices[ticker];
  res.send(`Transation complete, you sold ${shares} shares of ${ticker} at $${dummyPrices[ticker]}/share for a total of $${total}.`);
});
```

Once you finish the route to check the value of a stock, you can start breaking down the project into small steps like this: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files

**Comment by lmilliken** [comment]
@scissorsneedfoodtoo , can you clarify what you mean by "breaking down the project into small steps?"  The example seems to show code for a game.  I'm not sure what I need to do since this stock trading platform is just to teach students to create an API.

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, yes, that's exactly right.

Users will code the actual project in freeCodeCamp's (upcoming revised) editor, so the first step can start with a blank file telling users to include Express with `const express = require('express');`, or something like that. I just wrote up some FAQs that might help as your writing out your instructions: https://www.freecodecamp.org/forum/t/freecodecamp-curriculum-7-0-faqs/269346. But feel free to contact me if you have any other questions or there's something I can help with.

**Comment by lmilliken** [comment]
Ok, here's the draft https://github.com/lmilliken/fcc-trading-platform.  Let me know if it's too much/little instructions or if the steps are too small/big.  Will ping you again when finished.

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, looking good so far! Before you get too much further, my only suggestion would be to try and break the steps down a bit more. For example, `server010.js` could be a blank file with the text:

```js
// Normally you would install Express with a package manager like npm or yarn, but we've already taken care of that for you. Import Express into your project by using the `require` keyword. Here is an example of using `require` to import the Path module: `const path = require('path');`. 
```

Then `server020.js` could read:

```js
const express = require('express');

// Initiate Express with the following code: `const app = express();`
```

Anyway, hope that helps. Looking forward to seeing all of your instructions later

**Comment by lmilliken** [comment]
Hey @scissorsneedfoodtoo , this is the full finished draft: https://github.com/lmilliken/fcc-trading-platform

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, awesome! Just skimmed through and everything looks good. Can you open up a pull request to this repository? Then we'll be able to do a more thorough review before merging.

**Comment by lmilliken** [comment]
I'm currently working on the lessons for the the Calorie Counter.

I'll loop back to update the instructions for this Express.js lesson in a couple of weeks.  In the meantime, anyone is welcome to fork and update: https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/express-strock-trading-platform

**Comment by scissorsneedfoodtoo** [comment]
This project is open for anyone to work on. See the to do file for more information: https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/express-strock-trading-platform/TODO.md

**Comment by beaucarnes** [comment]
This project looks good so far. I'll start working on updating / creating the instructions.

**Comment by beaucarnes** [comment]
Just saw in https://github.com/freeCodeCamp/CurriculumExpansion/pull/143
that @lmilliken is working on this again so I'll hold off for now.

**Comment by scissorsneedfoodtoo** [comment]
@lmilliken, were you able to make any progress on a third draft? I left a few suggestions and thoughts in #180.

**Comment by lmilliken** [comment]
Ah, sorry I didn't see it before @scissorsneedfoodtoo , I'll submit the third draft shortly.

**Comment by scissorsneedfoodtoo** [comment]
No need to apologize, just a few minor things I noticed. Looking forward to seeing your next draft :1st_place_medal:
