### ISSUE TITLE
Learn Node.js by Building a Web Server

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#106]

**Comment by padunk** [comment]
Hi, I would love to help with this one. I made a simple server here:
[codesandbox](https://codesandbox.io/s/zxl9yl9o74)
But I don't know if this is good enough.
Thanks.

**Comment by QuincyLarson** [comment]
@padunk Wow - this looks great! Can you start breaking it down into individual test descriptions that walk people through building it step-by-step?

**Comment by padunk** [comment]
Ok, I will do it this week.

**Comment by QuincyLarson** [comment]
@padunk Awesome! Thanks for keeping us posted on your progress.

**Comment by padunk** [comment]
@QuincyLarson Sorry I can't finish it last week. I put it on my Github repo
https://github.com/padunk/fcc-web-server
Is that OK?
Thanks.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, your server looks great! My only suggestion would be to break down each step into even smaller steps, and to show some example code. Check out this PR and you'll see what I mean: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files

In that PR, index100.js gives a short explanation of how to use `document.querySelector()`, along with some example code. After expanding on that for a couple of lessons, the user has to use `document.querySelector()` on their own to select a bunch of other HTML elements.

In your index010.js file, you could start with no code and the following text:

```js
/* In order to create your server, you need the `http` module.
Use `const http = require('http');` to include it in your program.
*/

Then index020.js would start with:

```js
const http = require('http');

/* Commented out instructions */
```

Feel free to change the language, but try to keep instructions as possible.

Hope that helps! Please let me know if there's anything else I can help with.

**Comment by padunk** [comment]
@scissorsneedfoodtoo yup, I already checked that PR.
Let me see how can I break it down into smaller steps.
Thks.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, great! Looking forward to seeing them.

**Comment by padunk** [comment]
@scissorsneedfoodtoo, I break some step into a smaller one. 
Would you mind checking it?
Thanks.

**Comment by Ethan-Arrowood** [comment]
Hi @padunk can you submit your work as a pull request to this repository? If you need help let me know!

**Comment by padunk** [comment]
@Ethan-Arrowood Sure, but I never do pull request before, how to do that?

**Comment by scissorsneedfoodtoo** [comment]
@padunk, I could help you with that. It's similar to the process outlined in this guide: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md

It would probably be easier to hop on a call to walk you through the process. I'll send you an email and we can decide on a time.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, just wanted to check in and see how everything's going with this project. Were you able start breaking your lessons down into smaller ones? I left a review here that might help: https://github.com/freeCodeCamp/CurriculumExpansion/pull/148

**Comment by scissorsneedfoodtoo** [comment]
This project is open for anyone to work on. See the to do file for more information: https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/node-js-web-server

**Comment by beaucarnes** [comment]
I can work on this. I'm not sure the current method of using a switch statement to figure out the files to load is the best / simplest method.

**Comment by scissorsneedfoodtoo** [comment]
@beaucarnes, thank you for taking this on! Yes, we talked about the switch statements online and how there's probably a better way, but it was never revised.

**Comment by padunk** [comment]
Hi All, 

Sorry for the late reply.
I already break it down to smaller steps, but not finished it yet.
I will finish this today.

Thanks.

Sent from Mail for Windows 10

**Comment by scissorsneedfoodtoo** [comment]
@padunk, thank you for reaching out and continuing to work on this! Please hold off for a moment, though. Right now the plan is to change the project so it's more like this example: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework

**Comment by beaucarnes** [comment]
@padunk I already updated your server code to be more similar to the example linked to above. This server will be able to serve any number of files, including css and images. However, it doesn't handle POST requests like yours does. I just thought that could be a good way to simplify things. 

I'd love to hear your thoughts on this. Maybe there are some parts of your implementation that would be good to include.

https://gist.github.com/beaucarnes/f5e7c14a246e32df58c01b7e49a940c1

**Comment by padunk** [comment]
@beaucarnes The server looks good. And I like the idea of serving a different kind of file types, although I think handle POST request is also important, but maybe not at this stage. One thing I don't understand from the code is when it hit `404` why give back status `200`?
```
response.writeHead(200, { 'Content-Type': contentType });
// why not this:
response.writeHead(404, { 'Content-Type': 'text/html' });
```
Other than that I think the code is ok.

**Comment by beaucarnes** [comment]
@padunk Yeah, you are right, that should be `404`. I had taken over the project since we hadn't heard from you for awhile. But you can take it back over if you would like.
Just let me know if you want to keep working on this or if I should do it.

**Comment by padunk** [comment]
@beaucarnes Ok, I will work on this project. Do you have any idea about this project?
I will be happy to hear it. Thanks.

**Comment by beaucarnes** [comment]
@padunk I just made a PR with everything I did when I didn't know you were working on the project. I simplified the HTML files. Plus I added some images and a simple CSS file. You don't have to use what I created. But maybe it will give you some ideas.

**Comment by padunk** [comment]
@beaucarnes Ok. I will take a look at it.

**Comment by scissorsneedfoodtoo** [comment]
Hi @padunk, just wanted to check in and see how everything's going. Were you able to take a look at the new Node server project?

**Comment by padunk** [comment]
@scissorsneedfoodtoo Yup, I need to make some changes, I think I can finish it tomorrow.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, okay, sounds great! Saw you submitted a PR and I'll take a look at it ASAP.
