### ISSUE TITLE
Responsive Web Design Project: Product Landing Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#11]
We are introducing a few new front end projects to give campers more experience working just with HTML and CSS before adding JavaScript to the mix. 

Here are the agile use stories for this challenge:
1. When I arrive at the product landing page, I can click buttons in the navbar that will take me to the corresponding section of the landing page (features, pricing, email sign up)
2. I can watch an embedded product video
3. There is a form field where I can enter an email address.
4. The form uses HTML5 validation to confirm that the entered text is an email address
5. Upon clicking the button, it will post to a static page on FCC that confirms the email address entered (and that it posted successfully)

We are looking for a volunteer who can build a working demo of this on CodePen using only HTML5 and CSS (no libraries).

**Comment by atjonathan** [comment]
I will take this on.

**Comment by QuincyLarson** [comment]
@atjonathan You are juggling quite a few other priorities. Perhaps we could see whether @ChaituVR would be interested in tackling this since he already built https://github.com/FreeCodeCamp/CurriculumExpansion/issues/12 and this is a related challenge.

**Comment by atjonathan** [comment]
@quincylarson I'm nearly finished, should have it done by tomorrow...

**Comment by atjonathan** [comment]
@QuincyLarson What do you think of http://s.codepen.io/atjonathan/debug/wWZxVA?
We need to decide on a company/brand to use across the page, and to replace the placeholder text and images with details about that brand.

**Comment by QuincyLarson** [comment]
@atjonathan this looks solid! I think we should simplify it. No need for full-bleed images and video. Our goal with these projects should be to present something relatively bare-bones and allow them to build something more elaborate.

**Comment by atjonathan** [comment]
@QuincyLarson, how does it look now?

**Comment by SamAI-Software** [comment]
@atjonathan nice :) If you want some more inspiration, then checkout this [breakdown of three cool websites](https://youtu.be/4ZGdcoRsRY0) that use videos on their landing pages. By the way I've also made a few other tutorials on LPs, they might be also interesting for you for this particular challenge.

About your pen - I totally understand the approach to simplify it and I agree with that, however, I would consider adding just a few commonly used elements, which are basic expectations for product LP:
- Header
- Subheader (optional)
- One more dominant call-to-action button at the hero section
- Make a hero section at least 90-100 vh
- Add a small arrow at the bottom of a hero section (resolves issue with "scroll stoppers")
- Add little color change on button's hover (no need for pointer cursor)
- Simple footer.

**Comment by QuincyLarson** [comment]
@atjonathan that's better, but I was thinking something more simple and contemporary. You could get rid of the photo background. Also, I think you should actually add copy here that's thematic. It should be for a product, even if it's a cat photo app or something like that. 

Here's a good example of simple but contemporary: https://www.rinse.com/

**Comment by atjonathan** [comment]
Alright @QuincyLarson @SamAI-Software, let me know what you think now :smiley: 
http://s.codepen.io/atjonathan/debug/wWZxVA

**Comment by QuincyLarson** [comment]
@atjonathan @SamAI-Software Excellent - this is much better! My only suggestions: use pointers on mouse hover and add more vertical space between sections so the scrolling is more obvious when you click the navbar links. Other than that, this is good to go!

**Comment by atjonathan** [comment]
@QuincyLarson Finished :+1: :tada:

**Comment by QuincyLarson** [comment]
@atjonathan awesome! This is good to go. Thank you and @SamAI-Software for your hard work on this!

**Comment by atjonathan** [comment]
Np :)
