### ISSUE TITLE
Learn Data Visualization by Building a Dashboard

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#110]

**Comment by lsurasani** [comment]
@QuincyLarson what kind of data visualization are you thinking? like d3?

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, yes, any sort of D3 project that teaches most or all of the concepts [here](https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3) would be fine. Do you have any ideas about what kind of dashboard you'd like to build?

**Comment by lsurasani** [comment]
Sorry for lack of response, just got back from vacation. 

That sounds good, I'm thinking maybe a dashboard related to world population data by continent?

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, no problem! Hope you had a nice vacation.

There is another project that teaches D3 by building a world map, so I'm worried there will be a bit of overlap between the two. Sorry, I have trouble keeping all of these projects straight sometimes!

Rather than teach D3 here, it would be better to focus on the fundamentals of data visualization by building a simple dashboard. According to [this page](https://www.nngroup.com/articles/dashboards-preattentive/), data dashboards are useful for quickly communicating important information, with the most important information being shown as linear charts or graphs. Apparently things like pie charts and other circular graphs are difficult to read quickly or accurately. And if there are multiple visualizations and you want to draw attention to one in particular, placing it on the top left or right and sizing it appropriately should help. Here is another good resource I found that might be useful: https://dataschool.com/books/how-to-design-a-dashboard

That said, this can be a very simple dashboard, especially since we won't be teaching a library like D3. It could look something like one of the charts on [this](https://www.klipfolio.com/blog/digital-marketing-agency-dashboards) page, and have hard coded bar graphs (without the animations) like this: https://codepen.io/ejsado/pen/rHmDe

World population data by continent sounds good, or even something like the most popular programming languages. Whatever you feel like doing!

**Comment by lsurasani** [comment]
@scissorsneedfoodtoo okay! that makes sense. So to make sure I totally understand, the objectives with this project are:

1. Learn fundamentals of data vis (specifically related to dashboards and when to use which types of graphs)
2. Build a really simple dashboard (without using D3) to illustrate these concepts

So for action items to start on this, I'm guessing I should build the dashboard? And then do we want to test them or something for part 1? like a short quiz of some kind? Or is just giving the information fine?

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, thank you for your patience.

I'm sorry, but I misunderstood the goal of this project. I just got off a call with @QuincyLarson and using D3 is totally fine for this project. What we're thinking is that the D3 World Map project will teach the basics of D3 and this one will be more conceptual, teaching things like how to build a simple dashboard and how to build the four basic charts (pie, vertical bar, horizontal bar and line). This project could use the same (or a similar) data set to build each chart, and show why pie charts are bad for readability, which charts are good for representing different types of data, and so on.

Again, I'm very sorry if you've already started on this! Hopefully you haven't gotten too far if you have.

The first step is to build a prototype on CodePen, CodeSandbox, or any other online platform you prefer. Go ahead and build the whole dashboard and the charts, then post a link here whenever you're finished. After reviewing your prototype, you can start breaking your project down into steps like in the [JavaScript RPG](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/basic-javascript-role-playing-game).

**Comment by lsurasani** [comment]
okay, sounds good!

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, looking forward to seeing your project!

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, just wanted to check in and see how things are going. Were you able to make some progress on your prototype?

**Comment by lsurasani** [comment]
Hey @scissorsneedfoodtoo -- been busy for last two weeks with some stuff at work, so I haven't quite completed it yet, but hopefully tonight or tomorrow. Thanks for checking in!

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, no problem! Looking forward to seeing it.

**Comment by scissorsneedfoodtoo** [comment]
Hi @lsurasani, were you able to finish your prototype? Looking forward to seeing it soon!

**Comment by scissorsneedfoodtoo** [comment]
@lsurasani, how's everything going? Did you get a chance to start on the prototype?

**Comment by moT01** [comment]
I can try and take this one.

**Comment by scissorsneedfoodtoo** [comment]
Okay, sounds great. Thank you for picking this up @moT01.

**Comment by moT01** [comment]
https://codepen.io/moT01/pen/jjRJmY

**Comment by QuincyLarson** [comment]
@moT01 This looks excellent. The code is clean and simple, and I can visualize how we would walk people through setting up the dashboard one element at a time. Could you start breaking this down into a series of tests?

For the data, we could pre-include that so they don't have to type it out themselves but everything else should be coded by them one or two lines at a time.

**Comment by beaucarnes** [comment]
This looks nice! I'm excited to see how this is broken up for the tests.

**Comment by moT01** [comment]
Thanks for the feedback @QuincyLarson & @beaucarnes - quick question... should I break the project up into separate css and js files or should I just put all the code in an html file and use script/style tags like it is on codepen? And if I break it up, how would I direct users to different files and determine the order of lessons? The other project I did was all in the html file so it was easy to chronologize the lessons. Not sure if there will be a way to navigate files or how that would work - might be easiest to just put it all in a html file.

**Comment by scissorsneedfoodtoo** [comment]
@moT01, great question. The new platform will support multiple files, so it would be best to break your lessons up into separate HTML, CSS, and JS files. Every time a learner completes a step, the editor will focus on the area where the new lines of code will go. So if the learner adds a new CSS ruleset, then has to go back to the HTML file, the editor will switch to the HTML file automatically and scroll down to the line where they should write. The Nutrition Label project does a pretty good job showing this: https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/typography-nutrition-label

**Comment by beaucarnes** [comment]
Another method I'm going to try for a different project (that will have at least 10 files) is to put all the instructions in a single text file. For each instruction, I will indicate the file name that the instruction applies to. I will use sequential numbers on the file names for each step, just like in the other projects.

**Comment by moT01** [comment]
I think I have a method that looks like it will work for me - I just named each file a number and gave it whatever extension it needed.
<img width="185" alt="Screen Shot 2019-07-17 at 1 58 12 PM" src="https://user-images.githubusercontent.com/20648924/61403517-1196bf00-a89b-11e9-8f98-1be8925d62ba.png">

**Comment by beaucarnes** [comment]
Seems like a good method to me.

**Comment by scissorsneedfoodtoo** [comment]
@moT01 and @beaucarnes, both seem like great methods given the projects. Having all the instructions in one place for the Redux project will make it much easier to review.
