### ISSUE TITLE
Learn CSV by Building a Mailing List

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#114]

**Comment by lionel-rowe** [comment]
I'd be interested in contributing to this challenge.

I'm assuming the best approach for this one would be pulling in a library, rather than generating/parsing CSV files from scratch? Doing it from scratch could be valuable for teaching a few CS concepts, but isn't a very practical approach for how a developer would usually approach this problem, nor is it particularly related to data viz.

**Comment by QuincyLarson** [comment]
@lionel-rowe @RandellDawson has an idea for a CSV project that would involve quotations, commas within values, and other considerations so let's see what he comes up with first.

**Comment by QuincyLarson** [comment]
@lionel-rowe I just messaged with @RandellDawson and he is focusing on the Learn Functional Programming by Building a Spreadsheet project instead of this one. If you're still interested in building this one, we would welcome your help.

**Comment by Ramon92** [comment]
@QuincyLarson I would like to take this on and build a prototype.
My take on this is to make it possible to select an csv file with first names, surnames and emails.
Being able to parse several csv formats and outputting it in JS as an array. Or to output is as an array of objects in which each object has as keys the header of the csv file. 
The result will be displayed on the page in a table format.

Love to hear your idea about this

**Comment by scissorsneedfoodtoo** [comment]
@Ramon92, thanks for your patience. I believe this project is more about creating the actual CSV file itself while teaching the fundamentals like the general format, how there should be no unnecessary spaces at the beginning or end of an entry, how to include commas in a value by wrapping the whole thing in double quotation marks, and so on. The list could include properties like first and last name, email address, and a note with some extra details (and commas) about each person.

Perhaps it could then branch off and teach how to parse and manipulate the data with JavaScript, but that might be outside the scope of this project. What do you think @QuincyLarson?

**Comment by scissorsneedfoodtoo** [comment]
Hi @Ramon92, were you still interested in working on this project? If so, what do you think of the possible topics I mentioned in my last comment?

**Comment by Ramon92** [comment]
Hi @scissorsneedfoodtoo completely missed your message, sorry for the way too long delayed reply.
I have some time this month, I am still interested. 

Okay so if I understand correctly, the goal here is to just create a csv file with JS right.
For example based on some input you can export a csv to be downloaded?
And display the data in a simple table, before exporting it to a csv.

**Comment by scissorsneedfoodtoo** [comment]
Hi @Ramon92, no need to apologize. Thank you for your help with this project.

There's a lot of ways we could tackle this project. I was thinking something more along the lines of learners creating their own CSV mailing list, perhaps with the names, mailing and email addresses, phone numbers, and some notes about popular animated characters. Ones like Lisa Simpson, Morty Smith, and so on.

After teaching the fundamentals of CSV and some special considerations (no spaces at the beginning or end of an entry, how to include commas) by entering the values for a few characters, then we could go more into how to parse, manipulate, and perhaps add to the data using JS. That said, I don't think we need a UI or any sort of input to add to the CSV here. This can be entirely editor and console based.

But really these are just suggestions. Please feel free to let us know what and how you'd like to teach and we can discuss it more. The only real requirement is to teach CSV fundamentals, and we will probably do that by having learners write some of that by hand, line by line, at least for a few rows. There's a lot we can do with the data after that.

**Comment by Ramon92** [comment]
Hi @scissorsneedfoodtoo 
Sounds good, I can built the project the coming week and make a PR to be reviewed. What do you think?

**Comment by scissorsneedfoodtoo** [comment]
@Ramon92, awesome, sounds good. Please build a prototype on something ike [CodeSandbox](https://codesandbox.io/) before submitting a PR. Then we can take a look at the finished project and discuss it more before we start breaking it down into steps.

Also, please send me an email at kris@freeecodecamp.org if you have some time to talk about this project next week. I can answer any questions you might have before you really start digging into it.

**Comment by Ramon92** [comment]
I made a start of an example of a csv file and one way to parse it.
https://codesandbox.io/s/learn-csv-by-building-a-mailing-list-z52ue
I can setup multiple csv formats.

What would the end project look like?
As I was thinking of adding in here the steps to teach someone how to setup a csv, by explaining the concept in multiple steps.

I understood that the Final project is built first and then it is split in multiple pieces.
I tried emailing, but the email address seem invalid.

[![Edit learn csv by building a mailing list](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/learn-csv-by-building-a-mailing-list-z52ue?fontsize=14&hidenavigation=1&theme=dark)

**Comment by scissorsneedfoodtoo** [comment]
Hi @Ramon92, sorry about that. There was a typo in the email address in my last comment. It should be kris@freecodecamp.org with two e's, not three.

This looks like it's off to a good start. The inclusion of notes is nice so we can get an idea of what you'll teach and how things will be broken down.

Yes, that's right. We want to have very short steps that have learners do one thing at a time. So they might start by just writing "Name," in the first step, then "Email," and finally "Mailing address, Favorite animated character".

Having the CSV values in the JS file is fine for now. Eventually I believe we'll have everything in a separate CSV file and import it using `fs`, or some mocked version of that to work on the front end. Also, having learners write a simple CSV parser is a great idea.

The final project can really be anything. I know I mentioned that this could be all done with JavaScript and the console earlier, but what we might consider doing is having a function to append the parsed CSV values to an HTML table or grid. Then we might also consider having a function to get values from an existing HTML table and create a CSV file or string from the values there.

I will ask @QuincyLarson and @beaucarnes to take a quick look and give some early feedback about the direction for this project.

**Comment by QuincyLarson** [comment]
@Ramon92 Thanks for creating this and sharing this with us. You're off to a great start.

Rather than Jessica Alba and Tony Robbins perhaps we could use more well-known and widely-liked figures Keanu Reeves or Malala.

Like @scissorsneedfoodtoo I am very interested in seeing the end version of this project. Keep in mind that campers will need to type all this in themselves when they're creating it, so we should keep the CSV text to a minimum.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, thank you for your input. I agree that we can update the examples to use more current and liked figures as you suggested.

**Comment by beaucarnes** [comment]
@Ramon92 I agree with Quincy that this is a great start! 

I wonder if a different format for the project could work better to teach csv? Currently, the code seems to focus on the JavaScript and creating the CSV with JavaScript. Here is what @scissorsneedfoodtoo said back in July, which I agree with: " [the] project is more about creating the actual CSV file itself... Perhaps it could then branch off and teach how to parse and manipulate the data with JavaScript."

In my opinion, the project should work like this:

- First, the student should be guided through creating a simple CSV by typing it into a text file (with no JavaScript). This part would cover various formatting rules and would be the main part of this project.
- Next, the student would be guided through using JavaScript to parse and display the content.(with a library - no need to write a parser since the focus is on the csv format) 
- Finally, the student would use JavaScript to add to the CSV file (again, with a library).

**Comment by Ramon92** [comment]
@QuincyLarson Valid point for the final project to have more well-known figures.
@beaucarnes You are right, it now seems to focus indeed a bit too much on JS and how to parse CSV with JS. I will update the project with your Feedback, I will keep you posted.

**Comment by darren-stoll** [comment]
I was looking to help with this since it was marked with "Help Wanted", but it looks like @Ramon92 was working on updating the prototype? 

With regards to typing CSV into a text file, could that be done with instruction on codepen.io? I feel like that instruction is already given in the latest sandbox that I see [here](https://codesandbox.io/s/learn-csv-by-building-a-mailing-list-z52ue). I'd love to be able to help further with this, but I also don't want to step on any toes if a lot of the work has already been done.

Also, the doc says to mention @scissorsneedfoodtoo if I want to help, so I'm doing that. Looking forward to starting on this project.

**Comment by darren-stoll** [comment]
Haven't heard anything, but I got impatient and started on a thing [here](https://codesandbox.io/s/learn-csv-by-building-a-mailing-list-template-i18yd?file=/README.md).

I took a lot of ideas from Ramon92's code and added them to my implementation, but I also added a more descriptive readme file to help guide the student as to what needs to be done. I tried to stick with basic JavaScript where I could, but I ran into a problem with the 3rd step of having the student using JavaScript to add to the CSV file.

> * Finally, the student would use JavaScript to add to the CSV file (again, with a library).

Unless I use a server-side implementation like Node.js, I cannot actually add to the CSV file. Should I rewrite the code for all three steps in Node.js? If so, will that complicate things for the student to use more than basic JavaScript? I know that the end goal is to teach CSV, but I do want to keep the objectives in mind.

**Comment by scissorsneedfoodtoo** [comment]
Hi @darren-stoll, thanks for your patience and your improvements on the current prototype. I really like the direction you're heading.

We've paused development on this and other projects in the upcoming [Data Visualization](https://www.freecodecamp.org/news/python-curriculum/#-javascript-data-visualization-11-projects-), at least for the time being. The current plan is to move some of these practice projects into other sections. I'd like to keep this project in if possible, though I'm not sure exactly what section it will end up in.

I can better answer your questions once I know which section this project will be in. Right now it's hard to say if everything will need to be done client-side, or if we'll be able to use a server/Node.js.
