### ISSUE TITLE
Learn Functional Programming by Building a Spreadsheet

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#118]

**Comment by codingk8** [comment]
OK to contribute to this one.

**Comment by QuincyLarson** [comment]
@codingk8 OK - cool. See if you can build a very basic spreadsheet in JavaScript on a site like CodePen and we can go from there. This is going to be a particularly exciting project.

**Comment by codingk8** [comment]
I'm currently busy with a CSS project. Feel free to come and move on with this one in the meantime.

**Comment by QuincyLarson** [comment]
@codingk8 OK - thanks for confirming. This one project is open for contributors.

**Comment by RandellDawson** [comment]
@QuincyLarson I will take this one instead of the CVS one if that is ok.

**Comment by QuincyLarson** [comment]
@RandellDawson Sure thing - I've assigned it to you. Best of luck!

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, just checking in to see how things are going with your prototype. Do you have anything you can show us? If so, we could give some early feedback.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo I have been busy with my job search, so I have not spent as much time on it as I had hoped.  If you want someone else to take on this project who can spend, I am fine with that.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, no problem! Thank you for letting us know. I'll put the help wanted label back on for now, but please feel free to pick it up again later if it's still unclaimed and you have some time. Good luck with your job search!

**Comment by UsamaHameed** [comment]
Hello, I am back from vacation and can see that the typescript project is in good hands. I think I can take on this one instead. What kind of project do you want here? How versatile should it be? Can we limit it to some simple operations?

**Comment by scissorsneedfoodtoo** [comment]
@UsamaHameed, sure, the project is all yours! As @QuincyLarson mentioned above, a very simple spreadsheet on a platform like CodePen is totally fine. My thinking is that the spreadsheet doesn't have to be too versatile, and limiting it to a few simple operations is fine. The main goal here is to teach functional programming, so we're good as long as we can do that.

**Comment by scissorsneedfoodtoo** [comment]
@UsamaHameed, just wanted to check in and see how everything's going with this project. Were you able to make some progress on a prototype?

**Comment by sw-yx** [comment]
as someone who's tried doing this.. we may need to limit the scope a bit. spreadsheets are very hard to make right.

**Comment by UsamaHameed** [comment]
@scissorsneedfoodtoo I worked on it a bit but nothing to see right now. Just caught up in my job (thanks to fcc btw) and daily routine. @sw-yx I will definitely only work on a minimal working project first.

**Comment by scissorsneedfoodtoo** [comment]
@sw-yx, yes, that might be something to consider. Really these projects are all just suggestions, and can be changed if a better idea comes along. Anything that teaches functional programming would be fine!

@UsamaHameed, no worries. Glad you got caught up at work! Please let us know when you have a simple spreadsheet, or if you have another idea for a project.

**Comment by scissorsneedfoodtoo** [comment]
@UsamaHameed, hows everything going? Were you able to make any progress on a prototype?

**Comment by JiwoonKim** [comment]
Hi! I'd love to contribute to creating this project!

Just looked into the Functional Programming section for the Javascript Algorithms And Data Structures Certification, and noticed a lot of it revolves around basic array methods.
I was wondering what you had in mind in using array methods (filter, splice, slice, concat, etc.) for the spreadsheet. Should it just provide specifications for the array formulas like in Excel (i.e. MAX function) or also include functions for numbers, texts, and others?

**Comment by scissorsneedfoodtoo** [comment]
@JiwoonKim, awesome! It would be great if you could pick up this project.

You're right, the current Functional Programming sections does include a lot of basic array methods. Many of these concepts will be covered in other projects like the Algorithmic News Feed, Shopping Cart, and Calorie Counter which all come before your project. This could be more of a review / brief overview of the filter, splice, slice, map, and whatever other methods make sense within the scope of this project. More importantly, this project could teach concepts like pure functions, higher-order functions, avoiding mutability, and so on.

Your idea of reproducing formulas for numbers and text like in Excel is just what I was thinking. You could keep it simple and cover some of the things mentioned above while recreating Exel's MAX, SUM, AVERAGE, MEDIAN, TRIM, CONCATENATE, and whatever else you think is appropriate.

**Comment by JiwoonKim** [comment]
@scissorsneedfoodtoo Thanks for the explanation! I'd like to take this project if it's okay. I'll try to come up with a prototype and share it as soon as possible!

**Comment by scissorsneedfoodtoo** [comment]
Sounds great @JiwoonKim. Looking forward to seeing what you come up with. Please check out the [Contributor's Guide](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/CONTRIBUTING.md) for some frequently asked questions, and don't hesitate to reach out if there's anything we can help with.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo can I work on this?

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, sure, this project is all yours. The first step is to build a prototype on a platform like CodePen or CodeSandbox. Feel free to check out the [Contributor's Guide](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/CONTRIBUTING.md) for general information and FAQs, and please don't hesitate to reach out if you have any questions. 

Looking forward to seeing what you come up with.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo I've finished the prototype:
https://codepen.io/someder/pen/VoxwxX

**Comment by RandellDawson** [comment]
@SomeDer I looked over your current code and had a couple of observations:

1. Noticed you intermix ES6 arrow function syntax with traditional function declaration syntax.  Is there a reason you are not using arrow function and const/let throughout?

2. How do use the spreadsheet functions?  I expected to be able to enter something like:
`=sum(A1,B1)` or `=sum(A1:B1)` or =A1+B1
in say cell C1 and it display the sum.  Instead it displays the individual values but not the sum.  For example, If I put 3 in A1 and 4 in B1, and one of the above formulas in C1, I get `3+4` instead of `7`.

**Comment by SomeDer** [comment]
@RandellDawson thank you for the review. I've edited the code:
* It now uses arrow functions throughout
* The function names are no longer case sensitive
* Infix operators (`+`,`-`,`*`,`/`) are now supported
* The `A1:B1` syntax is now supported

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, amazing! Looks just like the Google Sheets spreadsheet I had open in another tab. And thank you for your observations and suggestions, @RandellDawson. The only other thing I noticed is that, while both `=sum(A1:A2)`, `=A1+A2`, and `A1+A2` all work, if I use either of the first two the `=` sign is left in the cell.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo OK. 
* The cell names can now use both upper and lowercase letters (so both `A1` and `a1` work). 
* When the user want  the expression to be expanded, it must now start with an `=` sign, and the sign is now removed. This means the third example no longer works, but that's the behavior of Google Sheets.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, awesome, thank you for continuing to work on this prototype. Really incredible what you've been able to do here.

Now that I've taken a better look at the code, my only suggestion would be to try and simplify things as much as possible. Taking a look at Quincy's [forum post](https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) about the new curriculum, your project will still be quite early in the curriculum.  Some of the longer lines of code might be difficult for learners to fully understand and for use to teach through 3-5 sentence text prompts. Would it be possible to break some of those lines up a bit?

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo I've broken down two blocks of code:
```js
// before
const varRangeExpanded = x.replace(
    /([A-J])([1-9][0-9]?):([A-J])([1-9][0-9]?)/gi,
    (match, c1, n1, c2, n2) =>
      range(parseInt(n1), parseInt(n2)).map(n =>
        charRange(c1, c2).map(c => document.getElementById(c + n).value)
      )
  );
```
```js
// after
 const rangeRegex = /([A-J])([1-9][0-9]?):([A-J])([1-9][0-9]?)/gi;
 const rangeFromString = (n1, n2) => range(parseInt(n1), parseInt(n2));
 const elemValue = n => c => document.getElementById(c + n).value;
// I've also added currying here.
 const addChars = c1 => c2 => n => charRange(c1, c2).map(elemValue(n));
 const varRangeExpanded = x.replace(rangeRegex, (_, c1, n1, c2, n2) =>
    rangeFromString(n1, n2).map(addChars(c1)(c2))
 );
```
```js
// before
str2.replace(
    regex,
    (match, fn, args) =>
      fn.toLowerCase() in spreadsheetFunctions
        ? spreadsheetFunctions[fn.toLowerCase()](
            args.split(/, ?/).map(parseFloat)
          )
        : match
  );
```
```js
// after
const toNumberList = args => args.split(/, ?/).map(parseFloat);
const applyFunction = (fn, args) =>
    spreadsheetFunctions[fn.toLowerCase()](toNumberList(args));
 const str3 = str2.replace(
    regex,
    (match, fn, args) =>
      fn.toLowerCase() in spreadsheetFunctions ? applyFunction(fn, args) : match
  );
```
Are there any other lines that need breaking down? Perhaps the `window.onload` function, but I think that's fairly simple, because it's mostly imperative code.

Also, can a single line can be broken down into multiple lessons? For example:
```js
const charRange = (start, end) => start;
const charRange = (start, end) => range(start.charCodeAt(0), end.charCodeAt(0));
const charRange = (start, end) => range(start.charCodeAt(0), end.charCodeAt(0)).map(x => String.fromCharCode(x));
```

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thanks for your patience and for taking the time to simplify those sections. My concern is that the the longer lines using `replace` will still be a bit too advanced for students at this stage of the curriculum, but perhaps that can't be avoided easily with all of the features of the spreadsheet. 

For the single `charRange` lines, yes, that's exactly how we could break them down, though with maybe one more lesson before the last one that explains how `String.fromCharCode` works. The starting code for that lesson could be: `const charRange = (start, end) => range(start.charCodeAt(0), end.charCodeAt(0)).map(x => x);`

I'll ping @beaucarnes and @QuincyLarson to see if they have some thoughts of suggestions about this prototype before we start breaking it down.

**Comment by QuincyLarson** [comment]
@SomeDer I am really impressed with this project so far. It works great, and looks great, too. It's quite amazing considering how few lines of code you've written here.

I encourage you to start writing the series of tests that will help learners build this project up, one line at a time. These should be only one or two sentences long. You don't need to actually code the tests - just write the text of the tests. It will probably take 100 or 200 tests to walk them through the entire process.

This process will give you some further ideas for how you can simplify the code to better communicate these concepts to learners.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, please take a look at the [FAQs](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/CONTRIBUTING.md) and [D3 Dashboard](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/d3-dashboard) to get a better idea of how we'd like to break these projects down into short lessons.

Also, send me a message at kris@freecodecamp.org if you have some time to hop on a call. We can talk about your project in more detail and I can answer any questions you might have.

**Comment by beaucarnes** [comment]
@SomeDer This looks great! I would recommend that the project starts with the HTML and CSS already created and the tests / instructions only focus on the JavaScript. You can consider hard coding some instructions in the HTML about how to perform the calculations in the spreadsheet.

Like Quincy, I'm impressed by how much functionality you squeezed into so few lines of code. You may also consider looking for any features that can be removed to make the project simpler. However, it may not be possible to remove features without removing key parts of instruction.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, we're starting the process of porting some of these projects over to the current platform for people to beta test. Would you be interested in helping us write the unit tests for each step in your project?

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo, yes I'm interested in helping. What's the syntax for adding the tests?

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, awesome! Thank you for continuing to help with this project.

Each test is just a Node `assert` statement. The tricky part is writing just one test per step that's flexible enough for different possible answers. I've been using a combination of regex and calling functions before `assert` to write the tests for the RPG game. Here's my branch so far for your reference: https://github.com/freeCodeCamp/freeCodeCamp/compare/master...scissorsneedfoodtoo:feat/js-rpg-game-tests

There are some things I need to go back and change, though, like naming each step "Part _" rather than "Number _". Also, the `challengeType` for all of my lessons should be 0 since there's HTML and CSS. Unfortunately there's no support for multiple files yet, so everything that shows up in the learner's editor needs to be between script tags, with the rest of the code hidden away in the "Before Test" and "After Test" sections.

**Comment by SomeDer** [comment]
@scissorsneedfoodtoo I've noticed that you've replaced code tags with backticks, but the backticks don't seem to be working.

**Comment by scissorsneedfoodtoo** [comment]
@SomeDer, thank you for your patience and for moving your PR over to the main repo.

The trick with the backticks is that there needs to be a space between the opening `<section>` tag and the first paragraph featuring backticks. In `step-002.md`, the following will render code as intended:

```html
<section id='description'>

Now define an empty function `add` using the `function` keyword.
It should accept two parameters, `x` and `y`.

</section>
```
