### ISSUE TITLE
Learn Basic Algorithms by Building an Algorithmic News Feed

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#119]

**Comment by lavanganji** [comment]
Hi @QuincyLarson  how can i help in this issue.

**Comment by picolloo** [comment]
I would like to help with this too

**Comment by QuincyLarson** [comment]
@lavanganji @picolloo Both of you have claimed other projects, and I recommend building those first. This one is going to be a real challenge and one or both of you can tackle it a bit later 😄

**Comment by picolloo** [comment]
So I'll choose another one to start

**Comment by lavanganji** [comment]
I will start on this one . @picolloo  you can start on the Shopping Cart

**Comment by scissorsneedfoodtoo** [comment]
Hi @lavanganji, just wanted to check in and see how everything's going with this project. Please post a link to CodePen here when you're finished, and feel free to reach out if you have any questions.

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  trying to build the pen but not sure where to begin with, any starting suggestion would be very helpful and great.

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, I imagine this project will go over concepts that are covered in [Basic Data Structures](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures) (using JS objects to store key-value pairs, checking properties of an object, and working with arrays), and fall somewhere between the challenges in the [Basic](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/) and [Intermediate](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting) Algorithm Scripting sections in terms of difficulty.

Building a full search engine is probably too difficult for students at this point of the curriculum, so a more accurate title for this project might be "Learn Algorithms by Building a Search Filter". [Here's](https://www.youtube.com/watch?v=3NG8zy0ywIk) a video I found of a book search filter project. You should think of some other data set to use, though, like usernames, email addresses, and phone numbers that can all be searched/filtered.

What do you think, @QuincyLarson? Is that what you had in mind for this project?

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  out of curiosity i am asking this, is okay i use JAVA as language in JS , this is just a personal preference.

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, sorry, but we're mainly focused on teaching people web development with HTML, CSS, and JavaScript rather than Java. Are you able to build the project using JavaScript?

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo I am able to build the project using JS. Will update the project soon

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, sounds good! Just let me know if there's anything I can help with.

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  , please review the first draft of code pen , please ignore the coloring and cosmetics
https://codepen.io/lganji/pen/xeboyO
Idea is to developer the car page application , where user can add cars to list, search the best cars by model and brands and also we have main search engine like search box in body of the page. 
All this needs to implemented. this is just a sample design.

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, this looks great! I really like the idea of a car page app to teach these concepts. It's definitely a realistic project and a lot of students will probably work on something like this once they're hired. Can't wait to see the finished project :+1: :+1:

**Comment by QuincyLarson** [comment]
@lavanganji I proposed this based off of Udacity's old Search Engine Python course, and I think we could have taught a lot of concepts by helping people build a search engine. This said, it would be much simpler if we built something without any UI, that was just outputting results from a hard-coded dataset.

So instead of doing a search engine and trying to build the crawler and indexes and everything, I think we could teach a lot of algorithmic concepts by building an algorithmic news feed.

I've updated the title of this issue, and I've asked @scissorsneedfoodtoo to go ahead and see if he can bang out a quick prototype which we can then refine.

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  I am just thinking what will be prototype so that i can work in that direction

**Comment by QuincyLarson** [comment]
@lavanganji I just have a foggy idea of what this might look like in my mind. I encourage you to experiment and share your prototypes as you progress. 

I am optimistic that as you build it and contemplate the design decisions, the project will come together. I'm looking forward to seeing what you come up with 👍

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, sorry for the late response. I've started working on this, but haven't gotten a whole lot done. Mostly just research about how we could do this and starting to work on the JSON structure for the actual articles.

Feel free to pick this up again! I'm always available here on GitHub or to hop on a call if you'd like to talk more about this project.

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  @QuincyLarson  My idea is to basic search filter and implement algorithms one by one like binary search , linear search etc.. 
Here is the sample pen https://codepen.io/lganji/pen/rbQLBm. where i used the just the index to search. given address . please share your thoughts

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, teaching different algorithms is definitely a good idea, though I think binary search might be too difficult for students at this point.

If you take a look at the [Learn Algorithms and Data Structures](https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) section in the post about the new curriculum, your project will fall after basic and intermediate JS, regular expressions, debugging, and data structures. So students will be somewhat comfortable with arrays, objects, and methods like `.map()`, `.filter()`, and shouldn't have a problem with a simple algorithm like linear search. I believe this project should cover some of the concepts in the [Basic](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/) and [Intermediate](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting) Algorithm Scripting sections, and prepare students to tackle the [Algorithm and Data Structures Projects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/).

I'm not sure if you saw, but the spec for this project has changed from building a search engine to an algorithmic news feed. Of course you can take this in a different direction if you want, but here's what I started working on last week: https://codepen.io/scissorsneedfoodtoo/pen/pBqOvw?editors=0012

I started building this JSON object to look like it's the ~20 most recent articles being returned from an API. I was thinking of starting small, with just one article object with some errors, like a headline with improper title casing. After awhile it would ramp up to things like calculating the score for each article (upvotes - downvotes), and ordering them by published date. Eventually it would introduce the concept of users with certain preferences like which sections they're subscribed to, likes/dislikes, if they want to sort by newer articles or more popular ones, and so on. Using those preferences, the student would write different functions to sort the articles and return them, no need for a UI.

Anyway, those were just some general thoughts that I had. Just let us know what you think and if there's anything we can help with. I'm also available to hop on a call about this if you'd like to talk about it in more detail.

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, how's everything going? Hope our discussion last week helped. Were you able to make any progress on this prototype? Is there something we can help with?

**Comment by lavanganji** [comment]
Hi @scissorsneedfoodtoo <https://github.com/scissorsneedfoodtoo> i am
working on it , i will post an update soon this week.

**Comment by scissorsneedfoodtoo** [comment]
@lavanganji, that's great! Looking forward to hearing more about your project :+1: :+1:

**Comment by lavanganji** [comment]
hi @scissorsneedfoodtoo https://codepen.io/lganji/pen/gJwEKL?editors=0010
I am just thinking that writing the function like convertToF() is our basic idea right , i mean we write the functions like getArticles() getHeadlines() getAuthors() getUpvotes() so on .. 
correct me if i am wrong.

**Comment by scissorsneedfoodtoo** [comment]
Hey @lavanganji, sorry, I'm not sure I understand. Are you asking if the function `convertToF()` looks good in terms of formatting? If so, yes, it looks fine, though it would be better to declare variables with `let` and `const` rather than `var`.

All the other functions that you mentioned sound good in terms of teaching the basics, though I worry that it might get a bit repetitive since the method for `getArticles`, `getHeadlines`, `getAuthors`, and `getUpvotes` will all be very similar. Something you could do is teach students how to write a couple of those helper functions, maybe `getArticles` and `getUpvotes`, then refactor it into a more general function where you pass in the thing you're looking for as a parameter (`getAll('upvotes')`).

Ideally by the end of the project this algorithmic news feed will do things like filter articles by category or tag, and sort them by most upvotes/downvotes/comments/most recent, and to take a simple user object and show articles that they are subscribed to.

What do you think? Are there any other features you'd like to see and teach with this project?

**Comment by lavanganji** [comment]
@scissorsneedfoodtoo  SOUNDS GOOD LET ME WORK ON IT.

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo Algorithms - this project looks interesting to me ;) After breaking down the Cryptography project, I'll look to this one closely. 

@lavanganji Can you share your progress so that I can see the direction in which this is going?

**Comment by lavanganji** [comment]
@vkWeb  this is my latest work https://codepen.io/lganji/pen/gJwEKL?editors=0010.   i thought i writing this methods, getArticles() getHeadlines() getAuthors() getUpvotes()  .. got really busy on something else. please let me know if you need anything else.

**Comment by vkWeb** [comment]
@lavanganji Thanks for sharing your progress. Since you are busy, I would like to take this project further. May I?

**Comment by lavanganji** [comment]
@vkWeb  sure and thanks

**Comment by vkWeb** [comment]
@lavanganji Thanks ;) 

@scissorsneedfoodtoo I'll look into this soon.

**Comment by QuincyLarson** [comment]
@vkWeb Just a quick thank you for all your work on these projects. You are coming up with some really ingenious approaches.

**Comment by vkWeb** [comment]
@QuincyLarson This means a lot to me. Thank you so much for the appreciation :)
As soon as I'm done with writing test descriptions of cryptography project, I'll start working on this one ;)

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo By reading your previous comments and looking into the forum post, I think you are expecting this project to use concepts of Data structures and replace `Basic and Intermediate Algorithm Scripting` of the current curriculum to prepare students for the final projects. 
I hope my understanding is correct?

**Comment by scissorsneedfoodtoo** [comment]
@vkWeb, yes, that's right. This project will replace the challenges in the Basic and Intermediate Algorithm Scripting sections, and should cover as many of those concepts as possible in preparation for the required JavaScript Algorithms and Data Structures Projects.

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo Okay. I'll go through the challenges first.

See, what's on my mind right now is that we won't build a full project here. We'll solve problems related to a project that can cover a huge amount of challenging situations. This section needs to be challenging. Extremely challenging. Campers love this challenging part of freeCodeCamp. So, we shouldn't disappoint them, right? ;)

**Comment by scissorsneedfoodtoo** [comment]
@vkWeb, we should be creating full projects here, though this doesn't require a full UI similar to the RSA digital signature project. Just a console based application is fine here, too. Also it should be challenging, but not so much that learners will get discouraged. Try to keep the difficulty level about the same as the current beginner and intermediate challenges while covering concepts that make sense for this project. I realize that this is a fine line to walk, though I'm confident that you'll be able to do it :+1: :+1:

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo I'm extremely sorry for the delay. Actually, after finishing the RSA project, I got busy with some college work.
 
Okay, I'll keep your points in mind. Btw, I'll first solve all the algorithm problems myself so this project may take some time but trust me, you will not be disappointed with the final project.

**Comment by scissorsneedfoodtoo** [comment]
@vkWeb, no need to apologize! Thank you for all of your hard work on the RSA project, and for taking on this one. Looking forward to seeing what you do with this news feed.

**Comment by scissorsneedfoodtoo** [comment]
Hi @vkWeb, were you able to start working on this news feed project?

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo Yes, I am solving different algorithm problems and I am also learning more about JS. I have solved the data structures and basic algorithm section of the current curriculum and I have realized something. 

I think news feed won't be the best approach here. IMHO, the current challenge-based approach seems perfect for the algorithms section. There are certain intermediate challenges which are really excellent but if we go with the project-based approach I don't think we'll be able to include them or similar problems. Also, the challenge-based approach is flexible and gives a sense of "Yes, we are solving problems!" but with the project-based one, we'll restrict ourselves. For e.g. [DNA pairing](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/dna-pairing), [Odd fibonacci sum](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-odd-fibonacci-numbers) are some examples of good challenges but with the project-based approach, we won't be able to include these concepts in a challenge.

I hope you got my point. Please think on this one closely :)

I'm mentioning @QuincyLarson for his thoughts.

**Comment by scissorsneedfoodtoo** [comment]
@vkWeb, it's true that we won't be able to cover every concept or problem in the current curriculum with these projects, but that's one of the reasons we're moving in this direction. In my opinion, coding challenges like the ones in the Intermediate Algorithm Scripting section are great at exercising already existing programming knowledge. However, they're not great for teaching someone how to program, and don't always reflect real world problems or skills. 

While both the DNA pairing and Odd fibonacci sum challenges are fun challenges, they're not things you would do in a typical project. The DNA pairing challenge is more about taking an input and figuring out relationships. In the context of a news feed, I could see doing something like looking at a section or tags an article was published with and suggesting similar articles. Or rather than the Spinal Tap Case challenge, taking an article's title and producing a slug.

So while we won't be including every concept in the current curriculum, learners won't be doing challenges just for the sake of doing them. Instead, they'll be building actual things, and solving real problems along the way.

**Comment by QuincyLarson** [comment]
@vkWeb I agree. We can have a basic algorithms project, an intermediate, an advanced - all different projects. And I'm not married to the notion of an algorithmic news feed project. Train schedules and other algorithmic projects would be great. The main thing is we give learners lots of practice building distinct, substantial projects that will involve them applying algorithm concepts.

**Comment by vkWeb** [comment]
@QuincyLarson Yes exactly, that's what I was thinking last night! We can have multiple small projects. It will cover different challenges in terms of difficulty and taste. 

Btw I had a talk with @scissorsneedfoodtoo via email and we decided to write a forum post to know camper's views and to take their suggestion on this approach. I will ask them if they know some good projects which can cover a broad range of algorithmic problems. This portion is very important. We need to deliver it the right way :)

**Comment by scissorsneedfoodtoo** [comment]
@vkWeb, that sounds good. We could split the projects up like we're doing with the basic CSS blog and intermediate Picasso painting projects now. The train ticket booking application you proposed would make for a good intermediate algorithms project.

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo I have created a forum post: https://www.freecodecamp.org/forum/t/tell-us-your-ideas-for-the-upcoming-algorithms-section/315113. 

Let's see how things turn out.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for posting that to the forum.

**Comment by scissorsneedfoodtoo** [comment]
As per [this](https://www.freecodecamp.org/forum/t/tell-us-your-ideas-for-the-upcoming-project-based-algorithms-section/315113) post on the forum, we will split this section up into separate projects.

**Comment by vkWeb** [comment]
@scissorsneedfoodtoo The apps/games we will be building are not finalized. I am still looking for different possibilities, here's my reddit post to ask the internet about project ideas: https://www.reddit.com/r/learnprogramming/comments/d8rjas/please_tell_us_your_ideas_for_the_upcoming/

I won't hold this for too long. I'll look for replies on the post only for 2 - 3 days and then we'll start working on the apps/games. I will tell you the finalized game/app list on this thread. Keep this and the Yahtzee game issue opened, just to see if someone is interested in helping us. 

If we don't get a reply from community soon I'll build these projects. ;)

**Comment by NA-E** [comment]
Hi @vkWeb. Do we now have any finalized game/app list? From the discussion above it appears that this section is going to get split into separate projects. I would love to contribute prototyping a project and progress forward with further developments.

**Comment by scissorsneedfoodtoo** [comment]
@NA-E, please feel free to work on a prototype for this project or pitch a totally new one as @vkWeb mentioned. 

The main thing we want to do with this project is to cover most, if not all, of the concepts used in the [Basic Algorithm Scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/) section of the current curriculum.

**Comment by NA-E** [comment]
@vkWeb @scissorsneedfoodtoo Okay. Allow me some time to do some brainstorming on my own. I'll give you guys an update in one week.

**Comment by scissorsneedfoodtoo** [comment]
@NA-E, awesome. Please let us know what you're thinking and we can discuss it here.

**Comment by vkWeb** [comment]
Hey @NA-E. Did you get an idea for this lesson?

**Comment by scissorsneedfoodtoo** [comment]
Hi @NA-E, any updates on the concepts you'd like to teach? Also, feel free to work on a prototype and post it here for early feedback. That might help us get a better idea of what to teach and how to teach it.

**Comment by 01Clarian** [comment]
@scissorsneedfoodtoo 
Hey there! I'd like to do this one if that's OK?

I sketched out the basics in sand box below.
1. We can look at simple algorithm through databases for sign in and authentication. 
2. We can map out the newsfeed if the authenticated.   
3. We can create databases and do some basic clean function structures and look at logic and returning loops correctly.
In sandbox sketched out quickly to prompts but in the project we can have a sign in button and display the data in html.

Let me know thoughts. Thanks

(readme: when you click the link it automatically goes to prompt username and password -
default username: zelda, password: ocarina)
https://codesandbox.io/s/elegant-mendeleev-8mu9l?fontsize=14&hidenavigation=1&theme=dark

**Comment by scissorsneedfoodtoo** [comment]
Hi @01Clarian, thanks for your patience and for working on a prototype.

Looking at your code I think you're definitely headed in the right direction in terms of difficulty and the types of things we would want to teach here (for loops to go through an array of objects, small helper functions, and so on).

Originally we envisioned this and the Intermediate Algorithms project being console based to keep things simple, though the latter project now has a UI to accept user input and show the state of the game. This one could go either way, though showing results in the console would still work.

For the local database and authentication, this could also work. Both are covered in the Learn Authentication by Building a Signup Page project, though. I also worry that we might scare off some users by introducing these concepts too early. Let's get more feedback from @beaucarnes and others in the community about this. 

I was thinking this project could be more about writing simple functions / algorithms to sort or filter through a list of news stories. For example, a function that sorts articles by their published date, or returns all the articles by a particular author. Here's an early CodePen with some possible articles: https://codepen.io/scissorsneedfoodtoo/pen/pBqOvw?editors=0012

That said, we could always change things up so learners are working with social media comments and posts. Do you have any other ideas for this project?

**Comment by 01Clarian** [comment]
@scissorsneedfoodtoo  Hey, awesome.  Thanks for getting back. 

OK. That makes sense if there's already an overview covered in Sign Up to avoid redundancies.

What about tweaking those similar concepts then of the small helper functions and for loops, and applying them to filtering and sort arrays etc to access  data of a similar style from the articles written up in https://codepen.io/scissorsneedfoodtoo/pen/pBqOvw?editors=0012 ?

As mentioned, we can create a basic search for authors and display articles / posts by recent date.
We could make a text input for the search, but maybe more simple approach is just console? Either way, I could work on a prototype that heads towards that overall direction, if that makes sense.

**Comment by scissorsneedfoodtoo** [comment]
Hi @01Clarian, those are all excellent ideas, and should cover most if not all of the concepts covered in the current [Basic Algorithm Scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/) section. Feel free to add or remove any functionality that makes sense for this type of project, and to modify that list of articles however you see fit.

About the simple UI, my inclination is to keep it console based for now so learners can focus more on the code. I'll reach out to @QuincyLarson and @beaucarnes to see what they think is more appropriate here.

**Comment by 01Clarian** [comment]
@scissorsneedfoodtoo  Very cool. Sounds good. 

Look forward to get it going this week and will stay tuned regarding UI and/or additional input.

**Comment by 01Clarian** [comment]
@scissorsneedfoodtoo  Hey, Managed to write up a quick prototype this morning. Taking into consideration the data object you provided and instead running some loops and sorting. 

Covers: 
Array vs. objects. 
Filter and reduce 
Objects.keys / for in  
Sort method including compare conditions and helper function
Filter search for Author
And reduce, .push and function to sort by sections into new arrays.

Please find  codepen below:
https://codepen.io/clarian/pen/JjjQMab
c

**Comment by scissorsneedfoodtoo** [comment]
@01Clarian, sorry for the delay and thank you for your patience.

I took a look at your latest prototype and it's headed in the right direction. All of those points you listed are definitely things that we want to cover in the final project. 

Some quick suggestions would be to use `let` or `const` rather than `var` wherever possible, and to try and group things into functions wherever possible. For example, the code to filter by author names could be a function that takes an author's name as an argument, then goes through all the articles in the different sections and returns them as an array.

Another thing we could do is add another couple of pages with several articles each. I'm thinking the pages can be the different sections that already exist, like programming, web development, and so on. The final project can have a separate file with a large array of objects so learners can just focus on learning algorithms. I can work on adding these other sections and articles.

Do you have some time to hop on a call this week and talk more about this project? If so, please sent me an email at kris@freecodecamp.org.

**Comment by 01Clarian** [comment]
@scissorsneedfoodtoo  No problemo - Sent you an email.

Cheers
