### ISSUE TITLE
Learn CSS Grid by Building a Magazine

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#124]

**Comment by thecodingaviator** [comment]
@QuincyLarson Can I pick this one up? You can check my [CodePen](https://codepen.io/thecodingaviator/pens/public/) I have some examples of CSS things I've done over there, if it looks good, please assign it!

Edit: If you also want me to teach CSS variables in JS, I can do that for the project too

Edit 2: I've made an example project [here](https://codepen.io/thecodingaviator/full/BbMLQM). I know the colours are not great a.t.m.. Not really a designer.

**Comment by QuincyLarson** [comment]
@thecodingaviator Awesome! I've assigned this to you in GitHub.

Your initial project looks great! I'm a huge Carl Sagan fan, and this is the first time I remember hearing that quote about the US and Mars.

Yes - you can tweak the CSS a bit to make it look even better. Once you're ready, you can start working backward to create the test text.

**Comment by thecodingaviator** [comment]
That is because the US and Mars quote is Neil deGrasse Tyson's 🤣

**Comment by thecodingaviator** [comment]
@QuincyLarson I'm totally out of ideas on what part of the CSS could need changes, any tips?

**Comment by QuincyLarson** [comment]
@thecodingaviator Ah - that makes sense. Never give up - trust your instincts, Fox! 

We can ship it looking the way it is and other contributors can come in and pretty it up later.

Regarding those basic files, they are only a few lines. You could also have people build those real quick at the beginning something like "first let's set the stage". That way people will feel like they built the entire project.

**Comment by thecodingaviator** [comment]
@QuincyLarson I'm just confused how to write the steps, do you want me to write all of them as a list in one `.txt`  file or make different `.txt` files for each step or do something on an `.html` file or so?

**Comment by QuincyLarson** [comment]
@thecodingaviator The simplest way would be to do these as separate files. 

You can see how @beaucarnes is doing this here: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files

**Comment by QuincyLarson** [comment]
@thecodingaviator The simplest way would be to do these as separate files. 

You can see how @beaucarnes is doing this here: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files

**Comment by thecodingaviator** [comment]
@QuincyLarson I'm doing something on #136 , does that look fine?

**Comment by QuincyLarson** [comment]
@thecodingaviator Yes - this looks great. How you do this doesn't matter too much as long as:
1) you specify the state of the code at the beginning of each test
and 2) You put the test text around where the change needs to be made.

And you're doing both of these. Keep up the great work on this!

**Comment by scissorsneedfoodtoo** [comment]
This project is open for anyone to pick up. See the to do file for more information: https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/css-grid-magazine/TODO.md

**Comment by ryanwaltmurray** [comment]
I could chip away at this one. This month is very busy for me, so leaving the 'help wanted' tag on wouldn't be a bad idea. I can collaborate with anyone who wants to sign onto it.

**Comment by scissorsneedfoodtoo** [comment]
@ryanwaltmurray, that sounds great! Any help would be greatly appreciated. For this, it would be best to fork the [finished project](https://codepen.io/thecodingaviator/pen/BbMLQM) on CodePen and try to make it more mobile friendly. The [TODO.md](https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/css-grid-magazine/TODO.md) file has some other CSS Grid examples that might serve as inspiration.

**Comment by ryanwaltmurray** [comment]
@scissorsneedfoodtoo I reviewed the finished product and CSS grid examples and have a question before continuing. My question is about whether we should incorporate CSS multi-column layout into the lesson and showcase CSS grid in other ways (sidebar images for example). The current lesson basically showcases CSS grid by positioning everything into columns with grid-template-areas. However, this is done much more efficiently using CSS multi-column layout. For example, text is currently 'columnized' by manually wrapping text in DIV tags so that it splits at the right point to give the appearance of text-wrapping. However, as soon as we add more text, or a quote, or an image, or change the number of columns, the nice and tidy layout breaks down. These problems would basically multiply when making it mobile-friendly. With css multi-column layout, this isn't an issue.

I tried to find ways to mimic what CSS multi-column layout does with CSS-grid, but I feel like it's working against the flow of CSS. Am I right in my assessment of the issues? What are you thoughts? Any suggestions?

**Comment by scissorsneedfoodtoo** [comment]
@ryanwaltmurray, yes, I believe you're right in that there's no good way to replicate CSS multi-column layouts in CSS grid, at least without manually wrapping text in `<div>` elements. Like you mentioned, it would be best to showcase CSS grid to layout major elements of the page like the sidebar images and the areas for text. Then inside of those text areas, using `column` or other CSS multi-column properties should be fine.

Could you start working on a prototype? Just let me know if there's anything I can help with!

**Comment by ryanwaltmurray** [comment]
Here's the prototype, let me know if there's any comments!

https://codepen.io/ryanwaltmurray/full/mYVgpv

**Comment by scissorsneedfoodtoo** [comment]
@ryanwaltmurray, thank you for your patience. This looks great! Thank you for updating this prototype. The mobile responsiveness works really well, and I like the way the larger elements shift from vertical to horizontal alignment depending on the screen size.

This definitely seems ready to break down into short lessons. The [CSS Animations Ferris Wheel](https://github.com/freeCodeCamp/CurriculumExpansion/tree/master/learn-css-animations-by-building-a-ferris-wheel) project is a good example of the length and complexity we're looking for in each step. This project will probably be the last CSS project, though, so you don't have to go into great detail about every CSS property you use. Concentrating mostly on the CSS Grid stuff is totally fine.

Please let me know if you have any questions or if I can do anything to help! Also, do you have about 20 or 30 minutes to hop on a call? I'd love to learn more about you and talk about your project. If so, please send me a message at kris@freecodecamp.org so we can set something up.

**Comment by Nirajn2311** [comment]
Hi, is this up for taking or is it done?

**Comment by thecodingaviator** [comment]
@Nirajn2311 check with @ryanwaltmurray

**Comment by Nirajn2311** [comment]
@ryanwaltmurray any update?

**Comment by ryanwaltmurray** [comment]
@Nirajn2311 please go ahead and finish it off if you have time, that would be great. I’ve become quite busy and had this on the back burner. The CodePen link above is the still the latest progress. If you have any questions about it feel free to message me.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for the update @ryanwaltmurray, and for offering to pick this up @Nirajn2311.

**Comment by scissorsneedfoodtoo** [comment]
Hi @Nirajn2311, were you able to make any progress on breaking this project down into smaller steps?

**Comment by Nirajn2311** [comment]
@scissorsneedfoodtoo sry mate, I was busy. Imma sit down and look at this in the weekend.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you @Nirajn2311. Also, please don't hesitate to send me an email at kris@freecodecamp.org if you want to set up a call to talk more about this project before you really start breaking it down.

**Comment by padunk** [comment]
Can I take this one? or is it done?

**Comment by thecodingaviator** [comment]
@padunk please go ahead

**Comment by scissorsneedfoodtoo** [comment]
Hi @padunk, thanks for taking this other project. Please post an updated prototype here when you get the chance, and don't hesitate to reach out if there's anything we can help with.

**Comment by padunk** [comment]
@thecodingaviator great, I will work on it this week. Thanks.

**Comment by padunk** [comment]
Hi @scissorsneedfoodtoo ,
Here is the updated prototype that I made. [link-1](https://codepen.io/padunk/pen/GRgRLQo).
I didn't make a new one,  just take the old one and change it a little bit.
What do you think? Or should I work with the old one made by @ryanwaltmurray ?

**Comment by scissorsneedfoodtoo** [comment]
Hi @padunk, just took a look at your prototype and it's looking good. I like the changes that you made to the older prototype -- it looks like something you would see in an actual online magazine.

One thing I noticed is that the mobile view could use a bit of tweaking. The hero image doesn't seem to scale to the size of the screen, and you have to scroll horizontally to read all the text on the page: 

![image](https://user-images.githubusercontent.com/2051070/70413642-359dab80-1a9b-11ea-883d-9be2d9c551a2.png)

Also, the author's name and published date look a bit strange rotated 90 degrees like that. Would it be possible to move that above the hero image like in the last prototype? Or below if you think that looks better: 

![image](https://user-images.githubusercontent.com/2051070/70413965-0dfb1300-1a9c-11ea-864f-6e4bfc9c573c.png)

![image](https://user-images.githubusercontent.com/2051070/70413982-1a7f6b80-1a9c-11ea-8b5c-64b29613e12d.png)

I like the idea of having a "Top four things to do in space" list. I just updated the text slightly here: https://codepen.io/scissorsneedfoodtoo/pen/rNaxLXO

**Comment by padunk** [comment]
@scissorsneedfoodtoo , Yes, I noticed that the image doesn't responsive, yet I still figuring it out. Cause grid kind of work differently with different browsers.
For the author and icon name, I will surely fix it.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for all your hard work on this. Looking forward to seeing your next prototype.

**Comment by padunk** [comment]
HI @scissorsneedfoodtoo, I already update the prototype. Could you please check? Thank you.
https://codepen.io/padunk/pen/GRgRLQo?editors=0100

**Comment by scissorsneedfoodtoo** [comment]
@padunk, thanks for your patience.

This looks great on mobile and desktop. Very responsive now, and it seems like there will be a lot of CSS Grid concepts we can teach here.

Just going to ask @beaucarnes and @QuincyLarson for some feedback before we start breaking this project down into steps.

**Comment by beaucarnes** [comment]
This looks good! 

I think maybe when it was fixed for a mobile layout that may have broke part of the desktop layout.

Is it supposed to look like this?:
![image](https://user-images.githubusercontent.com/1513130/71028417-39ed4880-20db-11ea-98c8-450316fe3955.png)

Also, this is a very minor fix, but the hero subtitle sentence should have a period.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your review, @beaucarnes. Great catch with the missing period in the hero subtitle.

@padunk, could you change that sentence to the following?: "Typically, when you look for role models, you want someone who has your interests and came from the same background." It's just missing the period at the end of the sentence.

Also as Beau mentioned, the images around the hero subtitle could use some work. Could you play with the alignment a bit so the pictures don't overlap like that? Also, in the final project, feel free to download any pictures from Unsplash you prefer and include them in the project directory. We shouldn't use random images from Unsplash in the final project.

**Comment by padunk** [comment]
@scissorsneedfoodtoo and @beaucarnes. Thank you for the input.
I made the images overlap intentionally to show that we could style it outside of the grid area with a negative margin. But I could fix it if that looks odd.
And noted for the random images, I will find good images with this.
Anyway, I will start to break this code little by little tomorrow.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, I see, thank you for your explanation. It does look a little odd since the images overlap like that.

If I remember correctly, negative margins are covered in other projects like the Typography Nutrition Label, so it could be good review here. Perhaps it could be fixed by selecting images with transparent backgrounds that look good when overlapping. If that's not possible, then it might be better to stick with a more traditional grid layout for that section of the page.

**Comment by padunk** [comment]
Happy new year.
@scissorsneedfoodtoo , I update the prototype and deleting the negative margin.
I'm on the processed of breaking the codes to small code now. 
Hopefully, I can finish it this week. No promise though.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, awesome, thank you for the update and for all of your efforts :+1: 

Please feel free to submit a PR with the first 10 or 15 steps if you'd like some early feedback. Otherwise, looking forward to seeing all of your broken down steps.

**Comment by padunk** [comment]
@scissorsneedfoodtoo I already submit a PR with the first 25 steps.
But please review it. I think if we want to focus on Grid the step on file 90 - 170 can be skipped.
Thank you.

**Comment by scissorsneedfoodtoo** [comment]
@padunk, awesome, thank you for the heads up about your PR. I'll go through it soon and leave some feedback there.
