### ISSUE TITLE
Learn Responsive Web Design by Building a Piano

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#126]

**Comment by RafaelDavisH** [comment]
I’m ready to get my hands dirty with this issue! 🙋🏽‍♂️

**Comment by QuincyLarson** [comment]
@RafaelDavisH Awesome! We would welcome your contribution! 

The first step is to build the project itself. Then you can work backward to break it down into steps, like this: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files#diff-99314d694942b489d28d8a6f0c3bc5a3

**Comment by RafaelDavisH** [comment]
update: The responsive design piano is almost complete. I am reaching out for input to the rest of the contributor at FreeCodeCamp Gitter forum. Here is the link to this project https://codepen.io/RafaelDavisH/project/editor/DyanzQ#

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, I saw your post in the chatroom the other day. Your project looks awesome! Can't wait to build it myself.

Seems like you're ready to start breaking the projects down into steps. Please let me know if you have any questions or if I can help with anything.

**Comment by RafaelDavisH** [comment]
@scissorsneedfoodtoo hey thanks 👋! So which Repo do I clone to push the code and PR from?

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, you can clone and push to this repo. There's no code to speak of, so you'll have to create all the directories and files for each step yourself. Here's a good example: https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, I saw you merged into the master branch here. Sorry, I believe this is because I was unclear in my last message.

What you need to do is clone this repo, create a branch named something like `feat/responsive-web-design-piano` with all of your changes, then open a Pull Request targeting the master branch here. Then we can all take a look at your code and review it. Is that something I can help with? It's similar to contributing to the main freeCodeCamp repo outlined here: `https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md`

Is that something I can help with? I'd be happy to hop on a call if you have some time.

**Comment by RafaelDavisH** [comment]
yikes!

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, it's no problem! I've done the same thing before. We should probably adjust the settings for this repo to prevent this from happening in the first place.

**Comment by RafaelDavisH** [comment]
@scissorsneedfoodtoo thanks,  I'll get this going. If do have any problems I'll let you know

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, sure thing. Don't worry about what you pushed to the master branch. I can submit a PR to clear that up. Go ahead and create your pull request and I'll take a look at your draft soon.

**Comment by RafaelDavisH** [comment]
@scissorsneedfoodtoo All done. Hopefully, everything looks good.

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, yes, everything looks good now. We'll review your project ASAP!

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, just wanted to check in and see if you were able to start breaking down this project a bit more. Please take a look at my review here: https://github.com/freeCodeCamp/CurriculumExpansion/pull/146

**Comment by scissorsneedfoodtoo** [comment]
This project is open for anyone to work on! See the to do file for more information: https://github.com/freeCodeCamp/CurriculumExpansion/blob/master/responsive-web-design-piano/TODO.md

**Comment by RafaelDavisH** [comment]
@scissorsneedfoodtoo I got really busy this past week. I can take care of this if its ok and no one has taken it.

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, no problem! Yes, please take another pass at it if you have some time. Please take a look at the review comments I left in [your PR](https://github.com/freeCodeCamp/CurriculumExpansion/pull/146) before it was merged for a more detailed review. Also, do you have about 20 to 30 minutes for a quick call later this week? I'd be happy to discuss your project and how we can break down some of the lessons. If so, please send me a message at kris@freecodecamp.org.

**Comment by RafaelDavisH** [comment]
> @RafaelDavisH, no problem! Yes, please take another pass at it if you have some time. Please take a look at the review comments I left in [your PR](https://github.com/freeCodeCamp/CurriculumExpansion/pull/146) before it was merged for a more detailed review.
> 
> Also, do you have about 20 to 30 minutes for a quick call later this week? I'd be happy to discuss your project and how we can break down some of the lessons. If so, please send me a message at [kris@freecodecamp.org](mailto:kris@freecodecamp.org). If not, go ahead and write any questions you have here and I'll answer them right away.

@scissorsneedfoodtoo this repo is ready to merge. I’m working on the rest of the steps and soon I will push those too.

**Comment by scissorsneedfoodtoo** [comment]
@RafaelDavisH, okay, thank you! I'll take a look now.
