### ISSUE TITLE
Learn Typography by Building a Nutrition Label

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#128]

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, could I start working on this, too?

**Comment by scissorsneedfoodtoo** [comment]
Here's an example project I'm still working on: https://codepen.io/scissorsneedfoodtoo/pen/MxVpLK

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Wow - this is uncanny! Excellent work!
