### ISSUE TITLE
Learn CSS Animations by Building a Ferris Wheel

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#129]

**Comment by sw-yx** [comment]
it  looks like this issue should be closed, @beaucarnes

**Comment by scissorsneedfoodtoo** [comment]
@sw-yx, thanks for dropping in! I think we'd like to keep this open until the actual project has shipped. Eventually someone will have to circle back to this project and start writing the actual tests, porting them to Markdown files, and so on. I'll leave this open for now so we can keep the discussion going throughout the rest of the process.

**Comment by sw-yx** [comment]
ah, apologies. didnt know the norms.

**Comment by scissorsneedfoodtoo** [comment]
No need to apologize! I'm still figuring them out myself.
