### ISSUE TITLE
Responsive Web Design Project: Technical Documentation Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#13]
We are introducing a few new front end projects to give campers more experience working just with HTML and CSS before adding JavaScript to the mix. 

Here are the agile use stories for this challenge:
1. I can see a list of commands on a sidebar.
2. The sidebar stays in the same place when I scroll down through the documentation.
3. When I click a command link on the sidebar, the page scrolls down to that command's documentation entry.
4. The documentation has a clear visual hierarchy to emphasize important aspects of each documentation entry.
5. All code snippets are rendered using the "code" html elements

We are looking for a volunteer who can build a working demo of this on CodePen using only HTML5 and CSS (no libraries).

**Comment by akshaynaik404** [comment]
Hi Quincy, I couldn't understand the 5th user story.

Are we supposed to render the code from external sites (like JSFiddle) or just put it in <code> tag ?

**Comment by ChaituVR** [comment]
@akshaynaik404 you started it? any progress?

**Comment by akshaynaik404** [comment]
Not yet @ChaituVR . u can go for it. I was just looking for some clarification.

**Comment by ChaituVR** [comment]
@akshaynaik404  no hurry :) you can do it ... i guess 5th user story is that all the code snippets provided in the Documentation should be in our code itself.. no apis or something... you start it if you got some time and if you still have some doubt quincy will respond as soon as he read this ..

**Comment by QuincyLarson** [comment]
@ChaituVR @akshaynaik404 Yes - what I was really trying to express with this user story is that it should be shown as code.

**Comment by QuincyLarson** [comment]
@ChaituVR since you did such a good job on https://github.com/FreeCodeCamp/CurriculumExpansion/issues/12 would you like to also tackle this one?

**Comment by ChaituVR** [comment]
@QuincyLarson sure.. Got some free time..   I will start it soon..  :)

**Comment by ChaituVR** [comment]
@QuincyLarson Hey i finished it here ...http://codepen.io/ChaituVR/full/pbprjE/ if any changes are needed i would like to change them

**Comment by QuincyLarson** [comment]
@ChaituVR this is excellent. Great use of media queries. This is clean, simple, and exactly what I envisioned! Thank you for building this.
