### ISSUE TITLE
Learn the CSS Box Model by Building a Rothko Painting

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#131]

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, is it okay if I start working on this?

**Comment by scissorsneedfoodtoo** [comment]
Here's an example project: https://codepen.io/scissorsneedfoodtoo/pen/KEoKqe

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Well done! That looks great!

Can you work backward to break the building of the project down into steps like these?

https://github.com/freeCodeCamp/CurriculumExpansion/pull/135/files#diff-99314d694942b489d28d8a6f0c3bc5a3

**Comment by scissorsneedfoodtoo** [comment]
Sure! I'll use that as an inspiration to break the project down.
