### ISSUE TITLE
Basic JavaScript Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#14]
@alayek  is in charge of coordinating the expansion of these challenges, but he needs your help.

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

Here are the challenges we have currently planned (these can be further expanded):

- [x] Comment your JavaScript Code
- [x] Declare JavaScript Variables
- [x] Storing Values with the Assignment Operator
- [x] Initializing Variables with the Assignment Operator
- [x] Understanding Uninitialized Variables
- [x] Understanding Case Sensitivity in Variables
- [x] Add Two Numbers with JavaScript
- [x] Subtract One Number from Another with JavaScript
- [x] Multiply Two Numbers with JavaScript
- [x] Divide One Number by Another with JavaScript
- [x] Increment a Number with JavaScript
- [x] Decrement a Number with JavaScript
- [x] Create Decimal Numbers with JavaScript
- [x] Multiply Two Decimals with JavaScript
- [x] Divide one Decimal by Another with JavaScript
- [x] Finding a Remainder in JavaScript
- [x] Compound Assignment With Augmented Addition
- [x] Compound Assignment With Augmented Subtraction
- [x] Compound Assignment With Augmented Multiplication
- [x] Compound Assignment With Augmented Division
- [x] Convert Celsius to Fahrenheit
- [x] Declare String Variables
- [x] Escaping Literal Quotes in Strings
- [x] Quoting Strings with Single Quotes
- [x] Escape Sequences in Strings
- [x] Concatenating Strings with Plus Operator
- [x] Concatenating Strings with the Plus Equals Operator
- [x] Constructing Strings with Variables
- [x] Appending Variables to Strings
- [x] Find the Length of a String
- [x] Use Bracket Notation to Find the First Character in a String
- [x] Understand String Immutability
- [x] Use Bracket Notation to Find the Nth Character in a String
- [x] Use Bracket Notation to Find the Last Character in a String
- [x] Use Bracket Notation to Find the Nth-to-Last Character in a String
- [x] Word Blanks
- [x] Store Multiple Values in one Variable using JavaScript Arrays
- [x] Nest one Array within Another Array
- [x] Access Array Data with Indexes
- [x] Modify Array Data With Indexes
- [x] Access Multi-Dimensional Arrays With Indexes
- [x] Manipulate Arrays With push()
- [x] Manipulate Arrays With pop()
- [x] Manipulate Arrays With shift()
- [x] Manipulate Arrays With unshift()
- [x] Shopping List
- [x] Write Reusable JavaScript with Functions
- [x] Passing Values to Functions with Arguments
- [x] Global Scope and Functions
- [x] Local Scope and Functions
- [x] Global vs. Local Scope in Functions
- [x] Return a Value from a Function with Return
- [x] Assignment with a Returned Value
- [x] Stand in Line
- [x] Understanding Boolean Values
- [x] Use Conditional Logic with If Statements
- [x] Comparison with the Equality Operator
- [x] Comparison with the Strict Equality Operator
- [x] Comparison with the Inequality Operator
- [x] Comparison with the Strict Inequality Operator
- [x] Comparison with the Greater Than Operator
- [x] Comparison with the Greater Than Or Equal To Operator
- [x] Comparison with the Less Than Operator
- [x] Comparison with the Less Than Or Equal To Operator
- [x] Comparisons with the Logical And Operator
- [x] Comparisons with the Logical Or Operator
- [x] Introducing Else Statements
- [x] Introducing Else If Statements
- [x] Logical Order in If Else Statements
- [x] Chaining If Else Statements
- [x] Golf Code
- [x] Selecting from many options with Switch Statements
- [x] Adding a default option in Switch statements
- [x] Multiple Identical Options in Switch Statements
- [x] Replacing If Else Chains with Switch
- [x] Returning Boolean Values from Functions
- [x] Return Early Pattern for Functions
- [x] Counting Cards
- [x] Build JavaScript Objects
- [x] Accessing Objects Properties with the Dot Operator
- [x] Accessing Objects Properties with Bracket Notation
- [x] Accessing Objects Properties with Variables
- [x] Updating Object Properties
- [x] Add New Properties to a JavaScript Object
- [x] Delete Properties from a JavaScript Object
- [x] Using Objects for Lookups
- [x] Testing Objects for Properties
- [x] Introducing JavaScript Object Notation (JSON)
- [x] Accessing Nested Objects in JSON
- [x] Accessing Nested Arrays in JSON
- [x] Record Collection
- [x] Iterate with JavaScript For Loops
- [x] Iterate Odd Numbers With a For Loop
- [x] Count Backwards With a For Loop
- [x] Iterate Through an Array with a For Loop
- [x] Nesting For Loops
- [x] Iterate with JavaScript While Loops
- [x] Profile Lookup
- [x] Generate Random Fractions with JavaScript
- [x] Generate Random Whole Numbers with JavaScript
- [x] Generate Random Whole Numbers within a Range
- [x] Sift through Text with Regular Expressions
- [x] Find Numbers with Regular Expressions
- [x] Find Whitespace with Regular Expressions
- [x] Invert Regular Expression Matches with JavaScript
- [x] Using the Conditional(Ternary) Operator
- [x] Using multiple Conditional(Ternary) Operators
- [x] Using the parseInt() function
- [x] Use the parseInt() function with radix

**Comment by chuckadams** [comment]
There are no fewer than eight distinct challenges covering arithmetic operators, a different challenge for each operator.  Which is then followed by four separate challenges for the compoind assignment operators.  I found this to be more than a little excessive and tedious when I went through it, and I can't be the only one who thinks so.  

I highly recommend collapsing this epic saga into two challenges: "Arithmetic Operations" and "Compound Assignment" .

Also, purely bikeshedding now, I recommend either dropping "with JavaScript" from all the titles or adding it to all of them for consistency.  I'm partial to the former.

**Comment by atjonathan** [comment]
@chuckadams Yeh I agree we should remove with JavaScript. cc/ @QuincyLarson

**Comment by QuincyLarson** [comment]
@chuckadams @atjonathan our philosophy up to this point is that each challenge should cover exactly one concept and ask the learner to accomplish exactly one task. I understand that it's tedious. Is there a way we could introduce these in more interesting contexts rather than just making campers do several things in one challenge?

**Comment by SamAI-Software** [comment]
### Immutability

- [ ] [Changing Variables Values]()
- [ ] [Passing Variables by Value]()
- [ ] [Changing Values in Arrays]()
- [ ] [Changins Values in Arrays with Pointer]()
- [ ] [Passing Arrays by Reference]()
- [ ] [Changins Values in Arrays with Push Method]()
- [ ] [Getting Values from Push Method]()
- [ ] [Creating New Arrays from Existing Array]()
- [ ] [Changing Values Inside of the Objects]()
- [ ] [Creating New Objects with Assign Method]()
- [ ] [Changing Arrays Inside of the Objects]()

```
## Challenge Title

**Challenge Description**

> Need help of somebody with good English and JS theory.

**Challenge Seed**
<!-- Initial code presented to the camper -->


**Challenge Tests**
TODO
<!-- either assert tests or your ideas for things to be tested -->


**Challenge Solution**
<!-- solution to this challenge -->
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Changing Variables Values

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of bar to 2.

**Challenge Seed**
```js
var foo = 1;
var bar = foo;

bar = 1; // Change this line
```

**Challenge Tests** (TODO)

- `bar` should return 2


**Challenge Solution**
```js
var foo = 1;
var bar = foo;

bar = 2;
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Passing Variables by Value

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of global `foo` to 2.

**Challenge Seed**
```js
var foo = 1;

// Only change code below this line
function tryToChange(foo) {
	foo = 2;
// Only change code above this line
}

tryToChange(foo);
```

**Challenge Tests** (TODO)
- `foo` should return 2

**Challenge Solution**
```js
var foo = 1;

function tryToChange() {
	foo = 2;
}

tryToChange(foo); // can be changed to tryToChange(), but not necessary
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Changing Values in Arrays

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Value of `foo` should stay the same [0, 1].
> Change the value of `bar` to [0, 2].

**Challenge Seed**
```js
var foo = [0, 1];
var bar = foo;

bar = 0; // Change this line
```


**Challenge Tests** (TODO)
- `foo` should return `[0, 1]`
- `bar` should return `[0, 2]`

**Challenge Solution**
```js
var foo = [0, 1];
var bar = foo;

bar = [0, 2];
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability - Changing Values in Arrays with Pointer

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of `foo` to `[0, 2]`
> Don't use `foo` to define `foo`.

**Challenge Seed**
```js
var foo = [0, 1];
var bar = foo;

bar[1] = 0; // Change this line
```

**Challenge Tests** (TODO)
- `foo` should return `[0, 2]`
- `bar` should return `[0, 2]`

**Challenge Solution**
```js
var foo = [0, 1];
var bar = foo;

bar[1] = 2;
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability - Passing Arrays by Reference

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of `foo` to `[0, 2]`.
> Don't use `foo` to define `foo`.

**Challenge Seed**
```js
var foo = [0, 1];

function tryToChange(bar) {
// Only change code below this line
	bar = [0, 2];
// Only change code above this line
}

tryToChange(foo);
```


**Challenge Tests** (TODO)
- `foo` should return `[0, 2]`
- `bar` should return `undefined`

**Challenge Solution**
```js
var foo = [0, 1];

function tryToChange(bar) {
	bar[1] = 2;
}

tryToChange(foo);
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 06 - Changins Values in Arrays with Push Method

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of `foo` to `[0, 1, 2]` using `.push()` method

**Challenge Seed**
```js
var foo = [0, 1];

foo.push(); // Change this line
```


**Challenge Tests** (TODO)
- `foo` should return `[0, 1, 2]`.
- `.push()` should be used

**Challenge Solution**
```js
var foo = [0, 1];

foo.push(2);
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 07 - Getting Values from Push Method

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of `foo` using `.push()`
> `foo` should be an array of integers.
> `bar` should be equal to `4`.

**Challenge Seed**
```js
var foo = [0, 1];

bar = foo; // Change this line
```

**Challenge Tests** (TODO)
- `foo` should return array with 4 integers.
- `bar` should return `4`.

**Challenge Solution**
```js
var foo = [0, 1];

bar = foo.push(2, 3); //bar return new length of array
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 08 - Creating New Arrays from Existing Array

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change the value of `bar` to `[0, 2]`.
> Value of `foo` should stay the same `[0, 1]`.

**Challenge Seed**
```js
var foo = [0, 1];

bar = foo; // Change this line

bar[1] = 2;
```


**Challenge Tests** (TODO)
- `foo` should return `[0, 1]`
- `bar` should return `[0, 2]`

**Challenge Solution**
```js
var foo = [0, 1];

bar = foo.concat();

bar[1] = 2;
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 09 - Changing Values Inside of the Objects

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Set `species` to `"Jedi"` for both `dad` and `son`.
> Don't use `species` from `dad` object directly.

**Challenge Seed**
```js
var dad = {species: "Human"};
var son = dad;

son = "Jedi"; // Change this line
```


**Challenge Tests** (TODO)
- `dad.species` should return `"Jedi"`
- `son.species` should return `"Jedi"`

**Challenge Solution**
```js
var dad = {species: "Human"};
var son = dad;

son.species = "Jedi";
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 10 - Creating New Objects with Assign Method

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change son to `"Dark"` side.
> Dad should stay on the `"Light"` side.

**Challenge Seed**
```js
var dad = {species: "Jedi", side: "Light"};
var son = Object.assign({}, dad); // Change this line
```


**Challenge Tests** (TODO)
- `dad` should return `Object { species: "Jedi", side: "Light" }`
- `son` should return `Object { species: "Jedi", side: "Dark" }`

**Challenge Solution**
```js
var dad = {species: "Jedi", side: "Light"};
var son = Object.assign({}, dad, {side: "Dark"});
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 11 - Changing Arrays Inside of the Objects

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change son to `"Dark"` side.
> Dad should stay on the `"Light"` side.
> Increase son's force to `[0, 1, 2]`.
> Dad's force should stay the same `[0, 1]`.

**Challenge Seed**
```js
var dad = {species: "Jedi", side: "Light", force: [0, 1]};
var son = Object
// Only change code below this line
		 .assign({}, dad, {force: force.concat(2)});
// Only change code above this line
```

**Challenge Tests** (TODO)
- `dad` return `Object { species: "Jedi", side: "Light", force: Array[2] }`
- `son` return `Object { species: "Jedi", side: "Dark", force: Array[3] }`

**Challenge Solution**
```js
var dad = {species: "Jedi", side: "Light", force: [0, 1]};
var son = Object
		 .assign({}, dad, {side: "Dark", force: dad.force.concat(2)});
```

**Comment by SamAI-Software** [comment]
[<- back to Immutability list](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/14#issuecomment-234778769)

## Immutability 12 - Passing Objects by Reference

**Challenge Description** (TODO)

> Need help of somebody with good English and JS theory.
> ### Instructions
> Change son to `"Light"` side.
> Set son's force equal to `4` using only `.push()` method.
> Don't use global variables directly inside `changeSide()` function.

**Challenge Seed**
```js
var son = {species: "Jedi", side: "Dark", force: [0, 1, 2]};

function changeSide(jedi) {
// Only change code below this line
	side = "Light";
	force.push();
// Only change code above this line
}

changeSide(son);
```

**Challenge Tests** (TODO)
- `son` return `Object { species: "Jedi", side: "Light", force: 4 }`
- Only `.push()` method should be used inside `.changeSide()` function.
- `jedi.force = 4` or `="4"` should not be used.

**Challenge Solution**
```js
var son = {species: "Jedi", side: "Dark", force: [0, 1, 2]};

function changeSide(jedi) {
// Only change code below this line
	jedi.side = "Light";
	jedi.force = jedi.force.push(3);
// Only change code above this line
}

changeSide(son);
```

**Comment by chuckadams** [comment]
@QuincyLarson A challenge that covers all the inline binary math operators at once is still just introducing one concept in JS.  We're not introducing the concepts of addition, multiplication, subtraction after all, since I'd call those a prerequisite for any programming course.

**Comment by QuincyLarson** [comment]
@chuckadams yes - I understand that we're not introducing these concepts. For a non-programmer, the symbols * and / will be new concepts. I don't see why having a couple additional challenges is problematic.

**Comment by alayek** [comment]
@SamAI-Software great job so far! Would you like to take this up as owner?

**Comment by alayek** [comment]
After discussion with @SamAI-Software, I have decided to take this up as owner. He will submit problems like he has been doing. I will do the meta work (cataloging, indexing, proofreading, reviewing etc.)

@atjonathan @koustuvsinha maybe you guys can lend us a hand too!

@QuincyLarson FYI.

**Comment by atjonathan** [comment]
@alayek, defiantly! I'm not so good with the theory write up though...

**Comment by QuincyLarson** [comment]
@alayek excellent. I've added you as the owner of this topic. Thanks for helping work with @SamAI-Software and everyone else to expand these JavaScript challenges.

**Comment by UsamaHameed** [comment]
@QuincyLarson Can we expand the JS challenges and add these? 

1. Using forEach loop
2. Using the .every() function
3. Using the .some() function

**Comment by alayek** [comment]
@FeelTheForce might want to add it in the FP section?

**Comment by FeelTheForce** [comment]
@alayek So should I create these challenges?

**Comment by alayek** [comment]
@FeelTheForce please come on [gitter](https://gitter.im/alayek) so that we can discuss and finalize next steps.

**Comment by UsamaHameed** [comment]
**Challenge**
Using the Conditional(Ternary) Operator

**Challenge Description**
The conditional/ternary operator is a one line `if-else` statement.
For example: 
```javascript
function findGreater(a, b) {
	if(a > b)
		return "a is greater";
	else
		return "b is greater";
}
```
The above function can be written using the conditional like:
```javascript
function findGreater(a, b) {
	return a > b ? "a is greater" : "b is greater";
}
```
**Useful Links**
* [Conditional Operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

**Instructions**
Using a `Conditional Operator`, check if two numbers are equal or not.

**Challenge Seed**
```javascript
function findGreater(a, b) {
	
}
findGreater(1, 2);
```

**Challenge Tests**
I have not used assert before so correct me if there is an error.
*There should be a test to check if the camper is actually using a conditional. Not sure how to do that.* 
`findGreater(1, 2);` should return false.
`findGreater(1, 1);` should return true.
`findGreater(1, -1);` should return false.

```javascript
assert(findGreater(1, 2) !== false, 'findGreater(1, 2) should return false');
assert(findGreater(1, 1) !== true, 'findGreater(1, 1) should return true');
assert(findGreater(1, -1) !== false, 'findGreater(1, -1) should return false');
```

**Challenge Solution**
```javascript
function findGreater(a, b) {
	return a === b ? true : false;
}
```

**Comment by UsamaHameed** [comment]
**Challenge**
Using the Conditional(Ternary) Operator

**Challenge Description**
The conditional/ternary operator is a one line `if-else` statement.
For example: 
```javascript
function findGreater(a, b) {
	if(a > b)
		return "a is greater";
	else
		return "b is greater";
}
```
The above function can be written using the conditional like:
```javascript
function findGreater(a, b) {
	return a > b ? "a is greater" : "b is greater";
}
```
**Useful Links**
* [Conditional Operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

**Instructions**
Using a `Conditional Operator`, check if two numbers are equal or not.

**Challenge Seed**
```javascript
function checkEqual(a, b) {
	
}
checkEqual(1, 2);
```

**Challenge Tests**
I have not used assert before so correct me if there is an error.
*There should be a test to check if the camper is actually using a conditional. Not sure how to do that.* 
`checkEqual(1, 2);` should return false.
`checkEqual(1, 1);` should return true.
`checkEqual(1, -1);` should return false.

```javascript
assert(checkEqual(1, 2) !== false, 'checkEqual(1, 2) should return false');
assert(checkEqual(1, 1) !== true, 'checkEqual(1, 1) should return true');
assert(checkEqual(1, -1) !== false, 'checkEqual(1, -1) should return false');
```

**Challenge Solution**
```javascript
function checkEqual(a, b) {
	return a === b ? true : false;
}
```

**Comment by UsamaHameed** [comment]
**Challenge**
Use the `parseInt()` function

**Challenge Description**
The `parseInt()` function parses a string and returns an integer. 
```javascript
var a = parseInt("007");
```
The above function will convert the string `"007"` to an integer `7`.
**Useful Links**
* [parseInt](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseInt)

**Instructions**
Using the `parseInt()` function, write a function that converts strings to integers and returns them.

**Challenge Seed**
```javascript
function convertToInteger(str) {
	
}
convertToInteger("56");
```

**Challenge Tests**
I have not used assert before so correct me if there is an error.
*There should be a test to check if the camper is actually using `parseInt()` or not. Not sure how to do that.* 
`convertToInteger("56");` should return a number.
`convertToInteger("56");` should return 56.
`convertToInteger("77");` should return 77.
`convertToInteger("JamesBond");` should return NaN.

```javascript
assert(typeOf(convertToInteger("56")) !== "number", 'convertToInteger("56") should return a number');
assert(convertToInteger("56") !== 56, 'convertToInteger("56") should return 56');
assert(convertToInteger("77") !== 77, 'convertToInteger("56") should return 77');
assert(isNaN(convertToInteger("JamesBond")); , 'convertToInteger("JamesBond") should return NaN');
```

**Challenge Solution**
```javascript
function convertToInteger(str) {
	return parseInt(str);
}
```

**Comment by UsamaHameed** [comment]
**Challenge**
Use the `parseInt()` function with `radix`

**Challenge Description**
The `parseInt()` function parses a string and returns an integer. The `radix` variable defines the number system to convert from. 
The function call looks like: 
`parseInt(string, radix);`
```javascript
var a = parseInt("11", 2);
```
Here the `radix` variable defines that `"11"` is in `binary` system.
The above function will convert the string `"11"` to an integer `3`.
**Useful Links**
* [parseInt](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/parseInt)

**Instructions**
Using the `parseInt()` function, write a function that converts binary numbers to integers and returns them.

**Challenge Seed**
```javascript
function convertToInteger(str) {
	
}
convertToInteger("10011");
```

**Challenge Tests**
I have not used assert before so correct me if there is an error.
*There should be a test to check if the camper is actually using `parseInt()` or not. Not sure how to do that.* 
`convertToInteger("10011");` should return a number.
`convertToInteger("10011");` should return 19.
`convertToInteger("111001");` should return 57.
`convertToInteger("JamesBond");` should return NaN.

```javascript
assert(typeOf(convertToInteger("10011")) !== "number", 'convertToInteger("10011") should return a number');
assert(convertToInteger("10011") !== 19, 'convertToInteger("10011") should return 19');
assert(convertToInteger("111001") !== , 'convertToInteger("111001") should return 57');
assert(isNaN(convertToInteger("JamesBond")); , 'convertToInteger("JamesBond") should return NaN');
```

**Challenge Solution**
```javascript
function convertToInteger(str) {
	return parseInt(str, 2);
}
```

**Comment by UsamaHameed** [comment]
**Challenge**
Using multiple Conditional(Ternary) Operators

**Challenge Description**
In the previous challenge, we used a single conditional operator. Now, we will learn how to use multiple conditionals. 
For example: 
```javascript
function findGreaterOrEqual(a, b, c) {
	if(a === b)
		return "a and b are equal";
	else if(a > b)
		return "a is greater";
	else
		return "b is greater";
}
```
The above function can be written using multiple conditionals like:
```javascript
function findGreaterOrEqual(a, b) {
	return (a === b) ? "a and b are equal" : (a > b) ? "a is greater" : "b is greater";
}
```
*Note that the conditional operator is Right Assosiative.*
**Useful Links**
* [Conditional Operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

**Instructions**
Using a `Conditional Operator`, check if a number is positive, negative or zero.

**Challenge Seed**
```javascript
function checkSign(num) {
	
}
checkSign(10);
```

**Challenge Tests**
I have not used assert before so correct me if there is an error.
*There should be a test to check if the camper is actually using a conditional. Not sure how to do that.* 
`checkSign(10);` should return "positive".
`checkSign(-12);` should return "negative".
`checkSign(0);` should return "zero".

```javascript
assert(checkSign(10) !== 'positive', 'checkSign(10) should return positive');
assert(checkSign(-12) !== 'negative', 'checkSign(-12) should return negative');
assert(checkSign(0) !== 'zero', 'checkSign(0) should return zero');
```

**Challenge Solution**
```javascript
function checkSign(a) {
	return (a === 0) ? "zero" : (a > 0) ? "positive" : "negative";
}
```

**Comment by QuincyLarson** [comment]
@UsamaHameed Nested turnaries - that's also an excellent challenge idea. Keep up the great work on these.

**Comment by QuincyLarson** [comment]
I'm closing this issue since all the challenges are done. I will seed these in then update #46

**Comment by HKuz** [comment]
I'm linking to a discussion about moving the "Convert Celsius to Fahrenheit" challenge on an issue for the FreeCodeCamp branch [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7697#issuecomment-263136055) so I can keep tabs on it from this issue.

**Comment by DusanSacha** [comment]
@HKuz, as we discussed I designed a new challenge and used this thread for review. Any comments are welcome. I would place this challenge right after [Basic JavaScript: Return a Value from a Function with Return](https://beta.freecodecamp.com/en/challenges/basic-javascript/return-a-value-from-a-function-with-return). Also the structure of this new challenge is very similar to mentioned challenge, that's why it should be easy enough to complete it.
Please, let me know what do you think.

# Understanding Undefined Value returned from a Function

A function can include the <code>return</code> statement but it does not have to. In case that the function does not have a <code>return</code> statement, the function will process the inner code and the returned value in that case will be <code>undefined</code>.

## Example
```javascript
function hello() {
    console.log('Hello from a function');
}
var returnedValue = hello(); // undefined
```
<code>hello</code> is a function without a <code>return</code> statement. The function will write the <code>'Hello from function'</code> string to console but the returned value of the function is <code>undefined</code>
<hr>
Create a function <code>printName</code> that accepts one argument <code>name</code>, writes this argument <code>name</code> to console, and its returned value is <code>undefined</code>. See the last line in the editor for an example of how you can test your <code>printName</code> function.

## Challenge Seed
```javascript
function printHello(hello) {
    console.log(hello);
}

// Only change code below this line",

console.log(printHello('Hello'));
```
## Solution
<code>function printName(name) {console.log(hello);}</code>
## Tests
```javascript
assert(typeof printName === 'function', 'message: <code>printName</code> should be a function');
assert(printName('Joe') === undefined, 'message: <code>printName('Joe')</code> should return <code>undefined</code>');
```

**Comment by DusanSacha** [comment]
@QuincyLarson Hmm, I see now... 
My another idea would be to modify a global variable and show that a function can 'work' also without <code>return</code> statement.

```javascript
var sum = 0;
function addSum(num) {
    sum = sum + num;
}
var returnedValue = addSum(3); // sum will be modified but returned value is undefined
```

**Comment by QuincyLarson** [comment]
@DusanSacha Great - I think this is a better approach. What do you think, @hkuz?

**Comment by chuckadams** [comment]
While I know the curriculum isn't about beating one particular paradigm into peoples heads, I'd be more reassured by some kind of note about the evils of side effects (and globals), namely how you don't know what's going on, spooky action-at-a-distance, how you can't change the thing being modified, etc.  Seems if you're going to introduce what functions are and how they work, it's a good place to introduce functional programming concepts.  Possibly even as a followup lesson that defines terms like "pure function" and "side effect".

**Comment by QuincyLarson** [comment]
@chuckadams I agree, but there's a careful balance between trying to be exhaustive and trying not to overload new learners. This seems like a topic we could cover later in the curriculum - perhaps in a "JavaScript Best Practices" section that falls after be basic algorithm section. Would you be interested in helping design this?

**Comment by HKuz** [comment]
@DusanSacha - this looks great, especially with the proposed change (modify a global variable vs. the console statement)! Thanks for writing this 👍

**Comment by DusanSacha** [comment]
Challenge implemented in PR #15751

**Comment by DusanSacha** [comment]
@QuincyLarson @HKuz  I was thinking about the two proposed challenges in [#15388](https://github.com/freeCodeCamp/freeCodeCamp/issues/15388).

_Create a function with a single parameter that also has an inner function with its own parameter.
Create a function with two parameters that also has an inner function that has its own parameter._

Honestly, I was not sure how @revisualize ment this new challenges to be done. So in order to start I would like to discuss the original idea of these new chalenges.

While going through the current challenges, I think the idea was to have a challenge where the users have one predefined function (getUserFullName) which they have to use inside of another function (welcomeText). They will be challenged to write the code of the welcomeText function using the pre-defined function.

Here is a very short draft of my idea:

```javascript
//pre-defined function
function getUserFullName(userName) {
    return "John Doe";
}

function welcomeText(userName) {
    var welcomeText = "Welcome, ";

// Only change code below this line
    var fullName = getUserFullName(userName); //possible solution
// Only change code above this line

    return welcomeText + fullName;
}
```

The second proposed challenge could be very similiar, just welcomeText could have 2 parameters (e.g. 'language'). The string 'Welcome' could be then returned based on the 2nd parameter. (e.g. 'Welcome', 'Bienvenido'...) 

Let me know, what do you think.

**Comment by HKuz** [comment]
Hi @DusanSacha - I wasn't very close to the original discussion of the new challenges, so I'm afraid I can't shed too much light there. (Not sure if the original suggestion was to define a function inside another one, then use it in the 'outer' function?). That said, I think what you've proposed makes sense. I've found the hardest part of writing a challenge is coming up with an interactive (and testable) coding part, and what you laid out seems straightforward and simple for a single challenge.

Also, don't feel pressure to follow that list exactly. If, while you're writing these challenges, you find they seem a bit redundant, then feel free to make it just one challenge instead.
