### ISSUE TITLE
Roadmap Question: Is there a plan of having Machine learning in curriculum?

### ISSUE THREAD

**Issue by imvetri** [freeCodeCamp/CurriculumExpansion#164]
Hi,

I really appreciate how freecodeCamp's curriculum and currently its mostly about web development. Is there a plan to also have AI / ML in the curriculum just like how web development is taught ?

Thanks!

**Comment by scissorsneedfoodtoo** [comment]
@imvetri, that's a very good question! From what I understand, there are many things we would like to do with the curriculum in the future, including things like teaching Python, math for programmers, and perhaps even machine learning. I can't say for sure when any of that will happen, though, especially now that we're focused on revamping our current challenged based curriculum to one that's project based.

This repo is more for discussing and developing the new projects, so I'll close this for now. It would probably be better to ask this question over on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp) or on the [forum](https://www.freecodecamp.org/forum/) to get more of a discussion going.

**Comment by imvetri** [comment]
@scissorsneedfoodtoo I did open a discussion [issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/17486#event-2322319434) in the main repo. I was asked to continue the discussion here.

Like you said, I will continue to the forum to start a discussion thread there. Thanks for the prompt response.

**Comment by imvetri** [comment]
@scissorsneedfoodtoo  Looking at the project page, the discussion threads there are different from what I'm proposing now. 

What I would like to see/have is the future goals of this project. How can contributors initiate conversation about it?

**Comment by scissorsneedfoodtoo** [comment]
@imvetri, sorry, I didn't realize that you already created an issue in the main repo. In that case, one thing you could do is create a new general forum post in the fCC forum and label it "Feature Request: Teach Machine Learning". A lot of regular contributors hang out there, and I'm sure they would be happy to discuss adding something like this to the curriculum in the future.

Please let me know if there's anything else I can do to help!
