### ISSUE TITLE
Learn React Hooks by building a scroll bar

### ISSUE THREAD

**Issue by UsamaHameed** [freeCodeCamp/CurriculumExpansion#167]
Hello, 
I tried searching in the issues but found nothing about react hooks. I think there should be a little project where students are allowed/encouraged to use react hooks only. Or, they are asked to convert one of their existing react projects to use hooks. 

In case this is found desirable, I can work on this work.

**Comment by sw-yx** [comment]
i would recommend not further expanding the scope. react hooks are idiomatic react, lets just include them in all react projects (but also use classes since they are widespread)

**Comment by scissorsneedfoodtoo** [comment]
Yes, I agree. It would be better to try and include this in the [React Flappy Bird](https://github.com/freeCodeCamp/CurriculumExpansion/issues/117) project if possible. Still, thank you for your suggestion, @UsamaHameed!
