### ISSUE TITLE
Applied Algorithm Design Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#18]
We are seeking a camper to be in charge of coordinating the expansion of these challenges. 

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

Here are the challenges we have currently planned (these can be further expanded):

- [ ] Understand Time Complexity
- [ ] [Greedy Algorithms](https://en.wikipedia.org/wiki/Greedy_algorithm)
- [ ] [Backtracking Algorithms](https://en.wikipedia.org/wiki/Backtracking)
- [ ] [Brute Force Search Algorithms](https://en.wikipedia.org/wiki/Brute-force_search)
- [ ] [Divide and Conquer Algorithms](https://en.wikipedia.org/wiki/Divide_and_conquer_algorithms)
- [ ] [Dynamic Programming](https://en.wikipedia.org/wiki/Dynamic_programming)

**Comment by erictleung** [comment]
Could possibly use https://projecteuler.net/ and http://rosalind.info/problems/locations/ as places to get applied algorithm ideas.

**Comment by QuincyLarson** [comment]
@erictleung absolutely. Those are both excellent resources. I think we need a list of textbook examples of each of these types of algorithms (if they aren't already covered sufficiently). Then we can convert these into challenges.

**Comment by QuincyLarson** [comment]
These may be better taught as video challenges. I'm going to create video challenge issues for them.
