### ISSUE TITLE
Generators and Iterators for ES6 [FCC BETA]

### ISSUE THREAD

**Issue by Flarp** [freeCodeCamp/CurriculumExpansion#227]
Generator functions are a big feature in ES6, and the building blocks for the new async/await feature in ES201(6/7). It should certainly be covered in some way, like an introduction, and maybe a tutorial on how to make a version of async/await using generators. 

Something like

* Generators
* Some generator practice
* Async/await using generators

**Comment by scissorsneedfoodtoo** [comment]
While these challenges would be a better fit in the current curriculum, some of the new projects might be able to use the concepts covered here. Closing this for now, but thank you for all of your hard work so far, @Flarp. 

I'll ask around and see if anyone is interested in picking this up for inclusion in the current curriculum. If so, I'll reopen this issue and move it back to the main repo for more visibility.
