### ISSUE TITLE
Automated Testing Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#23]
We are seeking a camper to be in charge of coordinating the creation of these challenges. 

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

We still need to come up with a list of concepts to cover, where each topic can be taught interactively, then translate these concept into the names of the challenges.

**Comment by erictleung** [comment]
- [Test Anything Protocol](http://testanything.org/)
- [Wikipedia on Unit Testing](https://en.wikipedia.org/wiki/Unit_testing)
- [List of unit testing frameworks in JavaScript](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#JavaScript)
- [Test-Driven Development](https://en.wikipedia.org/wiki/Test-driven_development)
- [Wikipedia on Software Testing](https://en.wikipedia.org/wiki/Software_testing)

**Comment by brandenbyers** [comment]
> 2. Test suite (using the assert method)

Out of curiosity, why `assert`?

**Comment by erictleung** [comment]
@brandenbyers our challenges currently use the `assert` function to run challenge tests. So for the new challenges, they can be run using the same framework.

**Comment by brandenbyers** [comment]
Got it. Assert for the challenge tests, but I assume the subject matter for these tests wouldn't necessarily have to be assert. Confusion when talking about testing the testing challenges!

**Comment by brandenbyers** [comment]
# Automated Testing Challenges Outline/Proposal

## Why test?

    * Manual testing is tedious
    * Unlocks edge cases that may not have been considered
    * Provides a refactoring safety net
    * Enables continuous integration/delivery
    * Testing Pyramid

### Challenge Ideas

    1. Provide a manual test case for the camper and have them navigate a site/app in order to verify the test case.
    2. Show the camper that same manual test as multiple unit/integration tests; compare the time savings.
    3. Excercise to separate test cases into unit, integration, and e2e tests

---

## Testing Tools

    * Jasmine, Mocha, and Chai
    * e2e: Selinium/webdriver tools depending on platform under test
    * supertest or similar for API tests
    
### Challenge Ideas

    1. Run a test suite with passing and failing tests using mocha
    2. Try out both `assert` and `expect` Chai assertion styles

---
    
## Unit tests

    * Tests an individual "unit" of code
    * Network requests are mocked for speed and consistency
    * The foundation of a Test-Driven Development (TDD) workflow
    * These can be for function or API tests
    
### Challenge Ideas

    1. Multiple challenges focusing on speed and accuracy
        - Unit tests must be fast and when they fail, it must be clear what the problem is
    2. Write an entire test suite of unit tests focusing on specific feature
    3. Write multiple API tests

---

## Integration tests

    * Tests the logic and interaction between multiple "units" of code
    * Network requests are mocked unless part of what is being tested
    * Uneccessary behavior for what is under test will be mocked/stubbed
      - Mocks are for when verifying something returned by the mock
      - Stubs aren't verified, they can't fail the test, but provide needed behavior

### Challenge Ideas

    1. Q&A challenges to separate tests fit for unit and those fit for integration testing
    2. Write a suite of integration tests specific to a feature

---

## UI/End-to-End tests

    * Tests as the user would use the app
    * Test code has no awareness of underlying feature code
    * A webdriver uses automation code to "drive" the browser's clicks and text input
    * These are slow tests and the most "expensive" to run
    * Sleeps/waits should never be used

### Challenge Ideas

    1. Write a test that navigates through multiple pages and verifies the final page has a specific element
    2. Devise a test that needs to wait intelligently without `sleep()`,`wait()`, or the like
    3. Write an e2e test that is better suited to a unit/integration test, and then write the same test coverage as a unit/integration test and compare which one is faster and more reliable

---

## Mocking

    * Always used when network requests are a part of a unit test
    * Sometimes used for UI tests when speed, reliability, and cost are important factors
    * End-to-End (e2e) tests cannot be mocked otherwise they are not true end-to-end tests

### Challenge Ideas

---

#### Unit/Integration tests

    1. Mock a network request for a unit test that is already written for the camper
    2. Write a unit test and a mock for a function
    3. Mock multiple network requests for an integration test
    4. In an integration test with complicated logic, stub out all behavior except for what is absolutely necessary
    5. Write an integration test that requires multiple mocks (and implement the mocks as well)
    6. Mock a websocket server

#### UI tests

    1. Mock a login network request for a login page
    2. Mock the websocket/XMPP connection for a chat app

---

## Flaky tests

    * Bad tests are be worse than no tests (false sense of security)
    * Test coverage percentage isn't what is important
      - Fewer acccurate and dependable tests are worth more than hundreds of half-baked tests that either fail regularly or aren't testing what you think they are testing
    * If tests ever fail, and they aren't actually exposing a defect, then there is a bug in the test
      - Bugs aren't acceptable in feature code, so why should they be in test code
      - Irregularly failing tests (flaky tests) eventually get ingnored
    * Fix flaky tests are remove them; they are useless and cause harm to a project
    * Who's testing the tests?

### Challenge Ideas

    1. Debug an existing flaky e2e test with a simple solution
    2. Debug an existing flaky e2e test that isn't obvious
    3. Debug an existing failing e2e test that is actually exposing a defect (but the camper doesn't know that up front)
        - flaky tests breed mistrust in accurate tests
        - deciphering flaky versus legitimate failures can waste a lot of time

---

## Test-Driven Development

    * Drives the development process
      - can improve comprehension of the problem being solved
      - can catch edge cases early
    * Can speed up the overall time to develop
      - This may seem counter-intuative given that it adds another step to writing feature code
      - But it allows for code to be written quickly, with little concern for the overall quality
      - Because refactoring is easy when proven tests verify if changed code is still working code
    * May be ackward to get accustomed to at first
    * Red > Green > Refactor

### Challenge Ideas

    1. Multiple challenges that walk a camper through red > green > refactor
    2. Challenges that stress the importance of considering edge cases early

---

## Test challenges for the sake of learning

    * Learning to develop never ends; there is always something new to learn
    * Organized curriculum like that from FCC is great, but what do you do once you have graduated?
    * Devise your own tests around a new topic you learning
      - These are like the bonfire challenges
      - Test-Driven Learning (https://www.youtube.com/watch?v=f6VpCVU1bIA)
      - Hone in on a topic you don't fully comprehend
      - Devise a test that covers a possible solution
      - Write the test code before you write your solution
    * Share your bite-sized learning opportunity with others
      - Could every camper be required to create a new advanced bonfire?
      - Eventually you'll have co-workers that could benefit from this fun way to transfer knowledge
      - You might be a team lead or in charge of interns someday, and testing puzzles could be a great way to break the ice on a core concept specific to your company

### Challenge Ideas

    1. Create a bonfire challenge based on a topic that the camper is not yet fully comfortable with
    2. Create a bonfire challenge based on a topic that they understand well

**Comment by brandenbyers** [comment]
I should also clarify that I do not currently have time commitment to create these challenges, but @QuincyLarson asked me to create a draft outline of potential coursework. I would, however, be happy to lead and/or assist with this project when others become available to implement it.

**Comment by QuincyLarson** [comment]
@brandenbyers thank you for this comprehensive list of challenge ideas and concepts that we can introduce en route. 

The next step is coming up with a sequence of challenge titles. I find that titles can encapsulate a lot of what will be taught by a challenge, and are much faster to come up with than the full challenge.

@brandenbyers I will try to find a contributor interested in synthesizing your points into a sequence of challenge titles. If you do have time and this is something you'd be interested in helping with, we'd welcome your expertise (since you know the subject matter better than any of us).

**Comment by brandenbyers** [comment]
I'll start looking around at what other titles you have for challenges and see if I can come up with some specific ones. In the meantime, please do try to find someone(s) that is able to spend more time on this.

In my estimation, currently I can do more to facilitate others developing these challenges. I can jump in to help others more frequently than I can set aside a larger chunk of time to work exclusively on these (hence the delay on getting this outline submitted). But this is a super important topic and one that often seems to get taught way too late or not at all which can lead to bad habits and a lack of test responsibility, so I would like to help in any capacity that I can.

Also, anyone that is willing to contribute to these challenges need not have specific knowledge of any of this stuff (I didn't know anything about testing when I started writing Bonfires). If you can find people with time and enthusiasm, I can provide them on-going direction.

**Comment by QuincyLarson** [comment]
Issue merged into https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44
