### ISSUE TITLE
Time Calculator (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#232]
Create project from the Python scientific computing certification.

**Comment by scissorsneedfoodtoo** [comment]
Project prototype: https://repl.it/@BeauCarnes/fcc-time-calculator

**Comment by borntofrappe** [comment]
The README and especially the examples do a great job at introducing the project. 

Regarding the section dedicated to the assignment, it ends with the following line

> The unit tests for this project are in test_module.py.

I was wondering if the sentence should be moved in the section dedicated to testing the project.

**Comment by Wahe3bru** [comment]
The README.md file, just below the codeblock in Assignment. The line:  

> Assume the start times are valid times.

" Assume **that** the start times are valid times." might be better.

otherwise instructions are clear and tests passed with no issues.

**Comment by adamdune** [comment]
The `README` is clear and concise. And I liked the project. 🎆 

I only have a couple of nitpicks for your consideration:

1. > The minutes in the duration time will be 60 or less, but the hour can be any whole number.
This line seems to imply that the duration time's minutes could be 60 (example: 2:60).

2. I found this project to be significantly easier than the `Arithmetic Formatter`. I guess the order of the projects here is likely not final. So, maybe the difficulty of the project can be factored into the final order of the project 😃.

**Comment by beaucarnes** [comment]
Thanks everybody. I've implemented most of the suggestions.

**Comment by rgroves** [comment]
Minor grammatical issue—need space between between "less" and "than" in the last sentence of the assignment description.

> The minutes in the duration time will be **lessthan** 60, but the hour can be any whole number.

**Comment by scissorsneedfoodtoo** [comment]
Great catch @rgroves. I've fixed it over in the main project here: https://repl.it/@freeCodeCamp/fcc-time-calculator

**Comment by mramire6** [comment]
I liked the project a lot. Thanks for inviting me. My comments below.

From the README
> The minutes in the duration time will be less than 60, but the hour can be any whole number.

The minutes in the duration time are also whole numbers, but the way the sentence is written makes it seem like only the hour is.

**Comment by scissorsneedfoodtoo** [comment]
@mramire6, thanks for your input. I agree that the wording there could be a bit confusing. Perhaps it could read: "The minutes in the duration time will be a whole number less than 60, but the hour can be any whole number."

Do you think that sounds better? Or is there an alternative that you can suggest?

**Comment by mramire6** [comment]
I think that reads well.

**Comment by scissorsneedfoodtoo** [comment]
@mramire6, thank you for your patience.

I went ahead and updated that sentence in the [main project](https://repl.it/@freeCodeCamp/fcc-time-calculator) based on your input. Thanks again for your help making the instructions as clear as possible.

**Comment by jdelarubia** [comment]
Fun project in which we need to manipulate dates as strings.
I coded a few extra validation tests in the file `test_extra.py` to prove my solution since I noticed that although I was getting green tests, the logic of my 'add_time()' function was faulty when I was trying some other inputs.
[Link to my solution](https://repl.it/@jdelarubia/02-fcc-time-calculator)

**Comment by scissorsneedfoodtoo** [comment]
@jdelarubia, thanks for your input. Could you describe some of the false positives you got with your original code? We may be able to add some of your tests to `test_module.py` to prevent the same thing from happening to other learners.

**Comment by jdelarubia** [comment]
Hi Kristofer, My issues were on edge cases. I updated my code and my extra `test_extra.py` file to include as much of these cases. Even now, I still get 2 cases wrong so my code is not complete (although it passes the specification).
I'll give you a few examples of the edge cases I mean.
1:59 AM + 0:01 = 12 PM
1:59 PM + 0:01 = 12 AM
10 AM + 24:00 = 10 AM, and its counterpart with PM
10 PM + 0:00 = 10 PM, and its counter with AM
... and things of this nature.
Thank you for your interest.

**Comment by scissorsneedfoodtoo** [comment]
@jdelarubia, great, thank you for including those tests. Even though this is only the second project in the Scientific Computing with Python section, we may want to include a couple of those tests just to make sure the student's code is working properly.

Seems like some people don't consider 0 to be a whole number, so we may need to modify the description to read something like: 

"The minutes in the duration time will be an integer less than 60, but the hour can be any integer."

What do you think @beaucarnes?

**Comment by mramire6** [comment]
When I was writing my initial comment I debated with myself quite a bit on which term might be clearer and correct to use: integers or whole numbers. The issue with using the term integers is that it includes negative values. Since the exercise seems to want to add time (and not subtract it), including the term integers might be confusing to some learners who expect a negative value as a test case.

I think the instructions are correct to specify whole numbers. Alternatively, you could say non-negative integers to mean the same thing.

**Comment by scissorsneedfoodtoo** [comment]
@mramire6, that's a very good point about integers including negative numbers. Thank you for pointing that out -- we definitely don't want to suggest that the calculator should also subtract time. 

I think you're right, we should stick with whole numbers rather than non-negative integers. It might be overkill, but maybe the description could read "The minutes in the duration time will be a whole number from 0 to 59, but the hour can be any whole number including 0."

**Comment by beaucarnes** [comment]
After some quick Google searching, it seems like everyone that 0 is a whole number. So I'm not sure we need to specify "but the hour can be any whole number _including 0_."

**Comment by mike-lloyd03** [comment]
There's some issues with the UnitTests giving bad feedback. It looks like some of the test times were changed but not in the msg argument:

```python
def test_two_days_later(self):
        actual = add_time("11:59 PM", "24:05")
        expected = "12:04 AM (2 days later)"
        self.assertEqual(actual, expected, 'Expected calling "add_time()" with "2:59 AM", "24:00" to return "12:04 AM (2 days later)"')
```

the assertEqual msg argument should read:
```python
'Expected calling "add_time()" with "11:59 PM", "24:05" to return "12:04 AM (2 days later)"'
```

**Comment by mike-lloyd03** [comment]
Also, similar inconsistencies on:

```python
def test_two_days_later_with_day(self):
    actual = add_time("11:59 PM", "24:05", "Wednesday")
    expected = "12:04 AM, Friday (2 days later)"
    self.assertEqual(actual, expected, 'Expected calling "add_time()" with "2:59 AM", "24:00", "Friday" to return "12:04 AM, Friday (2 days later)"')
```
(Similar to error shown in previous comment)

```python
def test_high_duration_with_day(self):
    actual = add_time("8:16 PM", "466:02", "tuesday")
    expected = "6:18 AM, Monday (20 days later)"
    self.assertEqual(actual, expected, 'Expected calling "add_time()" with "8:16 PM", "466:02", "Tuesday" to return "6:18 AM, Monday (20 days later)"')
```
(The day in the msg should be `tuesday` not `Tuesday`)

**Comment by robertue1** [comment]
Hi there guys! Here is my solution to this problem

[time_calculator_@robertue1](https://repl.it/@robertue1/fcc-time-calculator#time_calculator.py)

**Comment by manshul1807** [comment]
Hi, 

Please find my solution. It was a fun simple project. Have to think of completing exceptions one by one.

Link : https://repl.it/@ManshulArora/time-calculator

**Comment by beaucarnes** [comment]
@ mike-lloyd03 Thanks for catching those. I just updated the tests.

**Comment by manshul1807** [comment]
Had fun completing this project and got more confident in oop.
Personally I felt making chart tough. 
Link : https://repl.it/@ManshulArora/budget-app

**Comment by salasy** [comment]
@mike-lloyd03  Great that you pointed out the problem with the feedback, it made it a lot easier.

I have noticed that when we get used to using modules, even simple tasks like this become a challenge ...... a very fun challenge.
Link to my solution:
https://repl.it/@sasakr/fcc-time-calculator#time_calculator.py

**Comment by borntofrappe** [comment]
I revisited the project at the [new URL](https://repl.it/@freecodecamp/fcc-time-calculator), and have but a few notes on the updated version.

## time_calculator.py

The starter code has the function return a variable which is never initialized. Perhaps it is better to have the `return` statement refer to the start time.

```diff
-return new_time
+return start
```

The function should also accept an optional argument, but perhaps it is better to have campers fill in the necessary parameters.

```py
def add_time(start, duration, day_of_week=None):
```

## README.md

I hope I'm not too forward, but I've edited [the README in my fork](https://repl.it/@borntofrappe/fcc-time-calculator#README.md). I've updated a few sentences, but mostly the structure of the document. The idea is to arrange the instructions into sections, and following the template of the first project.

- assignment
- examples
- rules

I've also added explicit mention of how the day of the week should be separated with a comma `,`.

---

### Assignment

Write a function `add_time` that specifies the following parameters:

* a string describing the start time in a 12-hour clock. For instance: `3:00 PM`, `11:30 AM` 
* a string describing the duration time with the number of hours and minutes. For instance: `3:10`
* (optional) a string describing the day of the week for the start time. This value is case insensitive, so expect strings like `Monday` and `tueSday` alike

The function should add the duration to the start time and return the end time.

### For example

Pay close attention to the spacing and punctuation of the results.

```py
add_time("3:00 PM", "3:10")
# Returns: 6:10 PM

add_time("11:30 AM", "2:32", "Monday")
# Returns: 2:02 PM, Monday

add_time("11:43 AM", "00:20")
# Returns: 12:03 PM

add_time("10:10 PM", "3:30")
# Returns: 1:40 AM (next day)

add_time("11:43 PM", "24:20", "tueSday")
# Returns: 12:03 AM, Thursday (2 days later)

add_time("6:30 PM", "205:12")
# Returns: 7:42 AM (9 days later)
```

### Rules

The function should return a string following these rules:

* if the end time describes the following day, it should return the end time followed by `(next day)`
* if the end time describe days after, it should return the end time followed by `(n days later)`, where "n" is the number of  days after
* if the function is called with the day of the week (optional), it should return the day of the week for the end time. The day of the week should appear after the time and before the number of days later. Separate the day with a comma `,` and format the string to be capitalized (lowercase, except for the first letter)

Refer to previous examples above to see how the output should look like.

Assume that the start times are valid times. For the duration, the minutes are described by a whole number less than 60, but the hours can be any whole number. 

Do not import any Python libraries.

---

Again, I hope it's not too forward to suggest these edits, and hope you'll find some value. Let me know if you need further input 👍

**Comment by kelvinho1234** [comment]
https://repl.it/@kelvinho1234/boilerplate-time-calculator#time_calculator.py

here is my solution. it is very challenging for new learner

**Comment by NikolaVlat** [comment]
Hey folks, am I just lacking some sleep or should '11:59 PM' + '24:05' return '0:04 AM (2 days later)' not '12:04 AM (2 days later)'.
11: 59 PM is a minute before midnight, so clock goes back to 0:00 after that not 12:00.
