### ISSUE TITLE
Applied Quality Assurance Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#24]
We are seeking a camper to be in charge of coordinating the creation of these challenges. 

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

We still need to come up with a list of concepts to cover, where each topic can be taught interactively, then translate these concept into the names of the challenges.

**Comment by erictleung** [comment]
https://en.wikipedia.org/wiki/Software_quality#Measurement

**Comment by QuincyLarson** [comment]
Issue merged into https://github.com/FreeCodeCamp/CurriculumExpansion/issues/44
