### ISSUE TITLE
Port Scanner (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#243]
Create project from the Python information security certification.

**Comment by scissorsneedfoodtoo** [comment]
Project prototype: https://repl.it/@BeauCarnes/fcc-port-scanner

**Comment by RaviTejaCMS** [comment]
Grammatical error in the Description
In the port_scanner.py file, ............... port_range is a list of two numbers indicating the first and last numbers of the range of ports **to be checked.**

**Comment by RaviTejaCMS** [comment]
I think these is a Grammatical error in the Description
I guess it should be

In the port_scanner.py file, ............... port_range is a list of two numbers indicating the first and last numbers of the range of ports **to be checked.**

**Comment by ArieRS** [comment]
https://repl.it/@ArieRS/fcc-port-scanner

Maybe, the readme is more clearly if you give en example of the parameter of  get_open_ports. Thanks

"In the port_scanner.py file, create a function called get_open_ports that takes a target argument and a port_range argument. target can be a URL or IP address. port_range is a list of two numbers indicating the first and last numbers of the range of ports to check. For example ("209.216.230.240", [440, 445]) or ("www.stackoverflow.com", [79, 82])."

**Comment by adamdune** [comment]
After reading the README, I got the impression that we should check the ports in the `port_range` including the last number.

However, once I completed this project and checked the solution. I found that the solution does not check the last number of the `port_range`. 

If the last number in the `port_range` is excluded on purpose, it should be clearly stated in the `README`.

**Comment by scissorsneedfoodtoo** [comment]
Thanks everyone for your review. We'll clean up the grammar and consider including examples of both the input and expected output in the README.

Good catch on the solution not checking the last port in the range @adamdune. I always forget that `range` is exclusive and missed that in my initial review. Keep in mind that the solution code will not be included when the projects are launched, though, and we hope for learners to account for that in their own code. Perhaps we should adjust one of the tests or include a new tests where the open port is the second number in the `port_range` list to account for this.

**Comment by erezhazan1** [comment]
https://repl.it/@erezhazan1/fcc-port-scanner

It wasn't clear to me if there is any need for input validation,
and if there is any special request for this as I started learning this topic I noticed that there are so many options to do it (but maybe it's only me..)

**Comment by beaucarnes** [comment]
I made a lot of the recommended changes. Thanks for your suggestions. 

@adamdune I updated the solution code so it checks every port in the provided range inclusive of both numbers. That was a mistake to not check the final number in the range.

@erezhazan1 We are not requiring input validation for this challenge.

**Comment by jdelarubia** [comment]
Clear instructions (by the time I got here). [Link to my solution](https://repl.it/@jdelarubia/fcc-port-scanner).
Cheers!

**Comment by scissorsneedfoodtoo** [comment]
@jdelarubia, awesome, thank you for your input. Your solution looks great :+1: :+1:

**Comment by natea123** [comment]
Got stuck on socket.setdefaulttimeout() as I was not familiar with the socket package so staring at a blinking cursor after running had me confused if my tests were failing or the socket connection was failing. 

Other than that clear instructions and gave just enough info to get Googling around to learn about the socket package. 

[Link to solution](https://repl.it/@natea123/fcc-port-scanner)

**Comment by scissorsneedfoodtoo** [comment]
Great, thank you for your feedback @natea123 and for posting a link to your solution. I believe others have mentioned that `setdefaulttimeout()` threw them off as well. That might be something we can mention in the README to prevent learners from getting stuck.

**Comment by casraysa** [comment]
Hi there!

To solve this project, first I tried to get open ports list working and I left the verbose output for the final part.

I faced a similar problem to @natea123. I wasn't familiar with the socket package and, until I managed to deal with the socket timeout and closing the connection, I suffered a bit.

Once I got that part done, and I headed to create the verbose part. When I started to test the final code, I realized that I had assumed that all the ip addresses were correct, but it wasn't so. It took a bit to get it, but I knew that I had some detail missing.

However, I think that instructions are clear and sufficient. I also agree to give a hint about how to manage the socket connection time.  

I hope this feedback is helpful.

My solution below:
https://repl.it/@casraysa/fcc-port-scanner

**Comment by GohEeEn** [comment]
Hi here, 

So when I was reading the comments here, it seems like we are not required to do input validation on parameter **target**. However, I found the following statements, that sounds the opposite.

![image](https://user-images.githubusercontent.com/34720382/88463249-5b03ec00-cea9-11ea-823e-29cdf745b1b9.png)

I wasn't sure if my understanding is correct, but what is the invalid URL and IP mean here ? Is it like no response from our request ? I thought we need to differentiate if the parameter **target** is having a URL and IP, in order to output different error message.
