### ISSUE TITLE
SHA-1 Password Cracker (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#244]
Create project from the Python information security certification.

**Comment by scissorsneedfoodtoo** [comment]
Project prototype: https://repl.it/@BeauCarnes/fcc-brute-force-password-cracker

**Comment by RaviTejaCMS** [comment]
Probably a Typo in the 3rd Paragraph of the Description
I assume this 
'NOT of a password in the database, return "NOT IN DATABASE".'
should be this
'NOT of a password in the database, return "PASSWORD NOT IN DATABASE".'
with reference to given test cases.

**Comment by ArieRS** [comment]
https://repl.it/@ArieRS/fcc-brute-force-password-cracker?lite=&classroom_template=&outputonly=&fileName=

Yes, @RaviTejaCMS has already discussed the typo in the readme. And  one more input from me to provide a link that can be read by the user regarding the use of the hashlib.

**Comment by adamdune** [comment]
I really liked this project 👍 , great job. 
It's simple, yet teaches some valuable background information about password security. 

I agree with @ArieRS. The only confusing part for me was using the hashlib library. So the docs can provide some pointer or a link to a good explanation on its usage.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for catching that typo @RaviTejaCMS. We will definitely update that before launching. Also, good call on including a link to `hashlib` in the README. It's worth mentioning there since it's imported into `password_cracker.py` by default.

**Comment by beaucarnes** [comment]
@ArieRS & @adamdune:
Thanks for the suggestions. I implemented them in the code.

**Comment by jdelarubia** [comment]
Awesome project, I liked very much. Here is the [link to my fork](https://repl.it/@jdelarubia/fcc-brute-force-password-cracker).

I noticed the tests fail when the function calls are chained, like
```
hashed_word = hashlib.sha1(word.rstrip().encode())
```
Instead, I needed to split the calls in 2 lines.
```
word = word.rstrip()
hashed_word = hashlib.sha1(word.encode())
```

**Comment by scissorsneedfoodtoo** [comment]
Thanks for your feeback @jdelarubia.

I took a look at your solution and agree -- it is a bit strange that you can't chain `.encode()` to `.rstrip()`. As far as I can tell, strings in Python are immutable, so string methods should return a new string. 

Not sure why your original code doesn't work. Glad you were able to find a solution in the end.

**Comment by casraysa** [comment]
Hi there!

This project was very interesting and good fun. Instructions and the help link were useful and clear. I didn´t find any misunderstanding or problem to solve it.

Solution code below:
https://repl.it/@casraysa/fcc-brute-force-password-cracker
