### ISSUE TITLE
Learn Unit Testing by Writing Tests for an E-Commerce Site

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#246]

**Comment by Twaha-Rahman** [comment]
@beaucarnes I am really excited about the FCC v7 curriculum and would love to contribute to it. But I have some questions about this project that needs to be cleared before I can start - 

1) Is this going to be a full stack E-commerce site?

2) We are using Jest for Unit testing, right?

I'm looking forward to your reply!
