### ISSUE TITLE
Learn Functional Testing by Writing Tests for an E-Commerce Site

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#248]

**Comment by Twaha-Rahman** [comment]
@beaucarnes I am really excited about the FCC v7 curriculum and would love to contribute to it. But I have some questions about this project that needs to be cleared before I can start - 

1) Is this going to be a full stack E-commerce site?

2) Are we going to do testing with Jest, Mocha and Chai for Unit Testing, Integration Testing and e2e testing?

3) If we are doing e2e testing, we'll we be using Cypress?

I'm looking forward to your reply!
