### ISSUE TITLE
American / British English Translator (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#251]
Create project from the quality assurance certification.

**Comment by scissorsneedfoodtoo** [comment]
Solution: https://glitch.com/~youthful-grave-scabiosa

**Comment by TevaHenry** [comment]
This project is really well done.

- The documentation is thorough enough.
- Inclusion of DOM manipulation.
- There is more of a focus on writing tests (than current projects in the curriculum).

A minor change, especially for non native english speakers, could be to add a comment on the different word sets (e.g. as shown in attached screenshot).

![wordlist-comments](https://user-images.githubusercontent.com/35941084/81472378-d8757400-924b-11ea-8ba2-fd3aff72f9f5.png)

**Comment by gulshansainis** [comment]
The project requirements are very clear and test cases cover the requirements pretty well.
We should encourage the person to write test first. It is possible to submit the solution even if we do not write any tests.

**Comment by scissorsneedfoodtoo** [comment]
Thank you for taking a look at this project and for your suggestions @TevaHenry and @gulshansainis. I like the idea of adding the comment for the different word sets. I'll make sure to add that to the boilerplate and solution now.

Yes, that's unfortunately a problem with a lot of the new projects and a handful in the current curriculum -- we aren't able to ensure that all tests pass or that the project meets all user stories, so they function on the honor system. I like the idea of encouraging learners to write the test cases first like you mentioned, @gulshansainis. We could probably make that the first user story for all the projects in the Quality Assurance section.

Were either of you able to build this project? If so, please let us know what you think about the difficulty and the current user stories. Any feedback would be greatly appreciated.

**Comment by TevaHenry** [comment]
I have completed the project, @scissorsneedfoodtoo.
Given the student follows the freeCodeCamp curriculum in order, this project is quite feasible. As you have a clear sense of what you should be doing throughout the project, I would have it as one of the first projects from the certification to build confidence.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for taking the time to build the project and for your valuable feedback, @TevaHenry. It's great to know that you think it's appropriate for students at this point the curriculum. We'll certainly consider rearranging the projects for this certification so this is one of the first projects and helps build confidence like you mentioned.

**Comment by julieg18** [comment]
Great project! I had a lot of fun, and it was really well made. The only issue I had difficulty with was with the unit tests. My code was working perfectly but the unit tests failed due to a function that didn't work in NodeJS, but worked fine browser side.

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Thanks for your feedback @julieg18. Could you share your solution? I'm curious about the function you mentioned. It's possible that other campers will run into similar issues.

After a meeting the other day, we decided to increase the difficulty of this project slightly. We're thinking that we should require the translator to handle quotations ("..." vs '...'), titles (Dr. vs Dr), and maybe the Oxford Comma. What do you all think of that?

**Comment by julieg18** [comment]
I was using `Object.fromEntries()` but since that code doesn't work in node, I wrote my own function that did the same thing as `Object.fromEntries`. That would definitely up the challenge of the project! Sounds fun for me, but I'm not sure how it would feel for newer coders. Maybe you could make it optional, for the coders who want to challenge themselves more.

**Comment by TevaHenry** [comment]
> Awesome! Thanks for your feedback @julieg18. Could you share your solution? I'm curious about the function you mentioned. It's possible that other campers will run into similar issues.
> 
> After a meeting the other day, we decided to increase the difficulty of this project slightly. We're thinking that we should require the translator to handle quotations ("..." vs '...'), titles (Dr. vs Dr), and maybe the Oxford Comma. What do you all think of that?

I think this is a good idea. Given the current requirements, it wouldn't be a major rise in difficulty.

**Comment by scissorsneedfoodtoo** [comment]
@julieg18, that sounds like a great way to handle the problem. Surely much cleaner than the way I used multiple arrays to track different changes. That's a good point, we may try to make these things optional, or at least give very simple examples in the unit tests file.

@TevaHenry, awesome, glad you think it wouldn't make the project too difficult.

**Comment by scissorsneedfoodtoo** [comment]
@TevaHenry and @julieg18, I just updated the README and index.html with a could of new user stories. Could you take a look and let us know if everything looks good?

**Comment by TevaHenry** [comment]
@scissorsneedfoodtoo the additional user stories to accommodate the added difficulty are very well written. I think the project looks great.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thank you for confirming that @TevaHenry, and for all of your feedback.
