### ISSUE TITLE
Learn Python Basics by Building a Blackjack Game

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#252]

**Comment by chandu4ai** [comment]
Hi beaucarnes , waiting eagerly for the 2020 update. Can u tell me the how much work work has been completed for this thread(Learn Python Basics by Building a Blackjack Game). I want to contribute so if there is anything i can help you with just drop me a message or email to chandu.nsd@gmail.com

                   THANK YOU FOR THE HARD WORK
                                                                      HAVE A GREAT YEAR

**Comment by scissorsneedfoodtoo** [comment]
@random-bot, thanks for your patience and interest in this project. We're currently working on the required Python certification projects. Once we release those, we'll circle back around to these optional projects.
