### ISSUE TITLE
Learn Object Oriented Programming by Building a Minesweeper Game

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#254]

**Comment by hassaanp** [comment]
> This flow offers a better route to building the right understanding:
> Building Objects (using curly bracket notation and Object.create)
> Introduce functions to generate Objects
> In the curriculum, this is immediately introduced followed by the constructor, which, in my opinion, is not the logical progression. Instead, the curriculum should show how we can reduce code repetition by using functions to return objects.
> Introduce the Prototype Chain
> We discuss the cons of using the previous approach to create Objects, i.e the memory issue that results due to copies of methods in each instance. This logically introduces the need to pass methods by reference.
> Here is an example:
> 
> const animalMethods = {
>     eat: function(){console.log("nom nom nom")},
>     describe: function(){console.log(this.name)}
> }
> 
> const dog = Object.create(animalMethods);
> dog.name = "bingo";
> 
> dog.eat();
> This allows to introduce how the interpreter works, i.e it looks for the .eat method on dog, doesn't find it, looks a level up the prototype chain and finds it there in the animalMethods. We also get a chance to introduce how this lookup is done - allowing the student to build a better mental model. This then can be shown to resolve the memory problem introduced in 2
> 
> function animal (name) {
>     const newAnimal = Object.create(animalMethods);
>     newAnimal.name = name;
>     return newAnimal;
> }
> 
> const dog = animal("dog");
> dog.eat();
> This is true OOP in JS and the next progression is simply the automation part, i.e why new and class were introduced.
> 
> Introduce new
> Show the student how new keyword automates the linking part between the animalMethods and animal function. Here, we get a chance to show the property called prototype and why it was created.
> 
> Introduce class
> Builds upon new and solidifies the understanding of underlying automation. Also, introduce constructor.

This is a suggested flow for teaching OOP mentioned in #38365
