### ISSUE TITLE
Learn Concurrency by Building a Prime Number Generator [Python]

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#256]

**Comment by jean** [comment]
Is this going to cover `async`/`await` and the event loop libraries like [`anyio`](https://github.com/agronholm/anyio)?  Hope so! :grinning:

**Comment by scissorsneedfoodtoo** [comment]
Thanks for the suggestion @jean. We'll look into that once we start working on these optional projects.
