### ISSUE TITLE
Learn Basic NumPy by Creating and Manipulating Arrays

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#257]

**Comment by fheld** [comment]
I would be interested in helping with this project.

**Comment by scissorsneedfoodtoo** [comment]
@fheld, thanks for your patience and your interest in this project.

We're currently working on the required Python certification projects. Once they're released, we'll circle back around to these optional projects.

**Comment by julien-aw** [comment]
I would be interested in helping with this project too
