### ISSUE TITLE
Cat and Dog Image Classifier (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#268]
Create project from the Python machine learning certification.

**Comment by chakradhar123** [comment]
I completed this project and it took me about 3 hrs. I was stuck at the test_data_gen in the beginning and rest went smoothly. It was a nice practice for me as I recently learned CNN and TensorFlow.I suggest some **corrections/improvements**:-


**1)**containng->containing
![image](https://user-images.githubusercontent.com/42428956/76168498-55299a80-6196-11ea-8ab0-2851abfdb301.png)
**2)**karas->keras
![image](https://user-images.githubusercontent.com/42428956/76168509-6a9ec480-6196-11ea-934d-e43e2a91b32c.png)
**3)**rount->round
![image](https://user-images.githubusercontent.com/42428956/76168517-8609cf80-6196-11ea-9697-e0378e30953e.png)
i
4)mention at the begening if we can tweak values of epochs,batch size,etc
5)give some hint at the begining for test_data_gen like for example: (hint:-observe the directory structure)

**Comment by scissorsneedfoodtoo** [comment]
@chakradhar123, thanks for catching those typos! We'll go in and fix them as soon as possible.

Your third and fourth points might make things a bit more clear for people working through this project. What do you think @beaucarnes?

**Comment by beaucarnes** [comment]
@chakradhar123 Thanks for your input. I have updated the project to include all of your suggestions.
