### ISSUE TITLE
Book Recommendation Engine (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#269]
Create project from the Python machine learning certification.

**Comment by lefthand3r** [comment]
I started this project about an hour ago and can say for now that the start is very unintuitive since there is a lot of mingling needed with the format of the CSVs (iso-encoding, headers, c parsing errors, delimiters etc) 
IMHO it would make sense to give some hints concerning the reading

**Comment by beaucarnes** [comment]
@maikroservice Thanks for this advice. I updated the project so the file reading and parsing code is given. If you have time, it would be great to get your input on the rest of this project.
