### ISSUE TITLE
Neural Network SMS Text Classifier (Certification Project)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#271]
Create project from the Python machine learning certification.

**Comment by rahls77** [comment]
I am getting the following error when trying to run the imports in the first cell:
<img width="1562" alt="Screen Shot 2020-02-11 at 5 12 37 PM" src="https://user-images.githubusercontent.com/59658917/74284475-cd18b800-4cf1-11ea-8fce-c10322b34279.png">

**Comment by beaucarnes** [comment]
@rahls77 If you run the [solution code](https://colab.research.google.com/drive/1mJjwgUMeI2PPoPaTXf6cLEz9Fn88MnTf), do you get errors on any of the other cells?

When I looked at your screen, it looks like a few of those errors are fixed in the lines after the errors. For instance, one of the errors shown is that "you'll have gast 0.3.3 which is incompatible". If you look a few more lines down it shows that a possible incorrect version of gast is uninstalled and a correct version of gast is installed. So if the rest of the cells in the solution code run fine, I don't think you have to worry about those errors.
