### ISSUE TITLE
Learn SQL by Building a University Database (Crash Course)

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/CurriculumExpansion#272]

**Comment by Manish-Giri** [comment]
I have some DB background, I'll be interested in helping build this. (There's no 'help-wanted' label here, so not sure if you needed someone working on this).

**Comment by sudhirdontha72** [comment]
@beaucarnes , I will be happy to help and contribute to the same repo in case if this issue is still open.
Please feel free to drop a comment here.

Thank you!
Stay safe :)
