### ISSUE TITLE
Add QA and Security User Stories to Voting App Project

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#28]
Here are the current user stories for our voting app project:

User Story: As an authenticated user, I can keep my polls and come back later to access them.
User Story: As an authenticated user, I can share my polls with my friends.
User Story: As an authenticated user, I can see the aggregate results of my polls.
User Story: As an authenticated user, I can delete polls that I decide I don't want anymore.
User Story: As an authenticated user, I can create a poll with any number of possible items.
User Story: As an unauthenticated or authenticated user, I can see and vote on everyone's polls.
User Story: As an unauthenticated or authenticated user, I can see the results of polls in chart form. (This could be implemented using Chart.js or Google Charts.)
User Story: As an authenticated user, if I don't like the options on a poll, I can create a new option.

We want to add some testing and security-related stories to this challenge (and perhaps remove some of the existing challenges to keep this project from becoming too time consuming).

Once we add these stories, we need a working demo with stories that require tests like those taught in our QA section (https://github.com/FreeCodeCamp/CurriculumExpansion/issues/24) and stories that cover at least one security concern covered in our upcoming security section (https://github.com/FreeCodeCamp/CurriculumExpansion/issues/25)

**Comment by alayek** [comment]
@QuincyLarson do we have any plans of verifying the app when the camper submits the link (say, link to a Heroku deployment)?

There are two ways I imagine this could be done:
- use REPL to send some requests to the link and run a test suite. The test suit can be written in Python with core `urllib3`, because REPL doesn't yet support Node JS.
- providing users a skeleton project, with the tests for user-stories in it (could be some Phantom JS tests).

**Comment by QuincyLarson** [comment]
@alayek Yes - we are considering ways we could verify this. For now we will just stick with the "honor system." I agree that Phantom JS test or hitting specific end points would be really well suited to testing these apps.

**Comment by QuincyLarson** [comment]
Closing for now - we will worry about this once we settle higher-priority issues.
