### ISSUE TITLE
Building a Julia Programming track 

### ISSUE THREAD

**Issue by logankilpatrick** [freeCodeCamp/CurriculumExpansion#285]
Hey all, is this the right place to start the discussion on how we (in the broader Julia community) can contribute a Julia Programming course? 

Thanks!

**Comment by scissorsneedfoodtoo** [comment]
Hi @logankilpatrick, thanks for your patience.

This repo is a place for developing the planned updates to the freeCodeCamp curriculum. We're currently working on incorporating Python certifications and moving to a project based curriculum. Unfortunately we don't have plans to add Julia or other languages for the time being.

That said, we're always open to discussion. There was some talk about incorporating OpenCV into the curriculum last year. While we don't currently have plans for that, our suggestion to those contributors was to:

1. Create an in-depth article that covers the basics similar to this that can be published on Developer News
2. Turn that article into a video which could possibly be published on our YouTube page
3. Finally, we could look to turn that into an interactive project like the ones in this repo

Let us know what you think.
