### ISSUE TITLE
Problems with Solution

### ISSUE THREAD

**Issue by rayjohnson529** [freeCodeCamp/CurriculumExpansion#287]
The solution doesn't seem to result in the figure posted.

I am going to submit my results soon, but this seems like maybe an earlier draft of the starter problem?

I peaked at the solution to try to see how mine compared and copied the code and the resulting graph didn't match 'figure 1' - I believe the problem has something to do with the part using "fig, ax" (unless somehow I've made a major mistake).

In addition, the function in the solution doesn't match the name of the function in the problem provided (it changed from 'draw_factor_plot' to 'draw_cat_plot.')

The instructions call for us to include the 'overweight' column we created, but 'Figure_1' does not include the 'overweight' column.

The test also calls for 'draw_factor_plot' - perhaps this is all on me... 
Will do a more thorough write up once challenge is completed.

**Comment by scissorsneedfoodtoo** [comment]
@rayjohnson529, thanks for your patience and your feedback.

I'll close this for now, but please let us know how everything's going in the [issue for this project](https://github.com/freeCodeCamp/CurriculumExpansion/issues/238).
