### ISSUE TITLE
Add REST, GraphQL, and RPC to curriculum?

### ISSUE THREAD

**Issue by brillout** [freeCodeCamp/CurriculumExpansion#288]
Hi!

API creation is something many beginners do wrong.

For example, nowadays, many default to GraphQL although creating ad-hoc Node.js/Express controllers is most of the time just fine. GraphQL is nice and it's good to know about it but it shouldn't be the default choice.

There are many valuable lessons to teach in this area.

Would adding REST, GraphQL, and RPC to the curriculum be of interest?

I'm the author of an RPC implementation called [Wildcard API](https://github.com/reframejs/wildcard-api#readme).

**Comment by scissorsneedfoodtoo** [comment]
Hi @brillout, thanks for your patience.

This repo is a place for developing the planned updates to the freeCodeCamp curriculum. We're currently working on incorporating Python certifications and moving to a project based curriculum. While some of our new projects will focus on developing an API, we don't currently have plans for GraphQL yet.

That said, we're always open to discussion. There was some talk about incorporating [OpenCV](https://github.com/freeCodeCamp/CurriculumExpansion/issues/209) into the curriculum last year. While we don't currently have plans for that, our suggestion to those contributors was to:

1. Create an in-depth article that covers the basics similar to this that can be published on Developer News
2. Turn that article into a video which could possibly be published on our YouTube page
3. Finally, we could look to turn that into an interactive project like the ones in this repo

Let us know what you think.
