### ISSUE TITLE
Learn Basic React by Building a Quiz App

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/CurriculumExpansion#302]

**Comment by Sky020** [comment]
Hey @scissorsneedfoodtoo , is this project up for grabs? Or, is there something more urgent this side of the platform could use work on?

**Comment by scissorsneedfoodtoo** [comment]
Hi @Sky020, thanks for your patience and your interest in this project. 

I talked with @RandellDawson and we decided that we could use some help on the Responsive Design section. If you don't mind, give us a few days to discuss this and we'll have some options for projects/prototypes you can take.

**Comment by saeedtlb** [comment]
Hi @scissorsneedfoodtoo , How can I help on this issue??

**Comment by scissorsneedfoodtoo** [comment]
Hi @saeedtlb, thank you for your interest in helping with the curriculum.

Currently we're doing a lot of the curriculum development for the front 3 (Responsive Web Design, JavaScript Algorithms and Data Structures, and Front End Libraries) in-house. Once we have a system in place and tooling to make it easier to contribute, we'll open things up again for volunteers.

You can follow our progress in our [chat server](https://chat.freecodecamp.org/), or on the [forum](https://forum.freecodecamp.org/).
