### ISSUE TITLE
Testing of music player app and fixing bugs

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#327]
There are couple of bugs that found in the music player project.

Here is one of them:
If you delete the first two songs in the list and then try to play the third song (which is now the first song in the list) it won't play and you'll get the following console error:

```
Uncaught TypeError: playlist[currentSong] is undefined
```

I want to do some more testing and find/fix any bugs left in the app.

**Comment by solution234** [comment]
I have tried to recreate the bug here:https://rebrand.ly/lub4f9a

**Comment by RafaelDavisH** [comment]
Should this issue be close now since we have the PR with a new prototype ? https://github.com/freeCodeCamp/CurriculumExpansion/pull/338

**Comment by jdwilkin4** [comment]
@RafaelDavisH 

I linked the issue with the PR so it will close automatically when it gets merged.
