### ISSUE TITLE
Add some sort of challenge that requires using cookies and the cookie-parser module (Backend)

### ISSUE THREAD

**Issue by Redrield** [FreeCodeCamp/CurriculumExpansion#33]
I think that something that people should be getting taught, either with a lesson, or with an expansion upon learnyounode or expressworks, is how to work with cookies in node.js. This is something that becomes more important if they want to have content locked behind a custom authentication service (Not using oauth) and need persistence of identity

**Comment by QuincyLarson** [comment]
I'm closing this issue and adding it as a note to the back end challenges issue https://github.com/FreeCodeCamp/CurriculumExpansion/issues/26
