### ISSUE TITLE
swap picasso project with piet mondriaan project

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/CurriculumExpansion#335]
Here is live URL: https://piet-mondriaan.netlify.app/
Here is the HTML: https://github.com/Sboonny/Piet_Mondriaan/blob/initial/state/Piet_Mondriaan/index.html
Here is the CSS: https://github.com/Sboonny/Piet_Mondriaan/blob/initial/state/Piet_Mondriaan/style.css

---

The painting is different from Picasso one, using position with it will be weird, and it can be based on grid system for responsive layout, instead of the old project.

If we are okay with a new project, then the intermediate CSS techniques will be around `grid`, making `template-rows/columns`, and how naming is hard for programmers, so it's currently faster and easier to create layout, using utility classes.

Here is the project: https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-intermediate-css-by-building-a-picasso-painting

**Comment by jdwilkin4** [comment]
Hey Team! 

I am going to go ahead and close this because it looks like this issue has already been resolved with the addition of the cat painting project.
