### ISSUE TITLE
Responsive Web Design Project: Pure CSS Tribute Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#35]
We are introducing a few new front end projects to give campers more experience working just with HTML and CSS before adding JavaScript to the mix.

Here are the agile use stories for this challenge:
1. I can view a tribute page with an image and text.
2. I can click on a link that will take me to an external website with further information on the topic.

We are looking for a volunteer who can build a working demo of this on CodePen using only HTML5 and CSS (no libraries). This should be simple and unambitious. We want the result to be in line with what a camper who's new to coding can realistically achieve themselves.

**Comment by ChaituVR** [comment]
@QuincyLarson I made changes to the previous Tribute page here https://codepen.io/ChaituVR/full/PzxGEb/ with out any library. and tried to be as simple as possible.. if any one could suggest some changes i would like to change them..

**Comment by QuincyLarson** [comment]
@ChaituVR beautiful. This is just what we needed. Thank you!
