### ISSUE TITLE
Image Search API Project - Update User Stories

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/CurriculumExpansion#38]
Should we use pagination or a query param specifying the **number of results**?

It's easier to test that the response has X number of results than to test the pagination. By simplifying testing for us, we can give better and more accurate feedback to campers. 
### Suggested user stories:
- **(Unchanged)** I can get the image URLs, alt text and page urls for a set of images relating to a given search string.
- I can request a specific number of results by adding the `?results=<a-positive-integer>` parameter to the URL.
- I can get a list of up to 10 of the most recently submitted search strings at the path `/latest`

**Comment by Rafase282** [comment]
A practical usage of the API with the new functionality would be to have a bot or script that gets **x** numbers of results for a query to display the images in an app, for example a dynamic gallery as opposed to have the specific page of results.
