### ISSUE TITLE
Should FCC's Example API Projects be private on hyperdev?

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/CurriculumExpansion#39]
## Keep them private because...
* If they were, the hyperdev-project's code would be hidden while keeping the example apps themself public - this could keep cheaters out.

## Keep them public because...
* Cheaters only cheat themselves.
* There will for example be some who benefit from reading the code to gain a deeper understanding or see different solutions

**Comment by Em-Ant** [comment]
If the rule **Don't look at the code** is still valid, I think they should be private.

@FreeCodeCamp/issue-moderators thoughts ? 
@QuincyLarson if it's OK for everyone, We can close this, and I'll make the projects private before the release.

**Comment by raisedadead** [comment]
> If the rule Don't look at the code is still valid, I think they should be private.

I agree to keep them private. Just to keep obvious cheaters at bay.

But just to keep the curriculum open, we need to have a separate repo, that has the code from these challenges. This will enable contributors to fix things if necessary. Of course we take care of hiding the env keys. Anyone submitting code from these repos would be smart enough to actually write code, which is kind of similar to point mentioned in the second part on the opening post.

**Comment by SamAI-Software** [comment]
If we keep example projects private, then we need to find a way to show campers the "right" clean code after they pass the challenge with their own code.
The reason is because we want to teach campers good practices of clean maintainable functional coding.

**Comment by raisedadead** [comment]
> If we keep example projects private, then we need to find a way to show campers the "right" clean code after they passed the challenge with their own code.
> The reason is because we want to teach campers good practices of clean maintainable functional coding.

This can be done after the submit the link to their challenge on Free Code Camp, by showing them the repo that we maintain.

On that note instead of having tens of repos, this can be one repo with subdirectories.

**Comment by SamAI-Software** [comment]
> On that note instead of having tens of repos, this can be one repo with subdirectories.

Then it make no sense to make example projects private to avoid cheating, because after the first submission campers will have a link with all the answers.

**Comment by raisedadead** [comment]
Yeah, I agree, with an open curriculum we can't have it both ways. 

Making the curriculum code private leaves us with a bunch of members to maintain them, so the curriculum code has to be open.

But having the project code themselves public leaves obvious cheaters in clear path of the code and for that matter even non cheaters being able to see the code even when they actually may not want to.

And thirdly as you say if we indeed want to encourage practice of unlocking the code after submission, it has to be as **subtle as possible** or not displaying the code at all.

As you can this is a clear UX problem. My suggestion is just a "hint like behaviour" at least UX wise. Although I am open for any alternates.

**Comment by Em-Ant** [comment]
Should we recommend(require?) to keep **camper's solutions** public, in order to review them ?

**Comment by SamAI-Software** [comment]
Vote: make example API projects on hyperdev **private**.

**Comment by SamAI-Software** [comment]
Vote: make example API projects on hyperdev **public**.

**Comment by raisedadead** [comment]
@Em-Ant For anyone to verify the code and get the certification it has to be public.

**Comment by Em-Ant** [comment]
@SamAI-Software a public project can be forked (aka *remixed*). Cheaters could have a working solution in about 3secs.

**Comment by SamAI-Software** [comment]
@Em-Ant the same like at codepen and all front-end challenges.

**Comment by Greenheart** [comment]
@raisedadead 
> even non cheaters being able to see the code even when they actually may not want to

**Comment by Greenheart** [comment]
@SamAI-Software 
> the same like at codepen and all front-end challenges.

Because of this, I think we should keep hyperdev projects public as well. It's too much work to prevent cheating at this time.

**Comment by raisedadead** [comment]
Yeah, that works. If unintentional code views can been incorporated. It's pointless to look into the hassle.
I think this can be closed as resolved, with projects being public and of course the ENV keys hidden

**Comment by Em-Ant** [comment]
So *PUBLIC* code ?
