### ISSUE TITLE
File Metadata API Project - Should it be moved to the Dynamic Web Application Projects?

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/CurriculumExpansion#41]
This project requires the user to work with either an HTML form or some JS in order to access the API. It's not possible to simply use an URL request.

Since this project is on the border to being a simple dynamic web application - maybe we should move it to those projects?

---

On the other hand, it's interesting to have an API where it's possible to `POST` to.
If we disregard the frontend parts - the backend works like an API so it could still fit after all.

Any thoughts?

**Comment by QuincyLarson** [comment]
@Greenheart My reasoning in including it in the API projects is the HTML necessary is quite minimal. If you want to help design a new purely back end API project, we could consider doing this.
