### ISSUE TITLE
How should we solve the CORS issue when testing API Projects?

### ISSUE THREAD

**Issue by Greenheart** [FreeCodeCamp/CurriculumExpansion#42]
## The problem

API project apps need to have CORS-headers enabled for the `freecodecamp.com` site to allow the FCC project pages to run tests.

This could be solved by using JSONP for the API-calls, but it's overly complicated for these simple projects. Additionally, CORS seems to be a more modern solution so we'd suggest to go with that.
### 1. User stories
- explain CORS to the campers, show links
- tell them to implement the CORS headers - to allow us to test their API
### 2. Provide a boilerplate for the API project which enables the CORS headers by default

``` js
/*
Example of comment provided in project boilerplate
Uncomment this middleware to make you API testable by Free Code Camp

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
  next()
})
*/
```
### 3. Add challenges to FCC explaining working with APIs (ping #27)
- Explain JSONP
- Explain CORS
- JSONP vs CORS - Explain when to use which solution
## Suggestion

Go with `3` - this is a fundamental web concept so it's important to know when doing frontend development.

**Comment by MayankPratap** [comment]
I think most of the standard APIs will have CORS enabled already so they will work on FCC as well.  Otherwise we can make our own APIs with access control : '*' .

**Comment by Greenheart** [comment]
@MayankPratap Yes, they do. 

I realized this was phrased unclearly - what we really mean with this issue is that the API projects that camper's create will need CORS enabled. The reason for this is to allow a page like for example `freecodecamp.com/<some-api-project>` to run tests against a camper's API project and then give them feedback on if they fulfil given user stories :blush:

**Comment by alayek** [comment]
@Greenheart this is a good question. Enabling CORS on your own API is going to help us test, yes.

But then, it comes with other risks for the camper building the API. Security, to begin with. So, camper has to implement rate limiting etc. on their API. By the time they apply for certificates, and our reviewer goes in and checks out their project - it could be down. Or slow.

This is why I have been interested in testing the API on server, using Python. Or any other language you think would do good. REPL does not support Node JS, otherwise I wold have considered that as well.

**Comment by QuincyLarson** [comment]
@Greenheart @Em-Ant @alayek Will this be necessary before campers start the API projects? If not, then I think @Greenheart's suggestion could be a challenge in the information security section. We could then remind them to enable it and point them to that challenge as a user story on each project (as a reminder - assuming they worked through these before they started the projects).

@Em-Ant could we add such a challenge at the end of the information security challenges? First we would have a challenge showing them what CORS is, then a challenge where they purposefully whitelist FCC.

What do you all think?

**Comment by Em-Ant** [comment]
If you want the API projects to be testable from FCC (or from some Hyperdev project like one of our testing prototypes), where the testing happens **in the browser**, on the results of an ajax call,  you need to have CORS enabled in the API projects. In our original ideas CORS was part of the express challenges (see #44 section 2).

**Comment by QuincyLarson** [comment]
@Em-Ant OK - what do you think would be best then? Should we enable CORS all the time so it's possible that campers could complete later challenges even if they skipped the Express CORS challenge?

**Comment by Em-Ant** [comment]
There are 2 options: 
1. Teach CORS in the 'base' express section, and add it as a user story. There is also a npm package called `cors` that does the work, you just need to require it.
2. Provide an API project boilerplate with CORS enabled by default, and ask the campers to build their APIs using it.

**Comment by QuincyLarson** [comment]
@Em-Ant OK - based on what you've said, we can do #2 and specifically instruct them to use the boilerplate with CORS enabled by default. That way we don't need to include it as a user story. I'm sure we'll think of other things down the road that should be included in this boilerplate, too, so having them start with a boilerplate is best.

@Em-Ant could you build a project boilerplate, associate it with the Free Code Camp HyperDev account, and link us to it here? Then I think we can close this issue.

**Comment by Em-Ant** [comment]
API boilerplate with CORS: https://hyperdev.com/#!/project/shimmer-ripper linked to the camperbot's account.
