### ISSUE TITLE
chore: add Learn Pseudo-classes workshops to frontend cert

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#421]
In this new frontend cert, we have module to go into more detail about pseudo classes and how the different ones work. The preceding lecture block will teach them about the different types of pseudo classes.

The cafe menu does introduced pseudo classes briefly here
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-basic-css-by-building-a-cafe-menu/step-91

But we will need a small workshop for campers to apply what they learned about pseudo classes in a step based tutorial.

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/css-projects` directory
- [ ] add your completed project(index.html and styles.css files) in that new folder

**Comment by larymak** [comment]
@jdwilkin4 same question on this, is it only the HTML and CSS or are the user stories needed too?

**Comment by jdwilkin4** [comment]
this is a workshop.
Workshops have a different format then labs.

Workshops are step by step projects like this
https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app

For the prototype, only the complete HTML and CSS should be supplied.
However, workshops aren't open ended in the same way as the labs are.

This means that everything in the HTML and CSS will need to be broken down into steps and tests
This differs from labs, which are more open ended projects with minimal guidance in user stories
