### ISSUE TITLE
chore: create prototype for vanilla js drum machine lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#461]
We need a lab for them to do on the audio constructor and its methods.
Here is the workshop they will do before this
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-string-and-array-methods-by-building-a-music-player/step-99

They will also know all of the fundamentals (strings, functions, objects, arrays, etc)
They will also know about higher order functions like map, filter, reduce.
And they will know DOM basics like getElementById, querySelector, querySelectorAll, click events, change events. 

## Acceptance criteria

- [ ] create a new folder of the project in the `frontend-cert/js-projects` directory
- [ ] add your completed project in an `script.js` file in that new folder
- [ ] create a markdown file for your proposed user stories. You should call it `user-stories.md` and place it in your new project folder

**Comment by jdwilkin4** [comment]
I feel like the drum machine project we have for the frontend libraries should work here

https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-drum-machine

**Comment by fhsinchy** [comment]
> I feel like the drum machine project we have for the frontend libraries should work here
> 
> https://www.freecodecamp.org/learn/front-end-development-libraries/front-end-development-libraries-projects/build-a-drum-machine

Yeah this one looks fitting but without using React.js right?

**Comment by jdwilkin4** [comment]
React hasn't been taught yet. 
so this is will need to be HTML, CSS and vanilla JS.
full curriculum order can be found on the sheet 👍
