### ISSUE TITLE
Automated Testing Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#48]
@em-ant is in charge of coordinating the expansion of these challenges, but he needs your help.

These challenges will walk campers through writing tests using the [Mocha Chai library's Assert methods](http://chaijs.com/api/assert/).

These challenges will run on HyperDev - not on FreeCodeCamp.com yet. @Em-Ant can fill you in on specific details of this, as he is our resident HyperDev expert.

Ideally, we'll cover all three types of tests: unit, integration, and functional. These are [described here](https://codeutopia.net/blog/2015/04/11/what-are-unit-testing-integration-testing-and-functional-testing/).

---
### Introduction :8ball:
- [ ] Why testing is important ?
- [ ] Testing approaches (TDD vs. BDD - see [this](http://joshldavis.com/2013/05/27/difference-between-tdd-and-bdd/)) & Interface styles
- [ ] Unit, Integration, e2e tests
- [ ] What is a _Test Framework_ ([mocha](https://mochajs.org/))
- [ ] What is an _Assertion Library_ ([chai.js](chaijs.com/))
#### Basic Assertions
- [x] `.isNull()` - `.isNotNull()`
- [x] `isUndefined()` - `isDefined()`
- [x] `isOk(truthy)` - `isNotOk(falsey)`
- [x] `isTrue()` - `isNotTrue()`
#### Equality
- [x] `.equal()` - `.notEqual()`
- [x] `.strictEqual()` - `.notStrictEqual()`
- [x] `.deepEquals()` - `.notDeepEquals()`
#### Comparisons
- [x] `.isAbove()` - `.isAtMost()`
- [x] `.isBelow()` - `.isAtLeast()`
- [x] `.approximately()`
#### Arrays
- [x] `.isArray()` - `.isNotArray()`
- [x] `.include()` - `.notInclude()`
#### Strings
- [x] `.isString()` - `.isNotString()`
- [x] `.include()` - `.notInclude()`
- [x] `.match()` - `.notMatch()`
#### Objects
- [x] `.property()`
- [x] `.typeOf()`
- [x] `.instanceOf()`
### API Integration Tests :construction:
- [ ] Test an API endpoint 1  (using [chai-http](https://github.com/chaijs/chai-http))
- [ ] Test an API endpoint 2
- [ ] Test an API endpoint 3
### Functional e2e Tests :construction:
- [ ] Setup the Headless browser ([Zombie.js](http://zombie.js.org/))
- [ ] Setup the _Test Suite_
- [ ] Test a form on the Homepage 1
- [ ] Test a form on the homepage 2

**Comment by Em-Ant** [comment]
@QuincyLarson  some API challenges may need user stories updating in order to improve testability e.g #38. If we want them to be remotely testable we need to have CORS enabled ( #42 ) in these projects.

**Comment by QuincyLarson** [comment]
@Em-Ant Thanks for pointing this out. I commented on that issue here: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/42#issuecomment-242954838

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! We've loaded these challenges into the seed files and plan to deploy them to beta as soon as possible. 

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
