### ISSUE TITLE
Angular Challenges

### ISSUE THREAD

**Issue by MaXwellFalstein** [FreeCodeCamp/CurriculumExpansion#5]
I think Angular 2.0 should be fully supported as it is a very good client side option in the MEAN stack.

MEAN & MERN should be fully supported in FCC.

I know you use MERN for FCC, but this does not mean MEAN should be left aside.

**Comment by QuincyLarson** [comment]
Hi @MaXwellFalstein we have chosen to focus on React with our core curriculum, but we also have an "expanded universe" of technologies we cover - mostly on our wiki at this point (which we are moving to our forum). Would you be interested in contributing some Angular 2.0 tutorials? You could interconnect them and have essentially the equivalent of an Angular curriculum on our wiki. We are doing this for technologies like Python.

**Comment by MaXwellFalstein** [comment]
Hi @QuincyLarson.
I am very interested in doing something like that for Angular 2.0.
I will do a little bit of research and have a go on a few mock tutorials.
What are the reasons for focussing on React?

**Comment by alayek** [comment]
@MaXwellFalstein React has a good community support and at this stage, more mature and popular than Angular 2.0. I know that popularity of a technology is not an indicator of how solid it is; but it does help our campers land relevant jobs.

As for Angular 2.0, I did try it out. Looks cool, but seems like they took everything from React (composition and components) and added TypeScript. I am yet to see how to bundle an Angular 2.0 app for production.

The form validation part is just too complex, with confusing constructs like `[{}]`. The biggest problem with Angular like frameworks is that once you write your codebase in Angular, it's hard to switch out later in lieu of a better technology. Same for Angular 2.

React does not have this issue. Think of it like a view rendering library, like jQuery, only better. You can choose to switch later easily, and you can also add it in small portions in your existing codebase, to rewrite some UI component.

Similarly, if you think of React Native, which has same syntax as React JS itself; but renders native Android-iOS components (unlike Cordova driven Ionic, which renders in a webview and you cannot do touch gesture stuff). Angluar 2.0, AFAIK, doesn't have anything equivalent.

To be frank, I didn't like Angular 2 gitter room either. They are not very helpful.

---

The above is my personal opinion on Angular 2.0. Feel free to correct me if I am wrong.
