### ISSUE TITLE
full page map view has independently scrolling sections

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#50]
The freecodecamp.com/map view has two independently scrolling sections. See screenshot below.

![](https://www.evernote.com/l/Ar8xomFYSOtK46k3wnqo7ZkhUb_F3IfxjhsB/image.png)

- As a user, when I scroll down - with mouse anywhere in the view - the map should scroll. Currently, I have to mouse over the central column.

- As a user, the top map navigation component should always remain fixed at the top (and not be scrollable like in the above picture).

**Comment by atjonathan** [comment]
@QuincyLarson, is this in the wrong repository?

**Comment by QuincyLarson** [comment]
@atjonathan yes. thanks for pointing this out. I'll open it on the right repository.
