### ISSUE TITLE
chore: update description for random background color changer lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#530]
For the random background color changer lab, we should make it more clear that this lab is different in that you are debugging and fixing broken code instead of creating a project from scratch.

So we should update the objective here so it is clearer what you should do

<img width="549" alt="Screenshot 2024-08-14 at 10 41 59 PM" src="https://github.com/user-attachments/assets/975eb8fe-aa3b-4108-a36e-b29b4c008896">

Maybe something like this?

```md
Camperbot is learning JavaScript and has tried to build their own Random Background Color Changer. However, they have made a few mistakes along the way.   Fulfill the user stories below and get all the tests to pass so the lab is functioning properly
```

Also the intro text should change here because technically they are not creating a project but rather fixing a project

<img width="639" alt="Screenshot 2024-08-14 at 10 47 44 PM" src="https://github.com/user-attachments/assets/5fd58d0e-8079-41ad-8006-29da2cc6ca80">

**Comment by Dario-DC** [comment]
What about the tile? Is it fine to keep "Build" or should it be "Debug a Random Background Color Changer"?

**Comment by zairahira** [comment]
I'll vote for "Debug" instead of "Build".

**Comment by jdwilkin4** [comment]
@Dario-DC 

Yeah, changing it to debug is fine
