### ISSUE TITLE
9/28 Update on Curriculum Expansion Effort

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#54]
I am writing this to status update our @FreeCodeCamp/issue-moderators and other contributors.
- I've imported almost all of the challenges.
- @HKuz is well on her way to QA'ing the non-back end challenges: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/52
- @Em-Ant is adding tests to all of the back end challenges, and is redesigning the back end projects so that all of their user stories can be tested programatically. Some of the Dynamic Web App projects may be considerably simplified as a result, by replacing some front-end focused user stories with user stories that emphasize testing and security. This will largely eliminate the need for code review on these projects.
- @BerkeleyTrue is working on the view and testing functionality for these back end challenges and projects.
- There are still a few topics that haven't been fully designed and imported yet:
  - [React](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/2)
  - [Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/3)
  - [React and Redux](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/4)
  - [Advanced Data Structures](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/17)
  - [ES6](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/34) 
- @t3h2mas is working on the React Challenges and @alayek is working on ES6. @erictleung is working on data structures. But they could use some help. Any volunteers?

Our plan is to first deploy our Curriculum Development branch to Beta, then keep working on it until it's ready.

This way, campers who are eager to try out these new challenges can do so and create issues while we continue the process of refining these challenges.

Our goal is to push all the changes at the same time to minimize confusion.

**Comment by stanleyyylau** [comment]
Awesome, can't wait to try out challenges on national holiday!

**Comment by Greenheart** [comment]
Great news! I'm unfortunately very busy at the moment but I wish the rest
of you good luck, keep this up! :smile:

torsdag 29 september 2016 skrev Stanley <notifications@github.com>:

**Comment by evan153** [comment]
yaaaaaaaaaaaaaaaaaaasssssss

**Comment by marhyorh** [comment]
I can assist @t3h2mas with the React Challenges

**Comment by IsaacAbrahamson** [comment]
I am almost done with front-end certificate, is there anyway that newer members like me who don't know react, redux, etc. can help out?

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson yes. The most logical place to jump in would be the [Advanced Data Structures challenges](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/17). If you want to research a data structure, then design a challenge around it, take a crack at these. I recommend starting in the Graphs section - as far as I know, no one has started work on that yet.

**Comment by ShwetaRajput** [comment]
Busy these days.. But will complete all the challenges

**Comment by evan153** [comment]
Did the beta ever get updated on Friday? I'm not seeing any difference. :sob:

**Comment by QuincyLarson** [comment]
@evan153 We still need to fix some bugs before we can push the new challenges to beta. Thanks for your patience.

**Comment by alayek** [comment]
@IsaacAbrahamson if you are interested in helping out, I can help you get started. Please drop me a line at [Gitter](https://gitter.im/alayek).

**Comment by mmhansen** [comment]
Does anyone have an example of how to write the tests for react challenges? 
I've used jsDOM and chai-jquery for emulating react rendering and events, but I'm not sure how it is done on FCC.

**Comment by IsaacAbrahamson** [comment]
@mmhansen I could use your help testing user stories:
https://github.com/FreeCodeCamp/CurriculumExpansion/issues/68

**Comment by atharvajava** [comment]
Hi , I can help if possible though i am not much sound and experienced as you all so if there is anything i can help on please do include me into this plus i am willing to learn anything new which comes in the way to help things.

Thanks

**Comment by HKuz** [comment]
@atharvajava that would be fantastic if you want to help out! There is a list of topics in the original post at the top that are not finished. If any of those interest you, click on the link (it will take you to the issue for that topic), and post there asking the topic owner how you can help out. Thanks! 🎉

**Comment by QuincyLarson** [comment]
@atharvajava you might be interested in contributing to our ES6 challenges: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/34

**Comment by atharvajava** [comment]
@QuincyLarson  @HKuz  whatever comes up i will take a look onto it and try to complete it if i am stuck somewhere i will try to get some idea over it with you guys. I will be looking over the issues as soon as i am back from work.
Thanks :)
