### ISSUE TITLE
New Front end libraries projects? 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/CurriculumExpansion#540]
**Context**

I was hoping that at some point we could replace the Bootstrap project with a TailWind project and potentially the jQuery one with a project that uses the `cash` library. 

We here at FreeCodeCamp are trying to migrate to Tailwind and it certainly wouldn't hurt to teach more about it. 

As for cash, there are still people using jQuery in the world. It may be a possible replacement,  though we can certainly try teach it and the vanilla JS equivalents like `document.querySelectorAll`. 

More about cash: https://github.com/fabiospampinato/cash

**Comment by jdwilkin4** [comment]
Hi @a2937 ! 

> I was hoping that at some point we could replace the Bootstrap project with a TailWind project and potentially the jQuery one with a project that uses the cash library.

So the new curriculum changes will no longer have the boostrap or jQuery challenges.
But we still want to be careful about swapping out one technology or project for another.

The approach in the past was to pick the most popular frontend tooling at the time and teach that in an interactive way.
While, I understand why that approach was made at the time, it does leave us in a situation now with outdated material.
But also, this doesn't send the correct message for what it really means to be a professional frontend developer.

The messaging shouldn't be only learn these 4-5 frontend tools and get a frontend developer job.
The messaging should be learn the core HTML, CSS, JS languages, known how to learn, and know how to read documentation to be a successful frontend dev.

We need to prepare campers for the realities of the job and they need to be able to bounce around to different technologies 
or they won't make it. 

So the new curriculum changes will take a more wholelistic approach to frontend libraries frameworks that will cover the following: 

- what are JS libraries and frameworks? (differences between library and framework, problems they solve, why they are used, etc.)
- What are css libraries and frameworks? (problems they solve, why they are used, etc.)
- What are CSS preprocessors and why are they used? (SCSS, etc)
- What are meta frameworks and why are they commonly used in the industry? (ex NextJS, etc)
- What are some tools to use to setup projects using a library or framework? (ex Vite, etc)
- What is dependency management and how does it work with JS libraries and frameworks? (ex npm, yarn, pnpm, etc)
- What are state management libraries and when should you use them? (Redux, Zustand, etc)

As for the interactive portions, we will still have projects for React and TypeScript in the step based approach.

But for other aspects like css libraries, frameworks, state management, etc. we are currently discussing having more opened ended projects, similar to the current cert projects.
