### ISSUE TITLE
chore: update cat photo app on main to use same ids

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#587]
As discussed in chat, the workshops and labs that are already in main with reuse the same ids.
So the cat photo app that is already in the frontend cert, will need to be updated to use the same ids

**Comment by ilenia-magoni** [comment]
wasn't the cat photo app in the new cert changed tho? I checked with a diffchecker https://www.diffchecker.com/h1DsJZE5/

Should I go through the cat photo app and find which steps match with the new one?
What about the changes discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/54767?

**Comment by jdwilkin4** [comment]
> wasn't the cat photo app in the new cert changed tho?

The only change was to removal the form steps. So it is a little shorter. Everything is else is the same.

> What about the changes discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/54767?

Yeah I was really hoping we were able to get a fix merged in and see what happens because I originally opened that issue back in May.
But unfortunately, we haven't had a successful PR go through.

Considering a lot of people are still struggling with step 12 we should make the suggested changes outlined in the issue.

**Comment by ilenia-magoni** [comment]
cat photo app in Responsive Web Design updated, now I will update the workshop and match the IDs
