### ISSUE TITLE
Minimalist example projects with tests: Random Quote Machine

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#59]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to redesign these projects to have user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

At the same time, we've heard feedback that campers are intimidated by the highly polished example projects we use. Instead of having fancy example projects, we should have minimalistic project examples that focus on functionality rather than appearance, animations, etc.

So we need:
- [x] New agile user stories with one automated test each (reply to this issue with the user stories and their tests)
- [x] Minimal example project that fulfills all of these user stories (reply with a link to CodePen)

The current project: https://www.freecodecamp.com/challenges/build-a-random-quote-machine

**Comment by Weezlo** [comment]
_Note: what is discussed below could apply to other projects. The produced code could be reused_

I've imagined a few tests and developped the corresponding automated unit tests for the Random Quote Machine project.

### How it works:
I created a new empty pen for the Random Quote Machine project https://codepen.io/Weezlo/pen/VKVvjk. 
This empty pen includes a new external script I created:  http://codepen.io/Weezlo/pen/ALmBPw.js ([and the corresponding pen](http://codepen.io/Weezlo/pen/ALmBPw)). It's the core of the testing system. Campers won't see it and won't touch it.
This external script embeds all the testing logic, as well as the UI for the test report.
Campers should start with/fork [this empty pen](https://codepen.io/Weezlo/pen/VKVvjk). Every time the pen is refreshed, the tests are executed. The camper can immediatly see if his quote machine matches the expectations.

### The unit tests i've imagined so far for the Quote Machine (these tests perfectly match the existing example project):
- [ ] The page must contain an element with `id="text"`. This element should receive the text of the quote.
- [ ] The page must initially display random text in the element with `id="text"` (within x seconds after page has loaded)
- [ ] The page must contain a button element with `id="new-quote"`. This button is used to fetch a new quote.
- [ ] When the button with `id="new-quote"` is clicked, a new quote appears in the element with `id="text"` (within x seconds).
- [ ] The page must contain contain a "tweet" button element with `id="tweet-quote"`. This button should be used to tweet the current quote.
- [ ] When the button with `id="tweet-quote"` is clicked, this should initiate a new tweet containing the text of the current quote. 
- [ ] \(Optional\) The page could contain a centered wrapper element with `id="quote-box"`
- [ ] \(Optional\) The wrapper div with `id="quote-box"` could be horizontally centered

### See those tests in action
Here is a fork of the original quote machine project example including those tests: http://codepen.io/Weezlo/pen/qaQEYm
You can try to make the tests fail by modifying or commenting stuff on the page (id values, function calls, ...).
NB: a 3 seconds delay is applied to the tests with remote calls, this is why the test suite takes ~8 seconds to finish. This 3 seconds delay can be adjusted.

### A few things to discuss:
- Should the test failures give more detailed information on what failed?
- The test on the tweet button just checks if the button's "href" property contains the string "twitter.com", is it sufficient? Is it a good kind of test to do in general ?
- The test system currently uses Mocha, Chai, Bootstrap and jQuery(modal window), and thus requires all these dependencies - already included in the aforementioned pen:  bootstrap(js/css), jquery(js), mocha(js/css), chai(js). Bootstrap was used to save time with the modal window containing the test report. A future version could remove the bootstrap dependency by manually coding this modal window. Removing Bootstrap would also remove the jQuery dependency. 
- I have a few other ideas i would like to implement. One of them would be to impose to the campers to identify their project by adding a special variable to their code (e.g `const project_name="random quote machine"`). This way, we could programmatically identify the project we're testing, have only one external javascript file containing all the tests for all the projects (and thus only one template pen) and execute only the tests for this project.

### So
What do you think about all of this ?
About this "external script system" ? 
What other tests could we add to this project in particular?

**Comment by QuincyLarson** [comment]
@Weezlo wow. Wow!

Thanks for your patience with my slow response. This is not for lack of enthusiasm, I was just busy with events the past two days.

First of all, this looks amazing, and I think as-is it will provide an excellent user experience for campers - much better than the untested experience.

Regarding your things to discussion, my opinions:
> Should the test failures give more detailed information on what failed?
The error messages seem clear to me. They are actually more detailed than the error messages on our algorithm challenges, in that they show the JavaScript error as well. So I don't think they need to be more detailed. I propose we use them as-is and if it becomes clear that campers want more direction, we can provide it.

> The test on the tweet button just checks if the button's "href" property contains the string "twitter.com", is it sufficient? Is it a good kind of test to do in general?
Yes - I think this is sufficient. We could actually test to see whether it contains the string "twitter.com/intent/tweet?" to make sure they are using the proper Twitter intent. If we did this, we would need to update the test copy to "The page must contain contain a "tweet" button element with id="tweet-quote". This button should use the "twitter.com/intent/tweet" path and tweet the current quote." This would double as a clue as to how to implement this, which is a Twitter-specific concept and not something we want them to spend a long time looking up. If they google this path, they will get https://dev.twitter.com/web/tweet-button/web-intent as the top link, which is the best documentation for how to do this.

> The test system currently uses Mocha, Chai, Bootstrap and jQuery(modal window), and thus requires all these dependencies - already included in the aforementioned pen: bootstrap(js/css), jquery(js), mocha(js/css), chai(js). Bootstrap was used to save time with the modal window containing the test report. A future version could remove the bootstrap dependency by manually coding this modal window. Removing Bootstrap would also remove the jQuery dependency.
I agree that it would be nice to remove this dependency. Perhaps this is something we can do later, when we move all of these tests from CodePen over to freecodecamp.com itself. (This may happen in 2016, but we could potentially roll out these new projects out much sooner.)

> I have a few other ideas i would like to implement. One of them would be to impose to the campers to identify their project by adding a special variable to their code (e.g const project_name="random quote machine"). This way, we could programmatically identify the project we're testing, have only one external javascript file containing all the tests for all the projects (and thus only one template pen) and execute only the tests for this project.
Yes - this would be better. Then campers could fork the exact same pen for everything. We could pre-populate the pen with commented-out challenge names and they could uncomment the one they're working on. This would minimize the likelihood of misspellings. 

Rather than try to add a lot of additional tests, I recommend we keep moving and our community will invariably come up with ideas for additional tests over time.

I think the best application of your scarce time would be to keep moving forward and building test suites for the other projects, and redesigning their user stories as necessary to make them testable like the ones on this project.

**Comment by Weezlo** [comment]
@QuincyLarson @no-stack-dub-sack 
The "Run again" button has been implemented in the master generic test script (http://codepen.io/FCC_test_suites/pen/qqmGXr). The tested Quote Machine example (http://codepen.io/Weezlo/pen/qaQEYm) now uses this new master test script.

Any feedback would be highly appreciated.

**Comment by QuincyLarson** [comment]
@Weezlo awesome work! This works great!

Regarding the modal, is there a way you could make it closable with the escape key, or by clicking outside of it? I think Bootstrap modals support closing through these methods.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo I've added a little function to detect esc key to close modal. Should be working with all projects running tests off of master script.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome idea! Is it possible to add click-outside-the-modal-to-close functionality, too? Also, the button that says "run tests" could also say (CTRL+SHIFT+ENTER) below it so people know the hotkey exists.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Whoops, I meant to mention, I added a tooltip to alert users to the hotkey combo

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson 
> Is it possible to add click-outside-the-modal-to-close functionality, too? 

@QuincyLarson Yup - all set :+1:

@Weezlo - added these three functions to accomplish the above tasks:
```
// close modal on ESC press
$(document).keyup(function(e) {
  e = e || window.event;
  if (e.keyCode == 27) { 
    FCCCloseTestModal();
  }
});

// close modal on click outside el
function FCCclickOutsideToCloseModal(e) {
  if(e.target.id === 'fcc_test_message-box') {
    FCCCloseTestModal();
  }
}

// run tests hotkeys
const map = [];
onkeydown = onkeyup = function(e){
  e = e || window.event; 
  map[e.keyCode] = e.type == 'keydown';
  if(map[17] && map[16] && map[13]) { 
    FCCRerunTests();
  }
}
```

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack very nice! 👍

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson - ok, we're really getting there now! This is also ready for QA, and tests are being served via the gitCDN we now have set up based on the repo here. We should discuss this at some point so I can fill you in.

I've made some slight changes to @Weezlo's original user stories just so they are more consistent with the rest of the projects, and added 2 new user stories. Here's everything:

pen for campers to fork: http://codepen.io/FCC_test_suites/pen/JbgXab
example project w/ tests: http://codepen.io/FCC_test_suites/pen/WoVoJL

## User Stories

### Content
1. I can see a wrapper element with a corresponding `id="quote-box"`.
2. Within `#quote-box`, I can see an element with corresponding `id="text"`.
3. Within `#quote-box`, I can see an element with corresponding `id="author"`.
4. Within `#quote-box`, I can see a clickable element with corresponding `id="new-quote"`.
5. Within `#quote-box`, I can see a "tweet" button with corresponding `id="tweet-quote"`.
6. On first load, my quote machine displays a random quote in the element with `id="text"`.
7. On first load, my quote machine displays the random quote\'s author in the element with `id="author"`.
8. When the `#new-quote` button is clicked, my quote machine should fetch a new quote and display it in the `#text` element.
9. My quote machine should fetch the new quote\'s author when the `#new-quote` button is clicked and display it in the `#author` element.
10. I can tweet the current quote by clicking on the `#tweet-quote` button. This button should use the "twitter.com/intent/tweet" path and tweet the current quote.

### Layout
1. The `#quote-box` wrapper element should be horizontally centered.

**Comment by QuincyLarson** [comment]
We now have a QA thread live here: https://forum.freecodecamp.com/t/random-quote-machine-project-with-testable-user-stories-guinea-pigs-needed/71910

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
