### ISSUE TITLE
HTML5 and CSS3 challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#6]
This topic needs an owner. 

For each challenge, please reply to this GitHub issue with:

1. The feature/concept being introduced/reinforced (challenge description)
2. What the camper is presented with (challenge seed)
3. How we might test for it (assert tests)

Please copy and paste this template for your idea
```
**Challenge**

<!-- challenge title your idea is for -->

**Challenge Description**

<!-- your challenge description --> 

**Challenge Seed**

<!-- Initial code presented to the camper -->

**Challenge Tests**

<!-- either assert tests or your ideas for things to be tested -->

**Challenge Solution**

<!-- solution to this challenge -->
```

Here are the challenges we have currently planned (these can be further expanded):

### Introduction to FreeCodeCamp’s Development Environment

- [ ] Ready

**Challenge Description**:

This is FreeCodeCamp’s in-browser development environment. This is where we will build our web pages with HTML (Hyper Text Markup Language), and style them with CSS (Cascading Style Sheets). Don’t worry if you have never heard of HTML and CSS before, we will got into more detail as you progress through the FreeCodeCamp curriculum.

__*Quick tour through the IDE - need to know what it will look like to complete this section*__

To move on to the next challenge, please click the ‘Run Tests’ tests button.
	
**Challenge Seed**:
		‘’
	
**Challenge Tests**:
    assert(code == ‘’);

**Challenge Solution**
```
 
```

### Introduction to HTML5 Elements

- [ ] Ready

**Challenge Description**

HTML5 introduces more descriptive HTML tags. These include &lt;code&gt;&lt;header&gt;, &lt;footer&gt;, &lt;nav&gt;, &lt;video&gt;,&lt;article&gt;&lt;/code&gt; and so-on.

These tags not only make your HTML easier to read, it also helps with Search Engine Optimisation (SEO).

The &lt;code&gt;&lt;main&gt;&lt;/code&gt; HTML5 tag helps search engines (google etc...), and other deveplopers, find the main content of your page.

Wrap your paragraph with a opening and closing lt;code&gt;&lt;main&gt;&lt;/code&gt; tag.

**Challenge Seed**
```html

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Challenge Tests**
```js
assert(code.match(/<main>\s*?<p>/), message:"Add an opening &lt;code&gt;main&lt;/code&gt; tag before your paragraph");
assert(code.match(/<\/p>\s*?<\/main>/), message:"Add a closing &lt;code&gt;main&lt;/code&gt; tag after your paragraph.");

**Challenge Solution**
```html
<h2>CatPhotoApp</h2>

<main><p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p></main>
```
### Use RGB to Mix Colors

**Comment by amrsekilly** [comment]
Can I help with that? @Bouncey @QuincyLarson

**Comment by Bouncey** [comment]
@amrsekilly sure, reply with your ideas for a challenge, or set of challenges. 

Include:
The feature/concept being introduced/reinforced (challenge description)
What the camper is presented with (challenge seed)
What the camper has to achieve (goals)
How we might test for it (assert tests)
A possible solution

Thanks for contributing :tada:

**Comment by amrsekilly** [comment]
**Add Images to your Website**



**Challenge Description**

Sometimes you need to add images to your website, it makes your content more engaging and fun. But be careful not to use too many images; it might slow down the loading of your website as it will increase the size of the resources.

Add [this](http://anysnapshot.com/wp-content/uploads/2013/07/Cats-Curiosity.jpg) image to your div element by adding an img element and adding it as the src, and observe what will happen!

Don't forget to add an alt text; as it helps make your website more accessible to a wider audience.

 

**Challenge Seed**


```
 <div>

 </div>
```




**Challenge Tests**

```
assert(code.match(/<img src="" alt="">/), message: 'You need to add the image's source in the src attribute');
assert(code.match(/<img src="">/), message: 'You need to add an alt text to your image tag');
```



**Challenge Solution**

```
 <div>
   <img src="http://anysnapshot.com/wp-content/uploads/2013/07/Cats-Curiosity.jpg" alt="Cat's Curiosity">
 </div>
```

**Comment by amrsekilly** [comment]
@Bouncey I'm sorry, but I've never used the assert method before. Is it [that one on the Chai docs](http://chaijs.com/api/assert/#method_match)?

Do you know a good resource for learning it?

**Comment by Bouncey** [comment]
@amrsekilly thanks for the challenge suggestion :+1: 

However, I think we will build the mobile view of the new catphotoapp, I will refactor the challenge order to reflect this. 

Here is a sample of what we are going to build. Which itself is in deveolopment right now



![image](https://cloud.githubusercontent.com/assets/18572518/16621117/10d609c0-438d-11e6-95c3-5d6bdc85196c.png)

**Comment by atjonathan** [comment]
@Bouncey, after we fix the spam issue for `v2`, we can link them to an example (freecatphotoapp.com will be used eventually as the domain).

**Comment by utsab** [comment]
@Bouncey and @QuincyLarson , I'm creating a few centering challenges.  The sequence will go as follows: 

1) Center text

2) Center inline elements

3) Center block elements 

Here is the template for #1.  I haven't filled out the assert statements yet.  Please let me know if you like the direction is going and then I'll figure out the assert statements: 


**Challenge**

Centering text



**Challenge Description**

Centering your text horizontally is a common layout operation.  

We center text by setting a style of the text's parent element(the element that contains the text). Specifically, we set the "text-align" property of the parent to a value of "center".  Note that we are styling the parent of the text and not the text itself.  

[show code example]

In the following exercise, create a class called "centered" and use it to center the text. 

**Challenge Seed**

<code>

<style>

</style>


<div>Center me</div>

</code>

**Challenge Tests**

 

**Challenge Solution**

<code>

<style>
.centered {
    text-align: center; 
}
</style>


<div class="center">Center me</div>

</code>



What do you think?

**Comment by QuincyLarson** [comment]
@utsab yes - this is a good start. I like how you describe the tests instead of writing them. We can create the specific tests later.

**Comment by QuincyLarson** [comment]
@Bouncey what is the state of this? We don't need to literally re-invent the wheel here - we have a ton of HTML and CSS challenges already. I think we should strive to expand upon these, rather than replace them at this point.

**Comment by UsamaHameed** [comment]
@Bouncey @QuincyLarson Since all the above mentioned challenges are already in the Map, I am thinking about some new challenges. For example, 
1. HTML
   * Opening a link in a new tab (Helped me in my Intermediate Front End Dev Projects)
   * HTML tables  
2. CSS
   * Floating
   * Absolute/Relative Positioning
   * Difference between absolute and relative units
3. There should be a project after the HTML and CSS section in which campers have to implement a complete but simple webpage so that they also know where to add the <head>, <body> etc. Something like a put-it-all-together project.
What do you think?

**Comment by UsamaHameed** [comment]
@Bouncey @QuincyLarson Since all the above mentioned challenges are already in the Map, I am thinking about some new challenges. For example, 

1. HTML
   * Opening a link in a new tab (Helped me in my Intermediate Front End Dev Projects)
   * HTML tables  
2. CSS
   * Floating
   * Absolute/Relative Positioning
   * Difference between absolute and relative units
3. There should be a project after the HTML and CSS section in which campers have to implement a complete but simple webpage so that they also know where to add the <head>, <body> etc. Something like a put-it-all-together project.
What do you think?

**Comment by alayek** [comment]
@FeelTheForce I like the idea! These kind of things help before asking campers to implement a whole project like portfolio or tribute page.

Also, regarding your `target="_blank", we might want to cover the [security vulnerability](https://news.ycombinator.com/item?id=11631292) too (at least mention it).

I think we are already covering it in the security section.

**Comment by FeelTheForce** [comment]
@alayek Where should I add them then? 
Before covering flexbox, should we not show how floating works? 
I will keep the security vulnerability in mind while writing them.

**Comment by QuincyLarson** [comment]
@UsamaHameed we can cover the "float" properties quickly. I agree with @alayek that most people will use FlexBox for this. We actually need an owner for our FlexBox challenges: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/21

Have you used FlexBox before? Would you be interested in helping design these challenges?

**Comment by UsamaHameed** [comment]
@QuincyLarson Unfortunately, no. I am yet to learn about FlexBox. Fortunately, I am starting to learn about it today. I am not sure if I will be experienced enough to write challenges for it in time.

**Comment by QuincyLarson** [comment]
@UsamaHameed no worries - You are already doing great work here and on the functional programming challenges. @atjonathan and @alayek are making progress on Flexbox :)

**Comment by QuincyLarson** [comment]
@utsab you [mentioned](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/6#issuecomment-234400103) working on positioning challenges. These would be a valuable addition to our HTML and CSS challenges. Have you had time to work on them at all?
