### ISSUE TITLE
chore: add greeting card workshop to main

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#614]
We already have the prototype here
https://github.com/freeCodeCamp/CurriculumExpansion/issues/421

we need to break down that prototype into steps and tests and add that to the main repo.

**Comment by ilenia-magoni** [comment]
Is this to start from an empty seed (barebones boilerplate), or with the HTML file given and then guiding the camper through adding the CSS?

**Comment by jdwilkin4** [comment]
The HTML barebones boilerplate should be provided and then they will write the rest of the HTML and CSS themselves
