### ISSUE TITLE
chore: add updated objects workshop to main repo

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#619]
Once the updated prototype is ready, then it can be added to the main repo with steps and tests.

Here is prototype issue

https://github.com/freeCodeCamp/CurriculumExpansion/issues/618

**Comment by jdwilkin4** [comment]
This is complete right? @Ksound22 

If so, this can be closed

**Comment by Ksound22** [comment]
Yes it is
