### ISSUE TITLE
Creat prototype for Maps and Sets lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#654]
We need to create a prototype for a short lab for campers to practice working with Maps and and Sets.

You can review the previous lecture block on the sheet to see what concepts were taught before this.

**Comment by jdwilkin4** [comment]
There might be a lab that we can reused from this data structures list
https://www.freecodecamp.org/learn/coding-interview-prep/#data-structures

We might be able to use it as is or maybe make a few adjustments to create a new prototype

**Comment by zairahira** [comment]
I might go with the [doubly linked list](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-doubly-linked-list).

**Comment by jdwilkin4** [comment]
@zairahira 

Classes and the `this` keyword hasn't been taught yet. So the challenge would need to be refactored to just use functions instead of classes.

But also, I don't know if this challenge really highlights working with maps or sets. It looks like a map or set is not needed here.


I found this challenge 
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/use--has-and--size-on-an-es6-set

This might work.
We can even expand on it to include some more methods
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by zairahira** [comment]
I went for a new prototype that uses both- `Set` and `Map`.
