### ISSUE TITLE
Testable User Stories: Tribute Page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#67]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).

Here's the newly designed version of this project: https://codepen.io/ChaituVR/full/PzxGEb/

**Comment by no-stack-dub-sack** [comment]
I can start working on user stories for this and may be able to write some of the tests.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack awesome! Keep in mind that this is the very first project, so do your best to keep it unintimidating :)

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson no problem - so we should be testing for responsiveness I am guessing - just presence of elements for the most part. I was thinking ~5 user stories for this one.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson The first set forces some basic structure, but still keeps it pretty simple. If we'd like to include tests for responsiveness, we might include the stories at the bottom to replace numbers 1, 3, & 4.  Let me know what you think, and I can try to begin writing tests for either (or make any changes that might be necessary first). Also, I would need to fork the pen to add a few of the IDs which are not present in current version.

## Set one (non-responsive):
1. My tribute page should have a main <div> element with corresponding id="main", which contains all other elements.
2. I should see an `<h1>` element with corresponding id=”title”, which contains a string that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").
3. I should see a `<div>` element with corresponding id="img-div".
4. Within the element with the id of "img-div", I should see an `<img>` element.
5. Within the element with the id of "img-div", I should see an element with a corresponding id=”img-caption” containing a string that describes the `<img>` element. 
6. I should see an element with a corresponding id="tribute-info", which contains textual content describing the subject of the tribute page. 
7. I should see an `<a>` element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. 

## Include responsiveness:
1. My tribute page should have a main `<div>` element with corresponding id="main", which contains all other elements, and is responsive to browser re-size/device size.
3. I should see a `<div>` element with corresponding id="img-div" that responsively resizes according to the width of its parent element.
4. Within the element with the id of "img-div", I should see an `<img>` element that responsively resizes according to the width of its parent element.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo, I've written tests for the first set of User Stories above (which do not test for page responsiveness). BUT, there's a catch: in order to test for attributes of elements (for user story number 7 - looking for `href `and `target` attributes), and to test for descendants of elements (user story number 1), I had to include one more dependency - in this case Chai-Jquery - and introduce an `expect `chai assertion. I could not otherwise figure out how to test for these things, let me know if either of you have any ideas or thoughts on this. 

You can see the Tribute Page pen with working tests here: 
https://codepen.io/no_stack_dub_sack/pen/WobRKE

And the fork of @Weezlo's test script which now includes the tribute page tests is here: http://codepen.io/no_stack_dub_sack/pen/zoxjvQ (tests start on line 731)

**Comment by Weezlo** [comment]
@no-stack-dub-sack Very good !
Actually we can do stories 1 and 7 without using Chai-JQuery or the expect assertion.
For story number 7 you can use the method "hasAttribute" of DOM elements (https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttribute).
For story number 1 we can use a query selector to achieve the same thing.

I've made these changes and a few other modifications and integrated the tests in the original Pen (http://codepen.io/Weezlo/pen/ALmBPw).
And here is a fork of @ChaituVR's tribute page without extra dependencies : https://codepen.io/Weezlo/pen/dOPwQv/

**Comment by no-stack-dub-sack** [comment]
@Weezlo Perfect, glad there was another solution - and now I've learned something new! I didn't realize you could use assert with your own expressions (without things like `.strictEqual`, .`isAbove`, etc.), which I guess is a failure on my part since that is the VERY 1st thing covered in the API documentation now that I go back and look :sweat_smile:! Whoops, haha. Well, nice save and thanks. One more down, plenty to go. Almost makes you wonder why plugins like Chai-Dom (which I would have preferred to use but could not find a working CDN for) and Chai-jQuery even exist...

So I guess the only thing left to discuss on this one then is whether or not to test for layout/page responsiveness like you did with the quote machine.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack @Weezlo This looks great! Awesome work, gentlemen! I'm closing this issue.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack I just noticed your question about responsiveness. I think if you include an additional user story checking whether the user used a media query in the CSS for the img-div attribute, that will suffice. You could also include additional user stories, but they should be separate to minimize confusion, and be the final user stories imho.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson hmmm... we could do that, however, there are no media queries utilized in the example pen.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack https://codepen.io/anon/pen/yVNwwP 

I centered the image using CSS. Your way of having max 100% will actually stretch the image and cause it to become pixelated if it isn't wide enough. This way will only let the image be as wide as its max width:

```
img{
  max-width: 100%; 
  display: block; 
  height: auto;
  margin: auto;
}
```

I think we could add how to do this to the responsive design section. I will mention this on that thread. 

We just need to test this - probably to test that max-width: 100% is used. 

We could then have another test that says "Center the image" that tests for margin: auto

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson  Sure, we can write these tests, I didn't write this pen, but I might have done the same thing as @ChaituVR as I didn't completely understand the distinction between `max-width` and `width` when using % as opposed to px/em. Learn something new every day!

I will update these tests this evening, and the code on my end so I can verify that they work. I will post both, with the new set of user stories when done so we can officially put this issue to rest. 

Thanks!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo, As discussed above - a post-closed amendment:

Here are the final user stories, updated to include 3 which test for responsive design according to Quincy's suggestions:
 - `max-width:100%` and `margin: auto` on the `<img>` 
 - "img-div" element must be full width of parent (enables the other 2 tests) 

For ease of copy/paste integration, I've created a new pen which has just the Tribute Page tests (these include Anis's earlier edits and the new tests). @Weezlo do you want to give them a quick look before pasting them in to the master? 
http://codepen.io/no_stack_dub_sack/pen/QGyQRo 

**This CSS (from above post) will need to be added to whichever pen ends up being the master project page:
```
img{
  max-width: 100%; 
  display: block; 
  height: auto;
  margin: auto;
}
```
You can see the new tests in action [here](http://codepen.io/no_stack_dub_sack/pen/full/WobRKE).

# Final User Stories: 

## Content:
1. My tribute page should have a main `<div>` element with corresponding id="main", which contains all other elements.
2. I should see an `<h1>` element with corresponding id="title", which contains a string (text) that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").
3. I should see a `<div>` element with corresponding id="img-div".
4. Within the "img-div" element, I should see an `<img>` element with a corresponding id="image".
5. Within the "img-div" element, I should see an element with a corresponding id="img-caption" that contains textual content describing the image shown in "img-div".
6. I should see an element with a corresponding id="tribute-info", which contains textual content describing the subject of the tribute page. 
7. I should see an `<a>` element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your <a> element an attribute of target and set it to "_blank" in order for your link to open in a new tab (i.e. `target="_blank"`). 

## Layout:
1. The element with id="img-div" should be the full width of its parent its parent element.
2. The `<img>` element should responsively resize, relative to the width of its parent element, without exceeding its original size.
3. The `<img>` element should be centered within its parent element.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack these look solid.

**Comment by Weezlo** [comment]
@no-stack-dub-sack 
>  @Weezlo do you want to give them a quick look before pasting them in to the master? 

I will do that.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson thanks, @Weezlo sounds good!

**Comment by QuincyLarson** [comment]
Re-opening until we have 3rd party QA.

**Comment by no-stack-dub-sack** [comment]
@Weezlo, this pen has the tests that need to be integrated into the "master pen" before we can have campers QA this project: http://codepen.io/no_stack_dub_sack/pen/QGyQRo 

You can see the new tests in action [here](http://codepen.io/no_stack_dub_sack/pen/full/WobRKE).

This CSS (from above post) will need to be added to whichever pen ends up being the master project page:

```
img{
  max-width: 100%; 
  display: block; 
  height: auto;
  margin: auto;
}
```

**Comment by no-stack-dub-sack** [comment]
@Weezlo, based on our convo on Gitter about a new CodePen account and a new master test script, I think this project is ready for QA (the details for new MASTER test script is in our Gitter chat). I have made the necessary integrations into the new master pen.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Weezlo, this project is ready for QA. Quincy, if you'd like to post on the Forum, maybe the best thing to do is include the user stories there. 

Here is the blank pen for campers to fork: http://codepen.io/no_stack_dub_sack/pen/KNmjWg
Here is the example project with passing tests: http://codepen.io/no_stack_dub_sack/full/WobRKE/

Here are the user stories for campers to reference:

## User Stories: 

### Content:
1. My tribute page should have a main `<div>` element with corresponding id="main", which contains all other elements.
2. I should see an `<h1>` element with corresponding id="title", which contains a string (text) that describes the subject of the tribute page (e.g. "Dr. Norman Borlaug").
3. I should see a `<div>` element with corresponding id="img-div".
4. Within the "img-div" element, I should see an `<img>` element with a corresponding id="image".
5. Within the "img-div" element, I should see an element with a corresponding id="img-caption" that contains textual content describing the image shown in "img-div".
6. I should see an element with a corresponding id="tribute-info", which contains textual content describing the subject of the tribute page. 
7. I should see an `<a>` element with a corresponding id="tribute-link", which links to an outside site that contains additional information about the subject of the tribute page. HINT: You must give your <a> element an attribute of target and set it to "_blank" in order for your link to open in a new tab (i.e. `target="_blank"`). 

### Layout:
1. The element with id="img-div" should be the full width of its parent its parent element.
2. The `<img>` element should responsively resize, relative to the width of its parent element, without exceeding its original size.
3. The `<img>` element should be centered within its parent element.

**Comment by QuincyLarson** [comment]
All right, this thread is live here: https://forum.freecodecamp.com/t/tribute-page-project-with-testable-user-stories-guinea-pigs-needed/58927

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
