### ISSUE TITLE
Testable User Stories: Portfolio

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#68]
Soon, campers will be able to build all front end projects right on FreeCodeCamp.com (no need for CodePen). We will also use automated tests to check whether campers have completed all of the agile user stories (and code review will become optional). 

This means we need to create user stories that can be tested. And we should err on the side of having lots of tests (I'm thinking ~10 tests per project).
Here are the naive ones (from before we realized these could be testable): 

1. I can access all of the portfolio webpage's content just by scrolling.
2. I can click different buttons that will take me to the portfolio creator's different social media pages.
3. I can see thumbnail images of different projects the portfolio creator has built (if you haven't built any websites before, use placeholders.)
4. I can navigate to different sections of the webpage by clicking buttons in the navigation.

Here's the newly designed version of this project: http://codepen.io/ChaituVR/full/PzXOVv/

**Comment by IsaacAbrahamson** [comment]
Just a couple ideas that could be checked automatically:

1. Page should be responsive.

2. Page should contain a #welcome section that takes 100% screen height.

3. #welcome section should have an <h1> element with your name or camper name.

4. Page should have a #portfolio section.

5. #portfolio should contain at least one .portfolio-tile for a project.

6. .portfolio-tile must contain a link to view its project.

7. Page should contain a #nav element at top of screen.

8. I can always see #nav wherever I am on the website.

9. #nav should have a link to #portfolio section.

10. I can click a link on the page and be able to visit your FCC or GitHub profile in a new tab.

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson this is excellent. Can you start writing tests for these? They could be Chai tests. As far as "the page should be responsive" you could check and make sure they're using at least one media query. You might just change that test to "Page should contain at least one media query"

For nav always being at the top, you could check that the nav section (which should use `.nav` should have the style "position:fixed")

You may be able to create a simple interface so you can test these chai tests right on CodePen. 

I noticed that @Weezlo built in a Chai test suite into his calculator project a few weeks ago: https://codepen.io/Weezlo/pen/dpXJrp/

**Comment by IsaacAbrahamson** [comment]
@QuincyLarson never heard of Chai, but I will look into once the week starts, see you then.

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson OK - great. There is pretty good documentation for it.

**Comment by no-stack-dub-sack** [comment]
@IsaacAbrahamson I noticed in Issue #54 that you were a newer member and were looking for a place to jump in and contribute. I am as well and have been working on some user stories and tests for other projects. I also noticed in the same issue that you were looking for a little guidance into jumping into working on the tests. If you are still interested in working on this - check out issue #67. @Weezlo has written most of the tests, but I have started to learn Chai a little as well and have been writing some basic ones. 

If you are looking for a place to start, check out the pen I posted on that issue and you will see an example of what the tests should look like (on line 733 I believe) for a simpler project like the tribute page or portfolio. Not too much of  a stretch from there to write tests for your user stories based on these... drop me a line on Gitter if you'd like and I would be happy to help to the best of my somewhat limited abilities on this! This is a great opportunity for folks like ourselves who are still learning to help out!

**Comment by IsaacAbrahamson** [comment]
@no-stack-dub-sack, Thank you!

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson wow - great to see you hear helping out with these new testable projects and user stories. 

You're in good hands with @no-stack-dub-sack and @Weezlo. Take a look at their existing projects such as this one http://codepen.io/no_stack_dub_sack/pen/amaAzq and see if you can learn from that as an example, then ask questions if you get stuck. I'm also happy to help, and looking forward to our talk tomorrow night about the forum.

**Comment by Christian-Paul** [comment]
I've built upon @IsaacAbrahamson's user stories to create this list:

# User Stories

## Content
1. My portfolio should have a Welcome section with an id of "welcome-section"
2. The welcome section should have an h1 element that contains text
3. My portfolio should have a projects section with an id of "projects"
4. The projects section should contain at least one element with a class of "project-tile" to hold a project
5. The projects section should contain at least one link to a project
6. My portfolio should have a navbar with an id of "navbar"
7. The navbar should contain at least one link that I can click on to navigate to different sections of the page
8. My portfolio should have a link with an id of "profile-link", which opens my GitHub or FCC profile in a new tab

## Layout
1. My portfolio should have at least one media query
2. The height of the welcome section should be equal to the height of the viewport
3. The navbar should always be at the top of the viewport

Here is the pen with my tests: http://codepen.io/Christian-Paul/pen/XNypXW
And the sample project with a few changes to the ids/classes to pass the tests: http://codepen.io/Christian-Paul/pen/BQGprG

I tried to model my user stories and tests after some of the existing ones in the other projects.

I'd love some feedback @no-stack-dub-sack @QuincyLarson

**Comment by QuincyLarson** [comment]
@Christian-Paul wow - this is excellent. Great job learning the testing framework and pulling this together so quickly! 

@no-stack-dub-sack what do you think? Any feedback before we post this on our forum and get campers working through it?

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul Hey guys! Christian - great job! This looks awesome. I'm going to fork your example project into the FCC_Test_Suites CodePen profile, and integrate your tests into the master pen. I'm going to make at least 1 minor change: for user story # 8 - I'm going to add an `assert()` that tests for the presence of the `target` attribute before testing that it's equal to `"_blank"`. That way a more clear message will be presented to the user if they do not set a target attribute at all. If there's anything else, I will let you know. 

I will post both here shortly and let Quincy know when they are ready for QA!

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Christian-Paul, Ok, I've made the one change I mentioned above, and I've changed the language of the user stories slightly to be consistent with the rest so far. 

I've also integrated the tests into the master pen and forked the example as a redundancy and in order to update the external JS to be the master script that contains all tests. I've also added Christian's name to the "coded by" section at the top of the test script. 

I would say this is ready for QA. Here's the links and user stories below:

Example: http://codepen.io/FCC_test_suites/pen/yVGpKJ
Pen to fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories

### Content
1. My portfolio should have a Welcome section with a corresponding`id="welcome-section"`.
2. The welcome section should have an h1 element that contains text.
3. My portfolio should have a projects section with a corresponding `id="projects"`.
4. The projects section should contain at least one element with a `class` of "project-title" to hold a project.
5. The projects section should contain at least one link to a project.
6. My portfolio should have a navbar with a corresponding `id="navbar"`.
7. The navbar should contain at least one link that I can click on to navigate to different sections of the page.
8. My portfolio should have a link with a corresponding `id="profile-link"`, which opens my GitHub or FCC profile in a new tab.

### Layout
1. My portfolio should have at least one media query.
2. The height of the welcome section should be equal to the height of the viewport.
3. The navbar should always be at the top of the viewport.

**Comment by Christian-Paul** [comment]
@QuincyLarson @no-stack-dub-sack Thanks a lot for the feedback! I'm looking forward to seeing how it does in the next steps!

**Comment by no-stack-dub-sack** [comment]
@Christian-Paul Likewise - I think it will do well - the test are designed in just the right way for a project early on in the curriculum such as this one

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Christian-Paul - I just left a message in the Landing Page thread too, but since these have not been posted by Quincy for QA yet, I think we need to hold off until we figure something out. The Layout tests may have some problems. The media query test fails in full page mode and relies on CodePen specific syntax - which we cannot use in case people develop elsewhere. Also, the navbar test may fail if a user has a top margin on the nav bar even if it sticks to the top of the page. 

Once these 2 issues are fixed, it will be good to go.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack agreed. It is hard to test for responsiveness, but once we figure out a reliable way, we can use it on all of these projects.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @Christian-Paul Ok, I left a comment in issue #71 where we were discussing the media query test and navbar tests. I believe both issues are now fixed. @Christian-Paul modified the navbar test to allow for a margin of error, and we worked through the media query test to loop through all stylesheets looking for the presence of a media query. With both of those fixed, I think NOW we can push this out to QA. 

So once again, here's everything in its ready state:

Example Project with Passing Tests: http://codepen.io/FCC_test_suites/full/yVGpKJ
Pen to Fork: http://codepen.io/FCC_test_suites/pen/QGMMZO

## User Stories

### Content
1. My portfolio should have a Welcome section with a corresponding`id="welcome-section"`.
2. The welcome section should have an h1 element that contains text.
3. My portfolio should have a projects section with a corresponding `id="projects"`.
4. The projects section should contain at least one element with a `class` of "project-title" to hold a project.
5. The projects section should contain at least one link to a project.
6. My portfolio should have a navbar with a corresponding `id="navbar"`.
7. The navbar should contain at least one link that I can click on to navigate to different sections of the page.
8. My portfolio should have a link with a corresponding `id="profile-link"`, which opens my GitHub or FCC profile in a new tab.

### Layout
1. My portfolio should have at least one media query.
2. The height of the welcome section should be equal to the height of the viewport.
3. The navbar should always be at the top of the viewport.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Awesome - I've created the forum thread here: https://forum.freecodecamp.com/t/portfolio-page-project-with-testable-user-stories-guinea-pigs-needed/66994

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
