### ISSUE TITLE
Quality Assurance and Information Security Project: Metric Imperial Converter

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#75]
We are updating the Dynamic Web App projects to focus 100% on their back ends, and adding additional quality assurance and information security user stories. 

These projects will no longer require a front end. Instead, all the tests will be focused on JSON APIs like the API and Microservice projects. The front end will be optional and not tested.

For this project, we want a simple measurement converter that accepts a unit and its quantity and converts it from metric to imperial or vice versa. 

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
- If I pass a unit without a quantity, the API assumes the quantity is 1.
- I can pass fractional quantities.
- I can convert grams to pounds, and vice versa
- I can convert meters to miles, and vice versa
- I can convert gallons to liters, and vice versa
- If I pass a term that is not one of these units, I get an error message.
- There are 6 unit tests that verify that each of the conversions work
- There are 3 route tests to verify that the wrong inputs don't work

We can add more stories for additional testing and security issues.

Progress: 
- [ ] Create the list of tests
- [ ] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] To ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] A series of tests added to Free Code Camp's seed files

**Comment by Em-Ant** [comment]
@QuincyLarson  I've started building a simple demo. I don't have clear the email -> key work-flow. How 'realistic' we want it to be ?

**Comment by QuincyLarson** [comment]
@Em-Ant thank you for your patience with my slow response. I am not sure how the user could securely obtain an API key without also passing a password as a parameter or doing an email verification (and we don't want campers to have to set all that up). Maybe we could just have them hit an endpoint, which returns an API key, then they use that API key on future requests. What do you think?

**Comment by QuincyLarson** [comment]
@Em-Ant if you haven't made any progress on this yet, @systimotic is interested in tackling all of these remaining back end projects. I've messaged you on Gitter about him.

**Comment by systimotic** [comment]
Hi all! @QuincyLarson @Em-Ant @Greenheart 
I apologize for the radio silence. I finally got started on this yesterday.
I came across an interesting issue. There are two different types of gallons, the imperial gallon and the US gallon. According to Wikipedia, the imperial gallon is used (among others) in the UK and Canada, and the US gallon is used in the US 😜.
The difference is significant. Because this project is called 'Metric Imperial Converter', it makes sense to me we use the imperial gallon. If I ask Google what one gallon is in liters, it uses the US gallon by default (without telling me).
Regardless of which one we use, we should make it very clear that that's the one we're using. How do you feel about including all of the formulas in the instructions?

**Comment by systimotic** [comment]
Oh, and while we're at it, precision is going to be a big deal in this one. All of the numbers should probably be rounded, I suggest to 5 decimals. Another option is to tell them to use less decimals in the formulas.

**Comment by QuincyLarson** [comment]
@systimotic Yes - I think being accurate to 5 decimal places can be a stated requirement in the user stories. I think we should drop gallon from the conversion and use Ounce instead, which is a smaller metric that's probably more consistent.

**Comment by JosephLivengood** [comment]
User Stories

- I will prevent the client from trying to guess(sniff) the MIME type.
- I will prevent cross-site scripting (XSS) attacks.
- I can GET /api/convert with a single parameter containing an accepted number and unit and have it converted. (Hint: Split the input by looking for the index of the first character which will mark the start of the unit)
- I can convert 'gal' to 'L' and vice versa. (1 gal to 3.78541 L)
- I can convert 'lbs' to 'kg' and vice versa. (1 lbs to 0.453592 kg)
- I can convert 'mi' to 'km' and vice versa. (1 mi to 1.60934 km)
- If my unit of measurement is invalid, returned will be 'invalid unit'.
- If my number is invalid, returned with will 'invalid number'.
- If both are invalid, return will be 'invalid number and unit'.
- I can use fractions, decimals or both in my parameter(ie. 5, 1/2, 2.5/6), but if nothing is provided it will default to 1.
- My return will consist of the _initNum_, _initUnit_, _returnNum_, _returnUnit_, and _string_ spelling out units in format '{initNum} {initial_Units} converts to {returnNum} {return_Units}' with the result rounded to 5 decimals in the string.
- All 16 unit tests are complete and passing.
- All 5 functional tests are complete and passing.

The 16 unit tests are named with some being filled in for example. They test each function in the convertHandler(6 total) with valid/invalid/blank/ect inputs. The 5 functional tests test valid input, the 3 invalid inputs and a no number input.


Passing prototype built on boilerplate: https://gomix.com/#!/project/hard-twilight 
Boilerplate: https://gomix.com/#!/project/fcc-convert
Tester(ISQA_2-Metric/Imp Converter): https://pricey-hugger.gomix.me/

**Comment by Em-Ant** [comment]
@JosephLivengood it looks really great, and it has a clear structure.

**Comment by QuincyLarson** [comment]
The forum thread for QA'ing this is here: https://forum.freecodecamp.com/t/metric-imperial-conversion-project-with-testable-user-stories-guinea-pigs-needed/72754

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.

**Comment by EvonyJade8** [comment]
im not quite sure how to do the functional testing for the api routing....... im having difficulties with my lessons, so i went straight for the projects to see what i could at least learn while i regroup for the lessons..... im almost done with this project but not uite sure what i need to do on this last bit.... help?

**Comment by RandellDawson** [comment]
@EvonyJade8 Please use the [forum](https://freecodecamp.org/forum) or our [Gitter channels](https://gitter.im/FreeCodeCamp/Help) for help with challenges or projects.

Thank you.
