### ISSUE TITLE
Quality Assurance and Information Security Project: Personal Library

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#78]
We are updating the Dynamic Web App projects to focus 100% on their back ends, and adding additional quality assurance and information security user stories.

These projects will no longer require a front end. Instead, all the tests will be focused on JSON APIs like the API and Microservice projects. The front end will be optional and not tested.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
- I can view available books in a JSON array
- I can check out a book
- I can add a book
- Only one book can be checked out at a time from one IP address
- Checks to see whether a book of submitted title is found (using the Google Books API, or perhaps the Amazon API - we should choose one)
- Sanitizes the string to prevent JavaScript injection
- Makes sure the book is OK for general audiences, then inserts the book into the library
- Allows for more than one copy of the same book

Progress: 
- [ ] Create the list of tests
- [ ] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] To ask campers to build their own versions based off of our instructions and our boilerplate
- [ ] A series of tests added to Free Code Camp's seed files

**Comment by JosephLivengood** [comment]
User Stories

- Nothing from my website will be cached in my client.
- The headers will say that the site is powered by 'PHP 4.2.0' even though it isn't (as a security measure).
- I can post a _title_ to /api/books to add a book and returned will be the object with the _title_ and a unique __id_.
- I can get /api/books to retrieve an array of all books containing _title_, __id_, & _commentcount_.
- I can get /api/books/{_id} to retrieve a single object of a book containing _title_, __id_, & an array of _comments_ (empty array if no comments present).
- I can post a _comment_ to /api/books/{_id} to add a comment to a book and returned will be the books object similar to get /api/books/{_id} including the new comment.
- I can delete /api/books/{_id} to delete a book from the collection. Returned will be 'delete successful' if successful.
- If I try to request a book that doesn't exist I will be returned 'no book exists'.
- I can send a delete request to /api/books to delete all books in the database. Returned will be 'complete delete successful' if successful.
- All 6 functional tests required are complete and passing.

Passing prototype built on boilerplate: https://gomix.com/#!/project/spark-cathedral
Boilerplate: https://gomix.com/#!/project/fcc-library
Tester(ISQA_1-Personal Library): https://pricey-hugger.gomix.me/

**Comment by QuincyLarson** [comment]
Forum post for QA process is here: https://forum.freecodecamp.com/t/personal-library-project-with-testable-user-stories-guinea-pigs-needed/72757

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
