### ISSUE TITLE
User Experience Design Challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#8]
We are seeking a camper to be in charge of coordinating the creation of these challenges. 

For each challenge, please reply to this GitHub issue with:
1. Challenge description text
2. Test suite (using the assert method)
3. The seed code, which is pre-populated in the editor at the beginning of the challenge
4. A working solution that makes all tests pass

We still need to come up with a list of concepts to cover, where each topic can be taught interactively, then translate these concept into the names of the challenges.

**Comment by SamAI-Software** [comment]
Topics to cover:

- Sign Up / Sign In / Log In
- [Action Buttons](https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150#.xukgr0f32)
- [Radio buttons](http://babich.biz/radio-buttons-ux-design/)
- [Checkboxes, toggle] (http://babich.biz/checkbox-and-toggle/)
- Hamburger menu
- Animation speed
- Animation for loading/processing
- [Motion design](http://babich.biz/motion-in-ux-design/)
- [User Errors](https://uxplanet.org/mobile-ux-design-user-errors-1ad1f5d664f9#.mkufg2mqo)
- [Infinite Scrolling](http://babich.biz/infinite-scrolling-best-practices/)
- [Pagination](https://uxplanet.org/pagination-best-practices-76fbd3f5a78d)
- [Infinite Scrolling vs. Pagination](https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1)
- [Page payment](https://yoast.com/checkout-page-ux/)

Additional:

- [Accessibility](https://medium.com/salesforce-ux/7-things-every-designer-needs-to-know-about-accessibility-64f105f0881b#.uzumjhqqa)
- Flat design
- Sceuomorphism
- Web brutalism
- [Progressive enhancement vs Graceful Degradation](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement)

**Comment by QuincyLarson** [comment]
@creativejuggernaut mentioned these on our call:
- primary CTA vs secondary funnel
- reusing partials and components (for consistent patterns everywhere) - every time you have three adjacent buttons, you make them follow the same format.
