### ISSUE TITLE
Testable API and Microservice Projects: URL Shortener

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#80]
We are updating the API and Microservice projects to be testable. Campers will start with a boilerplate specific to each project.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
(to be added)

Progress: 
- [x] Edit the user stories if necessary to ensure they are testable 
- [x] Create the list of tests 
- [x] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] Ask campers to build their own versions based off of our instructions and our boilerplate :construction: 
- [ ] Add tests to Free Code Camp's seed files

**Comment by Em-Ant** [comment]
### Links
boilerplate:  https://hyperdev.com/#!/project/shimmer-ripper :construction: 
working demo: https://hyperdev.com/#!/project/thread-paper :construction: 

### Current user stories

1. I can pass a URL as a parameter and I will receive a shortened URL in the JSON response. 
2. If I pass an invalid URL that doesn't follow the valid http://www.example.com format, the JSON response will contain an error instead.
3. When I visit that shortened URL, it will redirect me to my original link..

### Proposed Imrpovements

* Change the HTTP method for the new url creation from GET to POST, according to REST. See https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7392  
...

**Comment by Em-Ant** [comment]
@QuincyLarson should we go with POST ? If we use many boilerplates I can create a form in the main view.

@Greenheart feel free add your thoughts.

**Comment by Greenheart** [comment]
After reading up on this, I think we should use POST to follow conventions.

@Em-Ant I read the referenced issue. Have you solved how campers should
test their API for this project? :)

tisdag 22 november 2016 skrev Emanuele Antonelli <notifications@github.com>:

**Comment by Em-Ant** [comment]
I was thinking to test the redirection using another hyperdev server .
The steps could be :
1. We add a valid url pointing to the support hyperdev server, having a random string in it. We test that the API response is ok, and we store the short url in a global var (e.g. `window.shortUrl`)
2. We use the redirection endpoint with the stored short url. After redirection the support hyperdev server will send back the random string. If we need maximum cheating protection, we cold think of some kind of encryption performed by the 2nd server.

Check out the last tests on [narrow-plane](https://hyperdev.com/#!/project/narrow-plane). I implemented is a draft version of this process.

**Comment by Em-Ant** [comment]
@QuincyLarson @BerkeleyTrue if we use the worflow explained above, the 2 steps need to be executed **sequentially**. Does our system support serial ajax calls (not parallel) ?

**Comment by QuincyLarson** [comment]
@Em-Ant @BerkeleyTrue said as long as when a request completes, it resolves a promise, these ajax calls can be run serially. Does this answer your question?

**Comment by Greenheart** [comment]
@Em-Ant Nice idea!

onsdag 23 november 2016 skrev Quincy Larson <notifications@github.com>:

**Comment by Em-Ant** [comment]
@QuincyLarson if the ajax call can be run serially serially I think it should be ok.  Thanks.

**Comment by QuincyLarson** [comment]
OK - cool. Please let me know if I can help with anything else. My goal is to keep you all unblocked so you can keep making steady progress with this 🙂

**Comment by Em-Ant** [comment]
This should be ready to QA. 


boilerplate: https://hyperdev.com/#!/project/pastoral-caution
working demo: https://hyperdev.com/#!/project/thread-paper

testing with [narrow-plane](https://narrow-plane.hyperdev.space/), option `MS3-url shortener` .

**notes** : 
* this project needs a db (mLab URI)
* the tests must be run sequentially

**Comment by QuincyLarson** [comment]
Forum thread for QA'ing this is live here: https://forum.freecodecamp.com/t/url-shortener-project-with-testable-user-stories-guinea-pigs-needed/60782

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
