### ISSUE TITLE
Testable API and Microservice Projects: Timestamp Microservice

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/CurriculumExpansion#82]
We are updating the API and Microservice projects to be testable. Campers will start with a boilerplate specific to each project.

Here some proposed user stories - feel free to expand upon them by replying to this comment, and if you see any that look unnecessary, please say so:
(to be added)

Progress: 
- [x] Edit the user stories if necessary to ensure they are testable
- [x] Create the list of tests
- [x] Build a prototype where all of those tests pass (to verify it can be done)
- [ ] Ask campers to build their own versions based off of our instructions and our boilerplate :construction: 
- [ ] Add tests to Free Code Camp's seed files

**Comment by Em-Ant** [comment]
### Links 
* API boilerplate to fork : https://shimmer-ripper.hyperdev.space 
* Working example : https://hyperdev.com/#!/project/curse-arrow - it's based on my solution. We should simplify the html view to be as simple as possible before releasing it.

### User stories before the update:

**1.** I can pass a string as a parameter, and it will check to see whether that string contains either a unix timestamp or a natural language date (example: January 1, 2016).
**2.** If it does, it returns both the Unix timestamp and the natural language form of that date.
**3.** If it does not contain a date or Unix timestamp, it returns null for those properties.

### Proposed amendments : 
* The API endpoint is ```GET [project_url]/api/timestamp/:date```
* A date string is valid if can be successfully parsed by ```new Date(date_string)``` (JS)
* If the date string is valid the api returns a JSON having the structure 
```{"unix": [all_digits_unix_ts], "natural" : [Full_month_name numeric_day, full_year] }```
e.g ```{"unix":1479656875,"natural":"November, 20 2016"}``` 

@Greenheart @systimotic what do you think ? The date format can be changed, but it's very important that it is well defined.

**Comment by QuincyLarson** [comment]
@Em-Ant Excellent. Quick question - should we have different boilerplates for each project? That will give us a little extra flexibility. Also, we can have a nice Readme.md like the one you have on  https://hyperdev.com/#!/project/curse-arrow, and any other necessary instructions right there in the boilerplate. I know it's a lot of extra projects, but it would be nice for these to be useable independent of going back to FCC to check the user stories.

**Comment by Em-Ant** [comment]
@QuincyLarson if you think that our improvements are ready to be imported as 'user stories' without any *smoothing*, we can say that this project is ready for QA. 

If you want we can have different boilerplates, with different readme.md. Should I copy the user stories in the boilerplate ?

**Comment by Greenheart** [comment]
Please note that the README and index.html of this microservice's example
solution need updates. I'd say we should do them once all other parts of
this project are done.

måndag 21 november 2016 skrev Emanuele Antonelli <notifications@github.com>:

**Comment by Em-Ant** [comment]
I was waiting for the user stories to be 'approved' ...

**Comment by QuincyLarson** [comment]
@Em-Ant yes - these user stories look good!

And yes - if you could create a similar-looking Readme and index.html for all of the projects like you have on https://hyperdev.com/#!/project/curse-arrow that would be ideal. Once these are ready, can you fork them from the Free Code Camp HyperDev account? Then I can start posting them on the forum requesting help.

**Comment by Em-Ant** [comment]
@QuincyLarson OK. 
These projects are already owned by camperbot's account

**Comment by Em-Ant** [comment]
@QuincyLarson 
The boilerplate and the working solution are ready for QA. 
Camper projects can  be tested with [narrow-plane](https://narrow-plane.hyperdev.space/), selecting the option `MS1-timestamp` in the dropdown list, and inputting a valid project url.

**Comment by QuincyLarson** [comment]
I've encouraged campers to try building this on the forum here: https://forum.freecodecamp.com/t/timestamp-microservice-with-testable-user-stories-guinea-pigs-needed/58955/1

**Comment by Greenheart** [comment]
@QuincyLarson Great news!

fredag 25 november 2016 skrev Quincy Larson <notifications@github.com>:

**Comment by Em-Ant** [comment]
What do you think about this issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9327 (returning null is bad pratice) ?

**Comment by systimotic** [comment]
@Em-Ant I agree that this is bad practice. I think we should be verbose and return an error. Returning an error in JSON, similar to some other projects, seems like a got solution to me.
```
{
  "error": "Invalid date"
}
```
Should we close the other issue in favor of this one?

**Comment by Em-Ant** [comment]
@systimotic I updated the user stories.

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! This is being QA'd and discussed.

I'm closing this issue. If anyone wants to discuss these further, please reopen it.
