### ISSUE TITLE
Web Design examples for some challenges

### ISSUE THREAD

**Issue by gepetobio** [FreeCodeCamp/CurriculumExpansion#85]
https://www.freecodecamp.com/challenges/build-a-tribute-page
https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage

I've been helping some people who have reached these 2 challenges and have not progressed because they didn't have a Design idea to build them. Some students are too worried about Design while they are still learning basic HTML and CSS. Although they have the capability to build those pages, they want them to look really nice. But they lack knowledge on Design Principles (which is not the goal for those challenges) and end up not building those pages or taking several days to build something they don't like (or are not proud of).

I would like to suggest that we add some sort of possible designs for those challenges. They can be simple JPGs or PNGs that someone can pick and follow, without having to think and come up with their own designs. I know there are several Web Designers doing the FCC challenges who would be glad to share some design options to those that lack those really-nice-to-have design skills.

That doesn't mean one cannot come up with his/her own designs for those challenges but giving the option to the others who hit a wall just because they are not good at web design.

I would like to hear someone else's opinions on this. I know it's not crucial but I strongly believe it would help some people...

**Comment by Em-Ant** [comment]
@gepetobio thanks for your comment. Our contributors are redesigning the front-end projects to be remotely testable. They will have a strict list of features to be implemented. We will also show example projects, designed with a 'minimal' style, to not discourage the beginners. These projects should work as reference, as you suggest.

If you want to take a look at what's going on with these challenges see:
https://github.com/FreeCodeCamp/CurriculumExpansion/issues/68
https://github.com/FreeCodeCamp/CurriculumExpansion/issues/67

**Comment by gepetobio** [comment]
@Em-Ant thanks a lot for your reply! I had seen [#71](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/71) and saw that the fronted projects would be inside FCC instead of Codepen.io but didn't see the issues you sent!

I'll look into them and maybe see if I can help as well ;-)

Not sure what to do with this ticket then... if this has been considered and has been already worked on, probably worth closing it?
