### ISSUE TITLE
Callbacks, Promises, and Async/Await

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/CurriculumExpansion#86]
I am not sure if this has been proposed or if it is already incorporated in other curriculum expansion requests here (I've searched, but didn't find anything).

I'd like to propose the introduction of some concepts that are core to JavaScript and Node.JS development in the following order:
- Callbacks
- Promises
- Async/Await (maybe)

**Reasoning**
- By starting with `callbacks`, we're introducing the students to how JavaScript handles asynchronicity natively, pointing out that many nested `callbacks` are difficult to reason about and maintain (which naturally leads to the next concept)
- `promises` help JS developers manage asynchronous callbacks in a more elegant/maintainable way.
- Optionally, we can introduce the new concept of `async/await` (available behind the `node --harmony-async-await` flag), which helps JS developers write asynchronous code in a seemingly synchronous style.

**Comment by pmbenjamin** [comment]
I just saw that `promise` lesson is discussed in #34 , but before jumping right into Promises, we should probably introduce `callback` lesson first to help the student understand why Promises are the way to go.

**Comment by QuincyLarson** [comment]
@pmbenjamin I agree that we should add these topics. We can revisit them once we've pushed our existing new challenges.
