### ISSUE TITLE
Publishing Modules to NPM

### ISSUE THREAD

**Issue by pmbenjamin** [FreeCodeCamp/CurriculumExpansion#87]
I propose adding an exercise/challenge for students to publish a simple JS project/module/library to NPM.

**Reasoning**
- Helps the student practice `callback` and/or `promise` to expose an asynchronous API to the consumer of their library (`promise` lessons are proposed in #34, `callback` lessons are proposed in #86)
- Helps the student practice `export`ing stuff (which is a lesson proposed in #34).
- Give students a feeling of accomplishment having published their potential first module to NPM.

**Comment by t3h2mas** [comment]
To tie into this? https://www.freecodecamp.com/challenges/manage-packages-with-npm

**Comment by pmbenjamin** [comment]
@t3h2mas - ah, didn't see that. I guess this request is superfluous then.

**Comment by Em-Ant** [comment]
@pmbenjamin the challenge **manage packages with npm** is going to be replaced in the new curriculum. Anyway we decided to not teach how to publish a package, because we want to keep things as simple as possible, and it's unlikely that  beginners need to publish packages. Thanks.
