### ISSUE TITLE
P2P Video Chat Application User Stories

### ISSUE THREAD

**Issue by karuppiah7890** [FreeCodeCamp/CurriculumExpansion#88]
@QuincyLarson How does this look ? Do tell me if there are changes to be made and if it's too complex and stuff

Objective: Build a hyperdev.com app that is functionally similar to this: https://unequaled-cement.hyperdev.space/

Fulfill the below user stories. Use whichever libraries or APIs you need. Give it your own personal style.

1. User Story: Upon arriving, the browser will prompt me to access my camera and microphone.

2. User Story: After I give it permission, I am prompted to type in a room name.

3. User Story: Once I type in the room name, a room will be created if no room of that name existed before.

4. User Story: A friend of mine can subsequently go to the same website, type in the same room I entered, and join the same room, then enter into a video chat with me. 

5. User Story: If I type in a room name, and there are already two people in that room, I get a notification that the room is full. 

6. User Story: Anyone can create or join any room. And there can be any number of rooms, but all of them must have unique names. 

7. User Story: I can choose to not permit the site to access my microphone and webcam. If I choose not to do this, if some other driver problem occurs, I see an error message saying these are required.

8. User Story: When I choose to cancel the room name input step, or if I type in no name, or just spaces, it should again ask me again to type in a valid room name.

9. User Story: If one of the two people in the room get disconnected, they can reconnect to the same room and continue chatting.

**Comment by QuincyLarson** [comment]
@karuppiah7890 I checked and I'm getting the following error:

![](https://www.evernote.com/l/Ar_QTRu0LMhNaYagZ_BB_Zsyt6UulmhdErUB/image.png)

**Comment by karuppiah7890** [comment]
@QuincyLarson What browser are you using ? Chrome ? I just checked, things are working fine in Firefox and even Chrome. Can you try again ?

**Comment by karuppiah7890** [comment]
@QuincyLarson I think it was some problem with hyperdev. Some server error probably, with all their new community and stuff : https://hyperdev.com/community/ with community projects

**Comment by atjonathan** [comment]
@QuincyLarson, this appears to load correctly now.

**Comment by QuincyLarson** [comment]
OK - I figured it out. Adblock was preventing it from working, so we might add a note about that.

**Comment by karuppiah7890** [comment]
Oh, okay!
Actually, even I have AdBlock, but nothing like that happened to me. May be some special settings

**Comment by texas2010** [comment]
I got error too. no wonder, adblock blocked it.  
I test it without adblock on. it is working!  
I use chrome.

**Comment by karuppiah7890** [comment]
But yeah, we can tell campers about it.

And what about user stories ? How do they look ?

**Comment by QuincyLarson** [comment]
@karuppiah7890 I went through and updated your user stories in your original post to make their wording a bit clearer. I also structured them all as "user story" instead of "error handling" and such. This makes them more consistent with the other projects.

**Comment by karuppiah7890** [comment]
Oh. I just noticed. I didn't know others can change a comment

**Comment by karuppiah7890** [comment]
Actually, it's a lot clear now. Well, I guess I need better vocab and writing skills too

**Comment by QuincyLarson** [comment]
@karuppiah7890 people with write access to a repo can. You can see that I edited the message last. I hope you don't mind - it was cleaner than pasting (almost identical) user stories below as a comment.

**Comment by QuincyLarson** [comment]
@karuppiah7890 all that remains to be done is to add this code to the "extra practice projects" section on the curriculum expansion branch. Would you be interested in doing this? Be sure to copy one of the challenge IDs and modify it slightly so it'll have its own unique ID. I'd be happy to do this myself, but you have done all the work here, so you should get credit for the PR :)

**Comment by karuppiah7890** [comment]
Sure! So, I should create a PR against `feature/curriculum-expansion` branch right ?

I see lots of projects with Hints. Do I need to give any ?

**Comment by karuppiah7890** [comment]
And what is the key `challengeSeed` in the challenge object ?

**Comment by QuincyLarson** [comment]
@karuppiah7890 the challengeSeed is the key for a YouTube video that demos the project. You can leave it blank for now and I may be able to record one later (or we may get rid of these videos all together as part of the redesign).

**Comment by karuppiah7890** [comment]
Okay!
