### ISSUE TITLE
100 Doors challenge

### ISSUE THREAD

**Issue by smileytechguy** [FreeCodeCamp/CurriculumExpansion#91]
#### Challenge Name
100 doors problem

#### Challenge Description
The 100 doors problem is as follows:
```
There are 100 doors in a row that are all initially closed.

You make 100 passes by the doors.

The first time through, visit every door and toggle the door (if the door is closed, open it; if it is open, close it).

The second time, only visit every 2nd door (door #2, #4, #6, ...), and toggle it.

The third time, visit every 3rd door (door #3, #6, #9, ...), etc, until you only visit the 100th door.
```

#### Your Code

```js
 // output
var log = function(i) {
    if (console == undefined) {
        debug(i);
    } else {
        console.log(i);
    }
} 

// toggle a boolean
var toggle = function(item) {
    if (item) { // do not need to check if bool due to arg
        return false;
    } else {
        return true;
    }
}

// initialize array of 100 doors, all closed or false
var doors = Array(100).fill(false);

var step = 1;
while (step <= doors.length) {
    for (i = step-1; i < doors.length; i+=step) {
        doors[i] = toggle(doors[i]);
    }
    step += 1;
}

// print raw contents
log("Raw array contents");
log(doors);

// loop through, find closed (false) indecies
log("");
log("Closed doors:");
var s = "[ ";
for (var x = 0; x < doors.length; x++) {
    if (doors[x] == false) {
        s += (x+1)+" ";
    }
}
s += "]"; // close it
log(s);

// loop through, find open (true) indecies
log("");
log("Open doors:");
var s = "[ ";
for (var x = 0; x < doors.length; x++) {
    if (doors[x] == true) {
        s += (x+1)+" ";
    }
}
s += "]"; // close it
log(s);
```
I use the jsc CLI interface a lot, so thats why I use log().  Check out https://github.com/smileytechguy/sample_projects/tree/master/100_doors for more implementations.

This challenge would require implementation of multiple for loops, or as I had a while and for loop.

**Comment by QuincyLarson** [comment]
@smileytechguy awesome - this is a cool challenge idea. Could you write a series of tests that verify  the solution is correct - preferably tests that would be passed progressively as the camper codes the solution, rather than all at once when they finish it?

**Comment by smileytechguy** [comment]
@QuincyLarson Sure!  What is the format, as I haven't contributed here before?

**Comment by smileytechguy** [comment]
**Challenge**

This challenge would be to solve the 100 doors problem [original source](https://www.rosettacode.org/wiki/100_doors)

**Challenge Description**

> There are 100 doors in a row that are all initially closed.

> You make 100 passes by the doors.

> The first time through, visit every door and toggle the door (if the door is closed, open it; if it is open, close it).

> The second time, only visit every 2nd door (door #2, #4, #6, ...), and toggle it.

> The third time, visit every 3rd door (door #3, #6, #9, ...), etc, until you only visit the 100th door.

**Challenge Seed**



**Challenge Tests**



**Challenge Solution**

**Comment by QuincyLarson** [comment]
@smileytechguy awesome! Well done! We can add this to our advanced algorithm challenges :)

**Comment by QuincyLarson** [comment]
Thanks for your help everyone! We've loaded these challenges into the seed files and plan to deploy them to beta as soon as possible. 

I'm closing this issue. If anyone wants to discuss these further, please reopen it.

**Comment by smileytechguy** [comment]
@QuincyLarson awesome!  Where can I find the beta track?

**Comment by QuincyLarson** [comment]
@smileytechguy it'll be at beta.freecodecamp.com as soon as we deploy it :)

**Comment by smileytechguy** [comment]
awesome!

**Comment by QuincyLarson** [comment]
@smileytechguy I've added this to our seed files and it will show up in its own new section as soon as we deploy.

**Comment by smileytechguy** [comment]
@QuincyLarson aright, awesome!  thanks
