### ISSUE TITLE
"Unit Testing" Waypoints

### ISSUE THREAD

**Issue by pmbenjamin** [freeCodeCamp/CurriculumExpansion#92]
There were a few github issues in FreeCodeCamp repo that were opened to discuss "Unit Testing" lessons/waypoints. I could not find any resolution for them in FreeCodeCamp repo or in CurriculumExpansion repo.

Namely, these 2 related issues:
- https://github.com/freeCodeCamp/freeCodeCamp/issues/5602 
- https://github.com/freeCodeCamp/freeCodeCamp/issues/5847

Is this suggestion still being considered?

**Comment by erictleung** [comment]
@pmbenjamin here are the challenges on unit testing https://github.com/freeCodeCamp/CurriculumExpansion/issues/48

**Comment by pmbenjamin** [comment]
Thank you, I will continue the discussion there!
