### ISSUE TITLE
Basic Data Structures: Modify an Array Stored in an Object

### ISSUE THREAD

**Issue by Jamiemufu** [freeCodeCamp/CurriculumExpansion#94]
Just going through the beta challenges and learning in the process, I think I may have found a problem with passing Basic Data Structures: Modify an Array stored in an Object.

In my Dev Tools console I have passed, I see the the new array with "Pete" under friends, but can't pass the challenge

```
`let user = {
  name: 'Kenneth',
  age: 28,
  data: {
    username: 'kennethCodesAllDay',
    joinDate: 'March 26, 2016',
    organization: 'freeCodeCamp',
    friends: [
      'Sam',
      'Kira',
      'Tomo'
    ],
    location: {
      city: 'San Francisco',
      state: 'CA',
      country: 'USA'
    }
  }
};

function addFriend(userObj, friend) {
  // change code below this line  
userObj.data.friends.push(friend);
  return userObj;
  // change code above this line
}

console.log(addFriend(user, 'Pete'));
````
First time posting a problem, so apologise if wrongly done

**Comment by doanldbanton** [comment]
You're not suppose to return the entire user object : 
 // change code below this line  
 userObj.data.friends.push(friend);
    return userObj.data.friends;
  // change code above this line
