### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by TomaszRybacki** [freeCodeCamp/CurriculumExpansion#96]
Remove Elements from a Linked List. 
Provided solution fails tests on freeCodeCamp site.
Consol output: currentNode is not defined.

**Comment by erictleung** [comment]
Thanks for your issue! For any current issues with the curriculum, I'd suggest to first share this on the [Contributors](https://gitter.im/FreeCodeCamp/Contributors) Gitter channel to verify that this is indeed a problem. Once they approve or at least double check that it is a problem, you can go ahead to open an issue on the [main repository](https://github.com/freeCodeCamp/freeCodeCamp/issues/new) for more direct feedback. Thanks and happy coding!
